### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by 157946a** [FlickerProjects/TrChat#1]
[17:15:45 WARN]: [Adyeshach] Task #224 for Adyeshach v1.3.6 generated an exception
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:914) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:346) ~[?:?]
        at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1120) ~[?:?]
        at java.util.jar.JarFile.getEntry0(JarFile.java:576) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:506) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:120) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at ink.ptms.adyeshach.taboolib.module.database.Database.createDataSource(Database.kt:18) ~[?:?]
        at ink.ptms.adyeshach.taboolib.module.database.Database.createDataSource$default(Database.kt:17) ~[?:?]
        at ink.ptms.adyeshach.taboolib.module.database.Host.createDataSource(Host.kt:18) ~[?:?]
        at ink.ptms.adyeshach.internal.database.DatabaseLocal.<init>(DatabaseLocal.kt:35) ~[?:?]
        at ink.ptms.adyeshach.api.AdyeshachAPI$database$2.invoke(AdyeshachAPI.kt:42) ~[?:?]
        at ink.ptms.adyeshach.api.AdyeshachAPI$database$2.invoke(AdyeshachAPI.kt:40) ~[?:?]
        at taboolib.library.kotlin_1_5_10.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at ink.ptms.adyeshach.api.AdyeshachAPI.getDatabase(AdyeshachAPI.kt:40) ~[?:?]
        at ink.ptms.adyeshach.api.AdyeshachAPI.getEntityManagerPrivate$lambda-0(AdyeshachAPI.kt:61) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
        at ink.ptms.adyeshach.api.AdyeshachAPI.getEntityManagerPrivate(AdyeshachAPI.kt:61) ~[?:?]
        at ink.ptms.adyeshach.common.entity.manager.ManagerEvents$onTick$2$1$1.invoke(ManagerEvents.kt:63) ~[?:?]
        at ink.ptms.adyeshach.common.entity.manager.ManagerEvents$onTick$2$1$1.invoke(ManagerEvents.kt:62) ~[?:?]
        at ink.ptms.adyeshach.taboolib.common5.MirrorKt.mirrorNow(Mirror.kt:17) ~[?:?]
        at ink.ptms.adyeshach.common.entity.manager.ManagerEvents$onTick$2.invoke(ManagerEvents.kt:62) ~[?:?]
        at ink.ptms.adyeshach.common.entity.manager.ManagerEvents$onTick$2.invoke(ManagerEvents.kt:60) ~[?:?]
        at ink.ptms.adyeshach.taboolib.platform.BukkitExecutor$submit$3.run(BukkitExecutor.kt:60) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by 157946a** [comment]
paper1.12.2

**Comment by 157946a** [comment]
@Bkm016

**Comment by Micalhl** [comment]
@Bkm016

**Comment by ItsFlicker** [comment]
给个完整日志

**Comment by 157946a** [comment]
> 请提供完整日志
https://cowtransfer.com/s/8e07339e9c1447

**Comment by ItsFlicker** [comment]
用TrChat 1.80试试
你的日志中没出现上面的报错啊

**Comment by Bkm016** [comment]
眼睛不好就别开服

**Comment by 157946a** [comment]
> 眼睛不好就别开服

鬼知道你还加了时间限制

**Comment by 157946a** [comment]
[01:49:04 INFO]: [TrChat] INFO | 加载完毕. TrChat v1.8 现已启用, 敬请使用.
[01:49:04 INFO]: [TrChat] 你正在运行开发版本的 TrChat, 请及时反馈漏洞/提出建议!
[01:49:04 ERROR]: Error occurred while enabling TrChat v1.8 (Is it up to date?)
java.lang.NoSuchFieldError: timings
        at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke(BukkitCommand.kt:102) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke(BukkitCommand.kt:65) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitExecutor$submit$1.<init>(BukkitExecutor.kt:39) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitExecutor.submit(BukkitExecutor.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitExecutor.start(BukkitExecutor.kt:28) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ExecutorKt.startExecutor(Executor.kt:11) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:70) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[01:49:04 INFO]: [TrChat] Disabling TrChat v1.8
[01:49:04 INFO]: [TrChat] INFO | 感谢使用本插件, 您在论坛为本插件评分即是对作者最大的鼓励


新问题

**Comment by ItsFlicker** [comment]
该问题新版本已修复

**Comment by 157946a** [comment]
1.80无法加载呢,加载后将trmenu zip file closed呢,这两个
