### ISSUE TITLE
[BUG] Cat-1.12 无法启动插件

### ISSUE THREAD

**Issue by 849025143** [FlickerProjects/TrChat#100]
[12:02:30] [Server thread/ERROR]: Could not load 'plugins\TrChat-2.0.0-PRE-1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[JavaPluginLoader.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[SimplePluginManager.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [SimplePluginManager.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:359) [CraftServer.class:git-CatServer-1.12.2-a8b73e9]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:340) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
        at me.arasple.mc.trchat.module.display.function.InventoryShow$cooldown$1.invoke(InventoryShow.kt:44) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.configuration.ConfigNodeTransfer.update$module_configuration(ConfigNodeTransfer.kt:17) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.configuration.ConfigInjector$NodeLoader.inject(ConfigInjector.kt:97) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.inject(RuntimeInjector.java:112) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.injectAll(RuntimeInjector.java:65) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:128) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:86) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.<init>(BukkitPlugin.java:42) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_311]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_311]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_311]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_311]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_311]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[PluginClassLoader.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-a8b73e9]

**Comment by ItsFlicker** [comment]
2.0需要重新生成所有配置
