### ISSUE TITLE
新版本与Paper 1.16.5报错 

### ISSUE THREAD

**Issue by lovemercer** [FlickerProjects/TrChat#101]
核心版本paper-1.16.5-794.jar
java版本16
无法启动，报错如下

[11:53:29 ERROR]: Could not load 'plugins/TrChat-2.0.0-PRE-1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException: Parameter specified as non-null is null: method me.arasple.mc.trchat.api.config.Functions$commandController$1.invoke, parameter $this$$receiver
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method me.arasple.mc.trchat.api.config.Functions$commandController$1.invoke, parameter $this$$receiver
        at me.arasple.mc.trchat.api.config.Functions$commandController$1.invoke(Functions.kt) ~[?:?]
        at me.arasple.mc.trchat.api.config.Functions$commandController$1.invoke(Functions.kt:40) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.configuration.ConfigNodeTransfer.update$module_configuration(ConfigNodeTransfer.kt:17) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.configuration.ConfigInjector$NodeLoader.inject(ConfigInjector.kt:97) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.inject(RuntimeInjector.java:112) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.injectAll(RuntimeInjector.java:65) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:128) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:86) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.<init>(BukkitPlugin.java:42) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350) ~[?:?]
        at java.lang.Class.newInstance(Class.java:642) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:94) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Paper-794]
        ... 7 more

**Comment by ItsFlicker** [comment]
2.0要重新生成所有配置
