### ISSUE TITLE
子服连不上全局聊天

### ISSUE THREAD

**Issue by LyingYi** [FlickerProjects/TrChat#106]
1.8.8 nachospigot 使用最新版插件 所有配置文件都一样 但4个服中只有一个在开服时显示已支持bungee通讯 其他服务器可以使用全局聊天但别的服务器接收不到 bc也只有在开服时显示了支持bungee通讯的那个服务器的消息
另外1.8核心需要在datasource.yml中将ConnectionTestQuery改为SELECT 1才能正常启动

**Comment by LyingYi** [comment]
edit 1：不是开服时间问题 只有那一个特定的服务器连得上 但是那个服的trchat taboolib版本都和其他服是一样的

**Comment by LyingYi** [comment]
更正：taboolib为protocollib 都为4.8

**Comment by ItsFlicker** [comment]
1.8可能确有此问题，调查中

**Comment by ItsFlicker** [comment]
> 另外1.8核心需要在datasource.yml中将ConnectionTestQuery改为SELECT 1才能正常启动

1.8只能改，无法修复

**Comment by LyingYi** [comment]
那还是麻烦在config或者哪里写一下吧。。

**Comment by FZDNSZYT** [comment]
> > 另外1.8核心需要在datasource.yml中将ConnectionTestQuery改为SELECT 1才能正常启动
> 
> 1.8只能改，无法修复

但是还是无法加入全局聊天，其他高版本就没有这个问题

**Comment by LyingYi** [comment]
> > > 另外1.8核心需要在datasource.yml中将ConnectionTestQuery改为SELECT 1才能正常启动
> > 
> > 
> > 1.8只能改，无法修复
> 
> 但是还是无法加入全局聊天，其他高版本就没有这个问题

是啊 也找不到什么1.8的跨服聊天了 哎

**Comment by ItsFlicker** [comment]
明天修



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月10日(周日) 凌晨1:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FlickerProjects/TrChat] 子服连不上全局聊天 (Issue #106)




    
另外1.8核心需要在datasource.yml中将ConnectionTestQuery改为SELECT 1才能正常启动
  
1.8只能改，无法修复
  
但是还是无法加入全局聊天，其他高版本就没有这个问题
  
是啊 也找不到什么1.8的跨服聊天了 哎

**Comment by ItsFlicker** [comment]
尝试使用2.0.0-PRE-4并把settings.yml中的Options.Force-Proxy设为BUNGEE

**Comment by LyingYi** [comment]
> 尝试使用2.0.0-PRE-4并把settings.yml中的Options.Force-Proxy设为BUNGEE
[16:10:29] [Server thread/INFO]: YingYii issued server command: /all 1
[16:10:29] [nioEventLoopGroup-3-4/ERROR]: Could not pass event PacketSendEvent to TrChat v2.0.0-PRE-4
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor124.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_321]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[?:?]
...
Caused by: java.lang.NoSuchMethodException: a() at class java.lang.Byte
	at me.arasple.mc.trchat.taboolib.common.reflect.Reflex.invoke(Reflex.kt:73) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.invokeMethod(Reflex.kt:115) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.invokeMethod$default(Reflex.kt:111) ~[?:?]
	at me.arasple.mc.trchat.api.nms.NMSListener.e(NMSListener.kt:38) ~[?:?]
	... 33 more
聊天、输/all、进入和退出服务器等均会触发

**Comment by ItsFlicker** [comment]
@LyingYi Try this https://github.com/FlickerProjects/TrChat/actions/runs/2143324335

**Comment by LyingYi** [comment]
> @LyingYi Try this https://github.com/FlickerProjects/TrChat/actions/runs/2143324335

已解决 感谢
