### ISSUE TITLE
Trchat 插件 在paper 1.16.5 790 核心下无法加载

### ISSUE THREAD

**Issue by XCWQW1** [FlickerProjects/TrChat#111]
![7Y%2C)MNC%2$HX4H0Z86Y03](https://user-images.githubusercontent.com/104244911/164877981-0a3eb53a-d6cd-44b4-b920-289198097461.png)
![F8M) ~TU~2 GN$LN4JFP)QL](https://user-images.githubusercontent.com/104244911/164877985-5fff3742-b7ba-4a8c-972f-2d53f9380a82.png)

核心paper 1.16.5 790
papi版本 2.11.1
trchat版本 2.0.0 PRE 1
服务端插件
![VCQ8D63{R{%PR3%Q9COGPKJ](https://user-images.githubusercontent.com/104244911/164878054-6ccbeee7-4352-4d58-a6fc-4d3d53c4a7a8.png)

**Comment by XCWQW1** [comment]
日志：

**Comment by XCWQW1** [comment]
[12:32:54] [Server thread/INFO]: [TrChat] Loading TrChat v2.0.0-PRE-1
[12:32:54] [Server thread/INFO]: 
[12:32:54] [Server thread/INFO]: 正在加载 TrChat... 1.16.5-R0.1-SNAPSHOT
[12:32:54] [Server thread/INFO]:

**Comment by XCWQW1** [comment]
日志
[12:32:54] [Server thread/INFO]: [TrChat] Loading TrChat v2.0.0-PRE-1
[12:32:54] [Server thread/INFO]: 
[12:32:54] [Server thread/INFO]: 正在加载 TrChat... 1.16.5-R0.1-SNAPSHOT
[12:32:54] [Server thread/INFO]: 

[12:33:02] [Server thread/INFO]: [TrChat] Enabling TrChat v2.0.0-PRE-1
[12:33:02] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: trchat [2.0.0-PRE-1]
[12:33:02] [Server thread/ERROR]: Error occurred while enabling TrChat v2.0.0-PRE-1 (Is it up to date?)
java.lang.NoSuchMethodError: net.kyori.adventure.platform.facet.FacetAudience.getOrDefault(Lnet/kyori/adventure/pointer/Pointer;Ljava/lang/Object;)Ljava/lang/Object;
	at net.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:113) ~[?:?]
	at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.<init>(BukkitAudiencesImpl.java:99) ~[?:?]
	at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.lambda$build$1(BukkitAudiencesImpl.java:175) ~[?:?]
	at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_321]
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_321]
	at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.build(BukkitAudiencesImpl.java:173) ~[?:?]
	at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:89) ~[?:?]
	at net.kyori.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53) ~[?:?]
	at me.arasple.mc.trchat.util.Util.init(Util.kt:38) ~[?:?]
	at me.arasple.mc.trchat.TrChat.onEnable(TrChat.kt:56) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:61) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-790]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]
[12:33:02] [Server thread/INFO]: [TrChat] Disabling TrChat v2.0.0-PRE-1
[12:33:02] [Server thread/ERROR]: Error occurred while disabling TrChat v2.0.0-PRE-1 (Is it up to date?)
kotlin1610.UninitializedPropertyAccessException: lateinit property adventure has not been initialized
	at me.arasple.mc.trchat.util.Util.getAdventure(Util.kt:34) ~[?:?]
	at me.arasple.mc.trchat.util.Util.release(Util.kt:42) ~[?:?]
	at me.arasple.mc.trchat.TrChat.onDisable(TrChat.kt:71) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onDisable(BukkitPlugin.java:85) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-790]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]

**Comment by Yurinann** [comment]
https://github.com/FlickerProjects/TrChat/actions/runs/2143752021

尝试使用最新构建版本

**Comment by XCWQW1** [comment]
已解决,感谢
