### ISSUE TITLE
请支持velocity3.1.2

### ISSUE THREAD

**Issue by 864063334** [FlickerProjects/TrChat#113]
[14:06:17 ERROR]: java.io.FileNotFoundException: https://repo2s.ptms.ink/repository/maven-public/net/md-5/bungeecord-chat/1.17/bungeecord-chat-1.17.pom
[14:06:17 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
[14:06:17 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[14:06:17 ERROR]:       at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[14:06:17 ERROR]:       at java.base/java.net.URL.openStream(URL.java:1161)
[14:06:17 ERROR]:       at me.arasple.mc.trchat.taboolib.common.env.RuntimeEnv.loadDependency(RuntimeEnv.java:179)
[14:06:17 ERROR]:       at me.arasple.mc.trchat.taboolib.common.env.RuntimeEnv.inject(RuntimeEnv.java:66)
[14:06:17 ERROR]:       at me.arasple.mc.trchat.taboolib.common.platform.PlatformFactory.init(PlatformFactory.kt:23)
[14:06:17 ERROR]:       at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:122)
[14:06:17 ERROR]:       at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.<clinit>(VelocityPlugin.java:43)
[14:06:17 ERROR]:       at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$4796824.GUICE$TRAMPOLINE(<generated>)
[14:06:17 ERROR]:       at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$4796824.apply(<generated>)
[14:06:17 ERROR]:       at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
[14:06:17 ERROR]:       at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
[14:06:17 ERROR]:       at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
[14:06:17 ERROR]:       at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
[14:06:17 ERROR]:       at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[14:06:17 ERROR]:       at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
[14:06:17 ERROR]:       at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
[14:06:17 ERROR]:       at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100)
[14:06:17 ERROR]:       at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)
[14:06:17 ERROR]:       at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:121)
[14:06:17 ERROR]:       at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:151)
[14:06:17 ERROR]:       at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:342)
[14:06:17 ERROR]:       at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:223)
[14:06:17 ERROR]:       at com.velocitypowered.proxy.Velocity.main(Velocity.java:64)

**Comment by FLYEMOJ1** [comment]
疑似相应的pom文件修改了位置
https://repo2s.ptms.ink/repository/releases/net/md-5/bungeecord-chat/1.17/bungeecord-chat-1.17.pom
感觉是开发这里没有即使更新 在他们的Repository Manager里面没有maven-public这个repo
我啥也不会只是随口提一句而已（

**Comment by 864063334** [comment]
> 请上传日志文件
[latest.log](https://github.com/FlickerProjects/TrChat/files/8590296/latest.log)

**Comment by 157946a** [comment]
等待更新,地址位置错误的原因
