### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [FlickerProjects/TrChat#131]
[08:41:40] [Server thread/INFO]: [TrChat] Enabling TrChat v2.0.0-PRE-7
[08:41:40] [Server thread/ERROR]: Error occurred while enabling TrChat v2.0.0-PRE-7 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/platform/bukkit/BukkitAudiences
        at me.arasple.mc.trchat.util.Util.init(Util.kt:40) ~[?:?]
        at me.arasple.mc.trchat.TrChat.onEnable(TrChat.kt:59) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:61) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-1f1c21e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-1f1c21e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-1f1c21e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:438) [CraftServer.class:git-CatServer-1.12.2-1f1c21e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServer-1.12.2-1f1c21e]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.platform.bukkit.BukkitAudiences
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:141) ~[PluginClassLoader.class:git-CatServer-1.12.2-1f1c21e]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-1f1c21e]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]
        ... 12 more
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.platform.bukkit.BukkitAudiences
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_321]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[PluginClassLoader.class:git-CatServer-1.12.2-1f1c21e]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-1f1c21e]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]
        ... 12 more

**Comment by ghost** [comment]
The core of this server is CatServer
