### ISSUE TITLE
加载插件时出现 NPE 错误

### ISSUE THREAD

**Issue by Chihsiao** [FlickerProjects/TrChat#132]
```
> Loading libraries, please wait...
[15:31:21 WARN]: [TrChat] Loaded class kotlin.Metadata from Mechanisms v1.9.3-SNAPSHOT which is not a depend or softdepend of this plugin.
[15:31:22 ERROR]: Could not load 'plugins/TrChat-2.0.0-PRE-7.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException: Parameter specified as non-null is null: method me.arasple.mc.trchat.module.display.function.InventoryShow$cooldown$1.invoke, parameter $this$$receiver
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-335]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-335]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-335]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-335]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method me.arasple.mc.trchat.module.display.function.InventoryShow$cooldown$1.invoke, parameter $this$$receiver
        at me.arasple.mc.trchat.module.display.function.InventoryShow$cooldown$1.invoke(InventoryShow.kt) ~[TrChat-2.0.0-PRE-7.jar:?]
        at me.arasple.mc.trchat.module.display.function.InventoryShow$cooldown$1.invoke(InventoryShow.kt:43) ~[TrChat-2.0.0-PRE-7.jar:?]
        at me.arasple.mc.trchat.taboolib.module.configuration.ConfigNodeTransfer.update$module_configuration(ConfigNodeTransfer.kt:17) ~[TrChat-2.0.0-PRE-7.jar:?]
        at me.arasple.mc.trchat.taboolib.module.configuration.ConfigInjector$NodeLoader.inject(ConfigInjector.kt:97) ~[TrChat-2.0.0-PRE-7.jar:?]
        at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.inject(RuntimeInjector.java:112) ~[TrChat-2.0.0-PRE-7.jar:?]
        at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.injectAll(RuntimeInjector.java:65) ~[TrChat-2.0.0-PRE-7.jar:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:128) ~[TrChat-2.0.0-PRE-7.jar:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:86) ~[TrChat-2.0.0-PRE-7.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.<init>(BukkitPlugin.java:42) ~[TrChat-2.0.0-PRE-7.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:83) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 7 more
```

**Comment by 157946a** [comment]
删除配置重新生成
