### ISSUE TITLE
开服报错

### ISSUE THREAD

**Issue by mfcc168** [FlickerProjects/TrChat#135]
[23:28:21 ERROR]: Could not load 'plugins\TrChat-2.0.0-PRE-9.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException: Parameter specified as non-null is null: method me.arasple.mc.trchat.module.display.function.EnderChestShow$cooldown$1.invoke, parameter $this$$receiver
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[server.jar:git-Paper-4466fe0]        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[server.jar:git-Paper-4466fe0]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[server.jar:git-Paper-4466fe0]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:319) ~[server.jar:git-Paper-4466fe0]        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:226) ~[server.jar:git-Paper-4466fe0]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:621) ~[server.jar:git-Paper-4466fe0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method me.arasple.mc.trchat.module.display.function.EnderChestShow$cooldown$1.invoke, parameter $this$$receiver
        at me.arasple.mc.trchat.module.display.function.EnderChestShow$cooldown$1.invoke(EnderChestShow.kt) ~[?:?]
        at me.arasple.mc.trchat.module.display.function.EnderChestShow$cooldown$1.invoke(EnderChestShow.kt:46) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.configuration.ConfigNodeTransfer.update$module_configuration(ConfigNodeTransfer.kt:17) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.configuration.ConfigInjector$NodeLoader.inject(ConfigInjector.kt:87) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.inject(RuntimeInjector.java:112) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.injectAll(RuntimeInjector.java:65) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:131) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:89) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.<init>(BukkitPlugin.java:46) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_321]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_321]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_321]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_321]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_321]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:94) ~[server.jar:git-Paper-4466fe0]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[server.jar:git-Paper-4466fe0]        ... 6 more

**Comment by 157946a** [comment]
https://github.com/FlickerProjects/TrChat/issues/134 一样的问题
