### ISSUE TITLE
1.18.2 Error

### ISSUE THREAD

**Issue by ItsEricRao** [FlickerProjects/TrChat#136]
`[Server thread/ERROR]: Could not load 'plugins/TrChat-2.0.0-PRE-9.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException: Parameter specified as non-null is null: method me.arasple.mc.trchat.module.display.function.EnderChestShow$cooldown$1.invoke, parameter $this$$receiver
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[purpur-1.18.2.jar:git-Purpur-1626]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[purpur-1.18.2.jar:git-Purpur-1626]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1626]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1626]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method me.arasple.mc.trchat.module.display.function.EnderChestShow$cooldown$1.invoke, parameter $this$$receiver
	at me.arasple.mc.trchat.module.display.function.EnderChestShow$cooldown$1.invoke(EnderChestShow.kt) ~[TrChat-2.0.0-PRE-9.jar:?]
	at me.arasple.mc.trchat.module.display.function.EnderChestShow$cooldown$1.invoke(EnderChestShow.kt:46) ~[TrChat-2.0.0-PRE-9.jar:?]
	at me.arasple.mc.trchat.taboolib.module.configuration.ConfigNodeTransfer.update$module_configuration(ConfigNodeTransfer.kt:17) ~[TrChat-2.0.0-PRE-9.jar:?]
	at me.arasple.mc.trchat.taboolib.module.configuration.ConfigInjector$NodeLoader.inject(ConfigInjector.kt:87) ~[TrChat-2.0.0-PRE-9.jar:?]
	at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.inject(RuntimeInjector.java:112) ~[TrChat-2.0.0-PRE-9.jar:?]
	at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.injectAll(RuntimeInjector.java:65) ~[TrChat-2.0.0-PRE-9.jar:?]
	at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:131) ~[TrChat-2.0.0-PRE-9.jar:?]
	at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:89) ~[TrChat-2.0.0-PRE-9.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.<init>(BukkitPlugin.java:46) ~[TrChat-2.0.0-PRE-9.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
	at java.lang.Class.newInstance(Class.java:645) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:85) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	... 7 more`

服务器核心为**Purpur 1.18.2**，之前拿**Paper 1.17.1**跑没有问题的
插件版本是**2.0.0-PRE-9**
不知道为什么，尝试删除libs目录还是无效
有什么解决方案吗

**Comment by 157946a** [comment]
https://github.com/FlickerProjects/TrChat/issues/135

**Comment by ItsEricRao** [comment]
> #135

但是我还是没有找到我手头哪个插件冲突了qwq，大佬能帮忙看一下吗
`Plugins (51): Adyeshach, AntiWorldFly, ArtMap, AuthMe, BanItem, BossShopPro, ChatItemDisplay, CMILib, Coins, ConditionalTextPlaceholders, CoreProtect, CustomCrafting, DeluxeHub, dynmap, DynMap_Residence, Elevators, FastAsyncWorldEdit (WorldEdit), GSit, Harbor, iAFK, ImageOnMap, InvSeePlusPlus, KeepChunks, LiteSignIn, LiteTeleport, LuckPerms, Multiverse-Core, Multiverse-Inventories, MyCommand, Oraxen, PlaceholderAPI, PlayerKits, PlayerParticles, ProtocolLib, PublicBin, QuickShop, RedPacket*, Residence, ScriptBlockPlus, ScriptEntityPlus, ServerlistMOTD*, SkinsRestorer, Slimefun, TAB, TheNewEconomy, TrHologram, TrMenu, UltimateTimber, Vault, WolfyUtilities, WorldGuard`

**Comment by 157946a** [comment]
不是冲突了,他冲突是bc的插件冲突,你要看他子服

**Comment by 157946a** [comment]
不是冲突了,他冲突是bc的插件冲突,你要看他子服

**Comment by ItsEricRao** [comment]
> 不是冲突了,他冲突是bc的插件冲突,你要看他子服,子服并不是冲突了,是因为function内容有改动,并且这个改动无法自动帮你补上,就出现了报错

啊这，function.yml在哪里，在服务器里翻了半天没找到

**Comment by ItsEricRao** [comment]
> 不是冲突了,他冲突是bc的插件冲突,你要看他子服,子服并不是冲突了,是因为function内容有改动,并且这个改动无法自动帮你补上,就出现了报错

大佬我删除了function.yml为什么还跑不了啊，报错内容还是一样的 :/

**Comment by 157946a** [comment]
上传

**Comment by ItsEricRao** [comment]
> 上传

没事了，我的问题，可能是config文件新版本的不一样我可能旧版本的读取不了之类的吧？？？我反正直接把TrChat整个文件夹删了重置又可以跑了
