### ISSUE TITLE
CatServer端无故报错

### ISSUE THREAD

**Issue by ghost** [FlickerProjects/TrChat#137]
[18:47:00] [Server thread/ERROR]: Error occurred while enabling TrChat v2.0.0-PRE-9 (Is it up to date?) java.lang.NoClassDefFoundError: net/kyori/adventure/platform/bukkit/BukkitAudiences         at me.arasple.mc.trchat.util.Util.init(Util.kt:40) ~[?:?]         at me.arasple.mc.trchat.TrChat.onEnable(TrChat.kt:59) ~[?:?]         at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:65) ~[?:?]         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-6eb82ffe]         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-6eb82ffe]         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]         at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:438) [CraftServer.class:git-CatServer-1.12.2-6eb82ffe]         at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServer-1.12.2-6eb82ffe]         at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330) [nz.class:?]         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [MinecraftServer.class:?]         at java.lang.Thread.run(Unknown Source) [?:1.8.0_321] Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.platform.bukkit.BukkitAudiences         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:141) ~[PluginClassLoader.class:git-CatServer-1.12.2-6eb82ffe]         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-6eb82ffe]         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]         ... 12 more Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.platform.bukkit.BukkitAudiences         at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_321]         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[PluginClassLoader.class:git-CatServer-1.12.2-6eb82ffe]         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-6eb82ffe]         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]         ... 12 more

**Comment by ghost** [comment]
于MCBBS中说的，尝试删除Libs文件夹并重启服务器，依旧报错

**Comment by 157946a** [comment]
检查是否是插件或者模组冲突,测试无法复现

**Comment by ItsFlicker** [comment]
后续会出shadow版本

**Comment by ItsFlicker** [comment]
尝试使用https://github.com/TrPlugins/TrChat/actions/runs/2560479915 中的shaded版本
