### ISSUE TITLE
trchat似乎与miraimc冲突

### ISSUE THREAD

**Issue by hexadecimal233** [FlickerProjects/TrChat#139]
``java.lang.LinkageError: loader constraint violation: when resolving method 'kotlin.Lazy kotlin.LazyKt.lazy(kotlin.jvm.functions.Function0)' the class loader 'TrChat-2.0.0-PRE-10.jar' @5ce6b1e1 of the current class, me/arasple/mc/trchat/util/FileListener, and the class loader 'MiraiMC-Bukkit.jar' @ef5be59 for the method's defining class, kotlin/LazyKt__LazyJVMKt, have different Class objects for the type kotlin/jvm/functions/Function0 used in the signature (me.arasple.mc.trchat.util.FileListener is in unnamed module of loader 'TrChat-2.0.0-PRE-10.jar' @5ce6b1e1, parent loader java.net.URLClassLoader @1b701da1; kotlin.LazyKt__LazyJVMKt is in unnamed module of loader 'MiraiMC-Bukkit.jar' @ef5be59, parent loader java.net.URLClassLoader @1b701da1)
        at me.arasple.mc.trchat.util.FileListener.<clinit>(FileListener.kt:18) ~[TrChat-2.0.0-PRE-10.jar:?]
        at me.arasple.mc.trchat.module.conf.Loader.loadChannels(Loader.kt:73) ~[TrChat-2.0.0-PRE-10.jar:?]
        at me.arasple.mc.trchat.module.conf.Loader.loadChannels(Loader.kt:62) ~[TrChat-2.0.0-PRE-10.jar:?]
        at me.arasple.mc.trchat.TrChat.onEnable(TrChat.kt:65) ~[TrChat-2.0.0-PRE-10.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:65) ~[TrChat-2.0.0-PRE-10.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-379]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]``

**Comment by ItsFlicker** [comment]
先用上个版本吧
