### ISSUE TITLE
1.19 paper端 无法展示物品

### ISSUE THREAD

**Issue by llw05** [FlickerProjects/TrChat#142]
在输入%i 之后 后台就会显示报错
22:49:33 INFO]: [Yum] [Yum 事件监控] 插件 TrChat 处理 AsyncPlayerChatEvent 事件时发生异常!
[22:49:33 INFO]: [Yum] 异常名称: java.lang.NoSuchMethodError
[22:49:33 INFO]: [Yum] 异常说明: 'net.minecraft.server.v1_19_R1.ItemStack org.bukkit.craftbukkit.v1_19_R1.inventory.CraftItemStack.asNMSCopy(org.bukkit.inventory.ItemStack)'
[22:49:33 INFO]: [Yum] 简易错误信息如下:
[22:49:33 INFO]: [Yum]     位于 me.arasple.mc.trchat.taboolib.module.nms.NMSGenericImpl.getName(NMSGenericImpl.java:118)
[22:49:33 INFO]: [Yum]     位于 me.arasple.mc.trchat.taboolib.module.nms.NMSKt.getInternalName(NMS.kt:83)
[22:49:33 INFO]: [Yum]     位于 me.arasple.mc.trchat.taboolib.module.nms.i18n.I18nOrigin.getName(I18nOrigin.java:85)
[22:49:33 INFO]: [Yum]     位于 me.arasple.mc.trchat.taboolib.module.nms.NMSKt.getI18nName(NMS.kt:87)
[22:49:33 INFO]: [Yum]     位于 me.arasple.mc.trchat.module.display.function.ItemShow.getDisplayName(ItemShow.kt:96)
这个是yum给他发出来的报错
我下面给你看看没装yum 出来的报错
[22:16:19] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.0-PRE-10
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:116) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[TrChat-2.0.0-PRE-10.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-17]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:195) ~[paper-1.19.jar:git-Paper-17]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:67) ~[paper-1.19.jar:git-Paper-17]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2295) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2251) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$20(ServerGamePacketListenerImpl.java:2224) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java:2224) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$16(ServerGamePacketListenerImpl.java:2121) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.onarandombox.MultiverseCore.MultiverseCore.getMVWorldManager()" because "this.core" is null
	at com.extendedclip.papi.expansion.multiverse.MultiverseExpansion.onPlaceholderRequest(MultiverseExpansion.java:51) ~[?:?]
	at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32) ~[PlaceholderAPI-2.11.1.jar:?]
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:161) ~[PlaceholderAPI-2.11.1.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[PlaceholderAPI-2.11.1.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98) ~[PlaceholderAPI-2.11.1.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.compat.PlaceholderExpansionKt.replacePlaceholder(PlaceholderExpansion.kt:15) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.module.display.format.part.json.Text.process(Text.kt:25) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.module.display.format.part.json.Text.process$default(Text.kt:21) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.module.display.format.JsonComponent$toTextComponent$1.invoke(JsonComponent.kt:27) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.module.display.format.JsonComponent$toTextComponent$1.invoke(JsonComponent.kt:26) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.taboolib.common5.MirrorKt.mirrorNow(Mirror.kt:17) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.module.display.format.JsonComponent.toTextComponent(JsonComponent.kt:26) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:126) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerChatEvent.onChat(ListenerChatEvent.kt:68) ~[TrChat-2.0.0-PRE-10.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	... 24 more

**Comment by 157946a** [comment]
因为没有兼容,而且这个展示物品的功能还未支持1.19

**Comment by 157946a** [comment]
删除yum重新上传报错,

**Comment by 157946a** [comment]
更新到pre17尝试

**Comment by ItsFlicker** [comment]
第二个报错为multiverse拓展错误

**Comment by ItsFlicker** [comment]
更新核心
