### ISSUE TITLE
插件无法加载且报错

### ISSUE THREAD

**Issue by Syscat20** [FlickerProjects/TrChat#146]
服务器核心分别用的是Paper与Sugarcane，游戏版本1.17.1，两者都会出现以下报错，导致插件无法加载。希望可以帮忙看看（
`[18:43:23] [Server thread/ERROR]: Could not load 'plugins\TrChat-2.0.0-PRE-10.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException: Parameter specified as non-null is null: method me.arasple.mc.trchat.module.display.function.Mention$cooldown$1.invoke, parameter $this$$receiver
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method me.arasple.mc.trchat.module.display.function.Mention$cooldown$1.invoke, parameter $this$$receiver
	at me.arasple.mc.trchat.module.display.function.Mention$cooldown$1.invoke(Mention.kt) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.module.display.function.Mention$cooldown$1.invoke(Mention.kt:43) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.taboolib.module.configuration.ConfigNodeTransfer.update$module_configuration(ConfigNodeTransfer.kt:17) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.taboolib.module.configuration.ConfigInjector$NodeLoader.inject(ConfigInjector.kt:87) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.inject(RuntimeInjector.java:112) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.injectAll(RuntimeInjector.java:65) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:131) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:89) ~[TrChat-2.0.0-PRE-10.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.<init>(BukkitPlugin.java:46) ~[TrChat-2.0.0-PRE-10.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
	at java.lang.Class.newInstance(Class.java:645) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:83) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.17.1.jar:git-Paper-411]
	... 7 more
`

**Comment by ItsFlicker** [comment]
重新生成function.yml

**Comment by Syscat20** [comment]
可以了！！感谢
