### ISSUE TITLE
核心为1.17的spigot端，只装了两个插件，PlaceholderAPI-2.10.10和TrChat-1.84，皆为最新版本。

### ISSUE THREAD

**Issue by VK-fgd** [FlickerProjects/TrChat#15]
![1](https://user-images.githubusercontent.com/90676409/133234470-047835af-78fc-4f94-917a-20f0b31cf88e.png)
1. 禁用的敏感词用 ' 这个符号隔开就能打出来，请问怎么在配置文件中将该符号禁用？
![2](https://user-images.githubusercontent.com/90676409/133234633-c2acc9e7-f949-4a5e-b7e0-78128a131bbf.png)
2. 打出单字“b”正常显示，但是打出“bi”显示“*i”。
![3](https://user-images.githubusercontent.com/90676409/133234694-19f23cbe-d5f9-4bae-a040-ec993c9f7884.png)
3. 配置文件“filter.yml”里的白名单无效。
![4](https://user-images.githubusercontent.com/90676409/133234828-502f0214-ffb4-4def-b5eb-d82eee5194a7.png)
![5](https://user-images.githubusercontent.com/90676409/133234848-0d9ae2f5-5332-45bd-ab20-f132774a51e7.png)
4. 有云端敏感词库吗？有的话如何启用？
5. 如输入敏感词，聊天窗口的频道和玩家名都显示为默认的白色（无敏感词是显示为配置文件设置的字体颜色）。
6. 不论发出什么文本，控制台都会先输出一段报错，在输出那一段文本。
报错：
[6.txt](https://github.com/FlickerProjects/TrChat/files/7160764/6.txt)
[17:37:58] [Async Chat Thread - #1/WARN]: java.lang.NoSuchFieldException: ping
[17:37:58] [Async Chat Thread - #1/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:49)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:270)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.taboolib.platform.compat.PlaceholderExpansionKt.replacePlaceholder(PlaceholderExpansion.kt:15)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.common.chat.format.objects.JsonComponent.toTellrawJson(JsonComponent.kt:79)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.common.chat.format.objects.JsonComponent.toTellrawJson(JsonComponent.kt:58)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.common.chat.format.Format.apply(Format.kt:32)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.common.chat.format.Format.apply$default(Format.kt:30)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.common.channel.impl.ChannelNormal.execute(ChannelNormal.kt:29)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.common.channel.ChatChannels$callChannel$1.invoke(ChatChannels.kt:55)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.common.channel.ChatChannels$callChannel$1.invoke(ChatChannels.kt:54)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.taboolib.common5.MirrorKt.mirrorNow(Mirror.kt:17)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.common.channel.ChatChannels.callChannel(ChatChannels.kt:54)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:57)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:39)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.internal.listener.ListenerChatEvent.onChat(ListenerChatEvent.kt:71)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:57)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:1866)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1800)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1766)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat$1.run(PacketPlayInChat.java:40)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[17:37:58] [Async Chat Thread - #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[17:37:58] [Async Chat Thread - #1/INFO]: [0;30;1m[[0;36;22mworld[0;30;1m][0;37;1m [0;37;22mfgd[0;37;22m: [0;37;22mbilibili[m

**Comment by 157946a** [comment]
你先更新最新版本

**Comment by ItsFlicker** [comment]
1. 在filter.yml中的IGNORED-PUNCTUATIONS添加 `"'"`
2. 已修复
3. CLOUD-THESAURUS的WHITELIST为云端库的敏感词白名单
4. 目前无已有的词库，需要自行搭建(添加在CLOUD-THESAURUS.URL并将CLOUD-THESAURUS.ENABLE设为true)
5. 已修复
6. 更新papi变量扩展Player

**Comment by VK-fgd** [comment]
问题已解决，感谢两位大佬的回答。
