### ISSUE TITLE
1.19无法加载

### ISSUE THREAD

**Issue by OshinoLin** [FlickerProjects/TrChat#150]
[21:49:56 ERROR]: Could not load 'plugins\TrChat-2.0.0-PRE-18.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException: Parameter specified as non-null is null: method me.arasple.mc.trchat.api.config.Functions$commandController$1.invoke, parameter $this$$receiver
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:410) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:318) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1670]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method me.arasple.mc.trchat.api.config.Functions$commandController$1.invoke, parameter $this$$receiver
        at me.arasple.mc.trchat.api.config.Functions$commandController$1.invoke(Functions.kt) ~[TrChat-2.0.0-PRE-18.jar:?]
        at me.arasple.mc.trchat.api.config.Functions$commandController$1.invoke(Functions.kt:38) ~[TrChat-2.0.0-PRE-18.jar:?]
        at me.arasple.mc.trchat.taboolib.module.configuration.ConfigNodeTransfer.update$module_configuration(ConfigNodeTransfer.kt:17) ~[TrChat-2.0.0-PRE-18.jar:?]
        at me.arasple.mc.trchat.taboolib.module.configuration.ConfigInjector$NodeLoader.inject(ConfigInjector.kt:87) ~[TrChat-2.0.0-PRE-18.jar:?]
        at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.inject(RuntimeInjector.java:112) ~[TrChat-2.0.0-PRE-18.jar:?]
        at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.injectAll(RuntimeInjector.java:65) ~[TrChat-2.0.0-PRE-18.jar:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:131) ~[TrChat-2.0.0-PRE-18.jar:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:89) ~[TrChat-2.0.0-PRE-18.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.<init>(BukkitPlugin.java:46) ~[TrChat-2.0.0-PRE-18.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:85) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        ... 7 more

**Comment by OshinoLin** [comment]
老配置文件问题

**Comment by ItsFlicker** [comment]
重新生成function.yml



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月28日(周二) 凌晨0:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [TrPlugins/TrChat] 1.19无法加载 (Issue #150)




 
[21:49:56 ERROR]: Could not load 'plugins\TrChat-2.0.0-PRE-18.jar' in folder 'plugins'
 org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException: Parameter specified as non-null is null: method me.arasple.mc.trchat.api.config.Functions$commandController$1.invoke, parameter $this$$receiver
 at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
 at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:410) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
 at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:318) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
 at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[purpur-1.19.jar:git-Purpur-1670]
 at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[purpur-1.19.jar:git-Purpur-1670]
 at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1670]
 at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1670]
 at java.lang.Thread.run(Thread.java:833) ~[?:?]
 Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method me.arasple.mc.trchat.api.config.Functions$commandController$1.invoke, parameter $this$$receiver
 at me.arasple.mc.trchat.api.config.Functions$commandController$1.invoke(Functions.kt) ~[TrChat-2.0.0-PRE-18.jar:?]
 at me.arasple.mc.trchat.api.config.Functions$commandController$1.invoke(Functions.kt:38) ~[TrChat-2.0.0-PRE-18.jar:?]
 at me.arasple.mc.trchat.taboolib.module.configuration.ConfigNodeTransfer.update$module_configuration(ConfigNodeTransfer.kt:17) ~[TrChat-2.0.0-PRE-18.jar:?]
 at me.arasple.mc.trchat.taboolib.module.configuration.ConfigInjector$NodeLoader.inject(ConfigInjector.kt:87) ~[TrChat-2.0.0-PRE-18.jar:?]
 at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.inject(RuntimeInjector.java:112) ~[TrChat-2.0.0-PRE-18.jar:?]
 at me.arasple.mc.trchat.taboolib.common.inject.RuntimeInjector.injectAll(RuntimeInjector.java:65) ~[TrChat-2.0.0-PRE-18.jar:?]
 at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:131) ~[TrChat-2.0.0-PRE-18.jar:?]
 at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:89) ~[TrChat-2.0.0-PRE-18.jar:?]
 at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.(BukkitPlugin.java:46) ~[TrChat-2.0.0-PRE-18.jar:?]
 at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
 at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
 at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
 at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
 at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
 at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
 at java.lang.Class.newInstance(Class.java:645) ~[?:?]
 at org.bukkit.plugin.java.PluginClassLoader.(PluginClassLoader.java:85) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
 at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
 ... 7 more
