### ISSUE TITLE
插件载入时出错

### ISSUE THREAD

**Issue by lijinhong11** [FlickerProjects/TrChat#169]
核心: Purpur
[12:51:31] [Server thread/INFO]: [TrChat] 信息 | 加载完毕. TrChat v2.0.0-PRE-23 现已启用, 敬请使用.
[12:51:31] [Server thread/ERROR]: Error occurred while enabling TrChat v2.0.0-PRE-23 (Is it up to date?)
java.lang.ClassCastException: Cannot cast me.arasple.mc.trchat.library.adventure.text.TextComponentImpl to net.kyori.adventure.text.Component
	at java.lang.Class.cast(Class.java:3889) ~[?:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.set(JavaClassField.kt:52) ~[TrChat-2.0.0-PRE-23-shaded.jar:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.setLocalProperty(Reflex.kt:91) ~[TrChat-2.0.0-PRE-23-shaded.jar:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.setProperty(Reflex.kt:75) ~[TrChat-2.0.0-PRE-23-shaded.jar:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.setProperty$default(Reflex.kt:69) ~[TrChat-2.0.0-PRE-23-shaded.jar:?]
	at me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.setProperty(Reflex.kt:51) ~[TrChat-2.0.0-PRE-23-shaded.jar:?]
	at me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.setProperty$default(Reflex.kt:50) ~[TrChat-2.0.0-PRE-23-shaded.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke(BukkitCommand.kt:85) ~[TrChat-2.0.0-PRE-23-shaded.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke(BukkitCommand.kt:65) ~[TrChat-2.0.0-PRE-23-shaded.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitExecutor$submit$1.<init>(BukkitExecutor.kt:39) ~[TrChat-2.0.0-PRE-23-shaded.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitExecutor.submit(BukkitExecutor.kt:36) ~[TrChat-2.0.0-PRE-23-shaded.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitExecutor.start(BukkitExecutor.kt:28) ~[TrChat-2.0.0-PRE-23-shaded.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ExecutorKt.startExecutor(Executor.kt:11) ~[TrChat-2.0.0-PRE-23-shaded.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:68) ~[TrChat-2.0.0-PRE-23-shaded.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:594) ~[purpur-1.19.1.jar:git-Purpur-1749]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:508) ~[purpur-1.19.1.jar:git-Purpur-1749]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.1.jar:git-Purpur-1749]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.1.jar:git-Purpur-1749]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.1.jar:git-Purpur-1749]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[purpur-1.19.1.jar:git-Purpur-1749]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.1.jar:git-Purpur-1749]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:51:31] [Server thread/INFO]: [TrChat] Disabling TrChat v2.0.0-PRE-23

**Comment by ItsFlicker** [comment]
不要用shaded版本
