### ISSUE TITLE
1.19.2玩家进服被踢

### ISSUE THREAD

**Issue by YKDZ** [FlickerProjects/TrChat#170]
进服时
```
[15:54:49 WARN]: java.lang.NoSuchFieldException: net.minecraft.world.entity.Entity#playerConnection
[15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.JavaClassStructure.getField(JavaClassStructure.kt:20)
[15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:25)
[15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28)
[15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28)
[15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28)
[15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getLocalProperty(Reflex.kt:83)
[15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:58)
[15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:56)
[15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty$default(Reflex.kt:52)
[15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:41)
[15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:40)
[15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:29)
[15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.addPlayerChannel$lambda-0(ChannelExecutor.kt:46)
[15:54:49 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[15:54:49 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[15:54:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:54:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:54:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```
移动后被踢出
```
[15:55:24 INFO]: YK_DZ lost connection: Internal Exception: java.lang.NoSuchMethodError: 'boolean net.minecraft.world.entity.Entity.du()'
[15:55:24 WARN]: java.lang.NoSuchFieldException: net.minecraft.world.entity.Entity#playerConnection
[15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.JavaClassStructure.getField(JavaClassStructure.kt:20)
[15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:25)
[15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28)
[15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28)
[15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28)
[15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getLocalProperty(Reflex.kt:83)
[15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:58)
[15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:56)
[15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty$default(Reflex.kt:52)
[15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:41)
[15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:40)
[15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:29)
[15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.removePlayerChannel$lambda-1(ChannelExecutor.kt:56)
[15:55:24 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[15:55:24 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[15:55:24 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:55:24 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:55:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```
客户端
![Snipaste_2022-08-07_16-04-52](https://user-images.githubusercontent.com/69898831/183281487-4f889cda-0d74-4d2f-9b2e-f11d2eb53a28.png)

**Comment by ItsFlicker** [comment]
未支持1.19.2 等待更新



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月7日(周日) 下午4:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [TrPlugins/TrChat] 1.19.2玩家进服被踢 (Issue #170)




 
进服时
 [15:54:49 WARN]: java.lang.NoSuchFieldException: net.minecraft.world.entity.Entity#playerConnection [15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.JavaClassStructure.getField(JavaClassStructure.kt:20) [15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:25) [15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28) [15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28) [15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28) [15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getLocalProperty(Reflex.kt:83) [15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:58) [15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:56) [15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty$default(Reflex.kt:52) [15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:41) [15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:40) [15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:29) [15:54:49 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.addPlayerChannel$lambda-0(ChannelExecutor.kt:46) [15:54:49 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [15:54:49 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [15:54:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [15:54:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [15:54:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)  
移动后被踢出
 [15:55:24 INFO]: YK_DZ lost connection: Internal Exception: java.lang.NoSuchMethodError: 'boolean net.minecraft.world.entity.Entity.du()' [15:55:24 WARN]: java.lang.NoSuchFieldException: net.minecraft.world.entity.Entity#playerConnection [15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.JavaClassStructure.getField(JavaClassStructure.kt:20) [15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:25) [15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28) [15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28) [15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28) [15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getLocalProperty(Reflex.kt:83) [15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:58) [15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:56) [15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty$default(Reflex.kt:52) [15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:41) [15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:40) [15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:29) [15:55:24 WARN]:        at TrChat-2.0.0-PRE-23.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.removePlayerChannel$lambda-1(ChannelExecutor.kt:56) [15:55:24 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [15:55:24 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [15:55:24 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [15:55:24 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [15:55:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)  
客户端
