### ISSUE TITLE
1.19 purpur 空指针问题

### ISSUE THREAD

**Issue by ghost** [FlickerProjects/TrChat#171]
[20:54:13 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.0-PRE-23
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor135.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:34) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:34) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[TrChat-2.0.0-PRE-23.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:git-Purpur-1732]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:195) ~[purpur-1.19.jar:git-Purpur-1732]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:67) ~[purpur-1.19.jar:git-Purpur-1732]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2384) ~[?:?]        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2340) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$21(ServerGamePacketListenerImpl.java:2313) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java:2313) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$17(ServerGamePacketListenerImpl.java:2210) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemSword#getDescriptionId()
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassStructure.getMethod(JavaClassStructure.kt:25) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getMethod(ReflexClass.kt:41) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.invokeMethod(Reflex.kt:42) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.invokeMethod$default(Reflex.kt:38) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.invokeMethod(Reflex.kt:36) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.taboolib.module.nms.NMSGenericImpl.getName(NMSGenericImpl.java:125) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.NMSKt.getInternalName(NMS.kt:83) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.taboolib.module.nms.i18n.I18n11700.getName(I18n11700.kt:74) ~[TrChat-2.0.0-PRE-23.jar:?]        at me.arasple.mc.trchat.taboolib.module.nms.NMSKt.getI18nName(NMS.kt:87) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.module.display.function.ItemShow.getDisplayName(ItemShow.kt:97) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.module.display.function.ItemShow.access$getDisplayName(ItemShow.kt:29) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.module.display.function.ItemShow$createComponent$1.invoke(ItemShow.kt:84) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.module.display.function.ItemShow$createComponent$1.invoke(ItemShow.kt:74) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.taboolib.common5.MirrorKt.mirrorNow(Mirror.kt:17) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.module.display.function.ItemShow.createComponent(ItemShow.kt:74) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.module.display.format.MsgComponent.serialize(MsgComponent.kt:70) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:137) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute$default(Channel.kt:115) ~[TrChat-2.0.0-PRE-23.jar:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerChat.onChat(ListenerChat.kt:65) ~[TrChat-2.0.0-PRE-23.jar:?]
        ... 26 more

**Comment by ItsFlicker** [comment]
#167
