### ISSUE TITLE
在Velocity端无法正常载入

### ISSUE THREAD

**Issue by ProphetSAMA** [FlickerProjects/TrChat#172]
Velocity版本：3.1.2-SNAPSHOT-168
TrChat版本：2.0.0-PRE-24
shaded版本也试过，无法使用

[04:26:27 INFO]: 正在加载 TrChat... 3.1.2-SNAPSHOT (git-8a63df2a-b168)
[04:26:27 INFO]:
[04:26:27 INFO]: [TrChat] 已支持 Velocity 通讯.
[04:26:27 WARN] [trchat]: org.bukkit.event.player.PlayerQuitEvent not found, use @Ghost to turn off this warning
[04:26:27 INFO]: [TrChat] 聊天 | 成功载入 1 个聊天频道... [6 Ms]
[04:26:27 INFO]: [TrChat] 信息 | 加载完毕. TrChat v@plugin_version@ 现已启用, 敬请使用.
[04:26:27 ERROR]: me.arasple.mc.trchat.taboolib.common.inject.ClassVisitException: class me.arasple.mc.trchat.module.internal.service.Updater#grabInfo: VisitorGroup{priority=0, list=[AwakeFunction(lifeCycle=CONST), AwakeFunction(lifeCycle=INIT), AwakeFunction(lifeCycle=LOAD), AwakeFunction(lifeCycle=ENABLE), AwakeFunction(lifeCycle=ACTIVE), AwakeFunction(lifeCycle=DISABLE), me.arasple.mc.trchat.taboolib.common.platform.ScheduleLoader@1e829aef, me.arasple.mc.trchat.taboolib.common.platform.command.SimpleCommandRegister@c4c6998, me.arasple.mc.trchat.taboolib.common.platform.event.EventBus@2fd661f5, me.arasple.mc.trchat.taboolib.module.kether.KetherLoader@74f2cc33, me.arasple.mc.trchat.taboolib.platform.compat.PlaceholderExpansion$PlaceholderRegister@7ead65a0]} (ACTIVE)
[04:26:27 ERROR]:       at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:141)
[04:26:27 ERROR]:       at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:109)
[04:26:27 ERROR]:       at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:72)
[04:26:27 ERROR]:       at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:155)
[04:26:27 ERROR]:       at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:91)
[04:26:27 ERROR]:       at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$1.run(VelocityPlugin.java:87)
[04:26:27 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:228)
[04:26:27 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[04:26:27 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[04:26:27 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[04:26:27 ERROR]: Caused by: java.lang.ExceptionInInitializerError
[04:26:27 ERROR]:       at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
[04:26:27 ERROR]:       at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
[04:26:27 ERROR]:       at java.base/java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:377)
[04:26:27 ERROR]:       at java.base/java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:374)
[04:26:27 ERROR]:       at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
[04:26:27 ERROR]:       at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
[04:26:27 ERROR]:       at java.base/java.lang.ClassValue.get(ClassValue.java:116)
[04:26:27 ERROR]:       at java.base/java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:400)
[04:26:27 ERROR]:       at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:388)
[04:26:27 ERROR]:       at java.base/java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:422)
[04:26:27 ERROR]:       at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
[04:26:27 ERROR]:       at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.get(JavaClassField.kt:31)
[04:26:27 ERROR]:       at me.arasple.mc.trchat.taboolib.library.reflex.ClassField.get$default(ClassField.kt:11)
[04:26:27 ERROR]:       at me.arasple.mc.trchat.taboolib.common.io.Project1Kt$getInstance$2.invoke(Project1.kt:51)
[04:26:27 ERROR]:       at me.arasple.mc.trchat.taboolib.common.util.CommonKt$lazySupplier$1$obj$2.invoke(Common.kt:38)
[04:26:27 ERROR]:       at kotlin1510.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
[04:26:27 ERROR]:       at me.arasple.mc.trchat.taboolib.common.util.CommonKt$lazySupplier$1.getObj(Common.kt:37)
>
[04:26:27 ERROR]:       at me.arasple.mc.trchat.taboolib.common.util.CommonKt$lazySupplier$1.get(Common.kt:42)
[04:26:27 ERROR]:       at me.arasple.mc.trchat.taboolib.common.platform.ScheduleLoader.visit(ScheduleLoader.kt:20)
[04:26:27 ERROR]:       at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:139)
[04:26:27 ERROR]:       ... 9 more
[04:26:27 ERROR]: Caused by: me.arasple.mc.trchat.taboolib.common.util.Version$VersionFormatException: For input version: "@plugin_version@"
[04:26:27 ERROR]:       at me.arasple.mc.trchat.taboolib.common.util.Version.<init>(Version.java:31)
[04:26:27 ERROR]:       at me.arasple.mc.trchat.module.internal.service.Updater.<clinit>(Updater.kt:29)
[04:26:27 ERROR]:       ... 29 more

**Comment by ProphetSAMA** [comment]
换用了PRE-18版本后载入正常
