### ISSUE TITLE
频繁报错

### ISSUE THREAD

**Issue by StealthDeci** [FlickerProjects/TrChat#174]
[17:33:18 WARN]: java.lang.NoSuchFieldException: net.minecraft.world.entity.Entity#playerConnection
[17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.JavaClassStructure.getField(JavaClassStructure.kt:20)
[17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:26)
[17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:29)
[17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:29)
[17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:29)
[17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getLocalProperty(Reflex.kt:83)
[17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:58)
[17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:56)
[17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty$default(Reflex.kt:52)
[17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:32)
[17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.removePlayerChannel$lambda-1(ChannelExecutor.kt:59)
[17:33:18 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[17:33:18 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[17:33:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:33:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:33:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ItsFlicker** [comment]
即将支持1.19.2



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月11日(周四) 晚上6:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [TrPlugins/TrChat] 频繁报错 (Issue #174)




 
[17:33:18 WARN]: java.lang.NoSuchFieldException: net.minecraft.world.entity.Entity#playerConnection
 [17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.JavaClassStructure.getField(JavaClassStructure.kt:20)
 [17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:26)
 [17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:29)
 [17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:29)
 [17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:29)
 [17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getLocalProperty(Reflex.kt:83)
 [17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:58)
 [17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:56)
 [17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty$default(Reflex.kt:52)
 [17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:32)
 [17:33:18 WARN]:        at TrChat-2.0.0-PRE-24.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.removePlayerChannel$lambda-1(ChannelExecutor.kt:59)
 [17:33:18 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
 [17:33:18 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 [17:33:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 [17:33:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 [17:33:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
