### ISSUE TITLE
1.19.2加載錯誤（PRE-25）

### ISSUE THREAD

**Issue by ClayCoffee** [FlickerProjects/TrChat#175]
java.lang.ClassCastException: Cannot cast me.arasple.mc.trchat.library.adventure.text.TextComponentImpl to net.kyori.adventure.text.Component
        at java.lang.Class.cast(Class.java:3921) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:731) ~[?:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.set(JavaClassField.kt:52) ~[TrChat-2.0.0-PRE-25-shaded.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.setLocalProperty(Reflex.kt:91) ~[TrChat-2.0.0-PRE-25-shaded.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.setProperty(Reflex.kt:75) ~[TrChat-2.0.0-PRE-25-shaded.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.setProperty$default(Reflex.kt:69) ~[TrChat-2.0.0-PRE-25-shaded.jar:?]
        at me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.setProperty(Reflex.kt:51) ~[TrChat-2.0.0-PRE-25-shaded.jar:?]
        at me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.setProperty$default(Reflex.kt:50) ~[TrChat-2.0.0-PRE-25-shaded.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke(BukkitCommand.kt:87) ~[TrChat-2.0.0-PRE-25-shaded.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke(BukkitCommand.kt:67) ~[TrChat-2.0.0-PRE-25-shaded.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitExecutor$submit$1.<init>(BukkitExecutor.kt:39) ~[TrChat-2.0.0-PRE-25-shaded.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitExecutor.submit(BukkitExecutor.kt:36) ~[TrChat-2.0.0-PRE-25-shaded.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitExecutor.start(BukkitExecutor.kt:28) ~[TrChat-2.0.0-PRE-25-shaded.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ExecutorKt.startExecutor(Executor.kt:11) ~[TrChat-2.0.0-PRE-25-shaded.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:68) ~[TrChat-2.0.0-PRE-25-shaded.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) ~[PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) ~[PlugMan.jar:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:940) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:903) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:512) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1442) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ItsFlicker** [comment]
不要使用shaded版本
