### ISSUE TITLE
Velocity 启动报错

### ISSUE THREAD

**Issue by ghost** [FlickerProjects/TrChat#187]
Velocity build 177

`[20:53:05 ERROR]: Couldn't pass ProxyInitializeEvent to trchat
java.lang.NoSuchMethodError: 'void com.velocitypowered.api.command.CommandSource.sendMessage(me.arasple.mc.trchat.library.adventure.text.Component)'
        at me.arasple.mc.trchat.taboolib.platform.type.VelocityCommandSender.sendMessage(VelocityCommandSender.kt:34) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.lang.TypeText.send(TypeText.kt:38) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.lang.TypeList.send(TypeList.kt:22) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.lang.LangKt.sendLang(Lang.kt:13) ~[?:?]
        at me.arasple.mc.trchat.module.internal.TrChatVelocity.onLoad(TrChatVelocity.kt:29) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.e(VelocityPlugin.java:70) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.Lmbda$37.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by ItsFlicker** [comment]
除bukkit 1.16.5- 不要用shaded

**Comment by ghost** [comment]
> 除bukkit 1.16.5- 不要用shaded

好
