### ISSUE TITLE
展示物品出错

### ISSUE THREAD

**Issue by MC54145** [FlickerProjects/TrChat#188]
仅有插件 TrChat 2.0.0 Pre29 与 PlaceholderAPI 2.11.2
purpur-1.19.1-1751

[09:32:20 ERROR]: Could not pass event PacketReceiveEvent to TrChat v2.0.0-PRE-2
9
java.lang.NoSuchMethodException: net.minecraft.world.item.ItemNameTag#getDescrip
tionId()
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassStructure.getMe
thod(JavaClassStructure.kt:25) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getMethod(Re
flexClass.kt:42) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.invokeM
ethod(Reflex.kt:42) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.invokeM
ethod$default(Reflex.kt:38) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.invokeM
ethod(Reflex.kt:36) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.module.nms.NMSGenericImpl.getName(NMSGe
nericImpl.java:125) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.NMSKt.getInternalName(NMS.kt
:89) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.module.nms.i18n.I18n11700.getName(I18n1
1700.kt:74) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.module.nms.NMSKt.getI18nName(NMS.kt:93)
 ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.module.display.function.ItemShow.getDisplayName(
ItemShow.kt:97) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.module.display.function.ItemShow.access$getDispl
ayName(ItemShow.kt:29) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.module.display.function.ItemShow$createComponent
$1.invoke(ItemShow.kt:84) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.module.display.function.ItemShow$createComponent
$1.invoke(ItemShow.kt:74) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.common5.MirrorKt.mirrorNow(Mirror.kt:17
) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.module.display.function.ItemShow.createComponent
(ItemShow.kt:74) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.module.display.format.MsgComponent.serialize(Msg
Component.kt:62) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.k
t:147) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.api.nms.NMSImpl.sendChatPreview(NMSImpl.kt:88) ~
[?:?]
        at me.arasple.mc.trchat.module.display.ChatPreview.onReceive(ChatPreview
.kt:24) ~[TrChat-2.0.0-PRE-29.jar:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:7
32) ~[?:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(J
avaClassMethod.kt:31) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(E
ventBus.kt:133) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$d
efault(EventBus.kt:131) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$register
Bukkit$2.invoke(EventBus.kt:78) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$register
Bukkit$2.invoke(EventBus.kt:77) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$reg
isterBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$reg
isterBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListene
r$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListene
r$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.
execute(BukkitListener.kt:72) ~[TrChat-2.0.0-PRE-29.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:7
6) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:git-Purpur-1751]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:70) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:678) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.type.BukkitProxyEvent.call(Buk
kitProxyEvent.kt:39) ~[TrChat-2.0.0-PRE-29.jar:?]
        at me.arasple.mc.trchat.taboolib.module.nms.ChannelHandler.channelRead(C
hannelHandler.kt:24) ~[TrChat-2.0.0-PRE-29.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fina
l]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMes
sageDecoder.java:327) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:299) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fina
l]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMes
sageDecoder.java:327) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:299) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fina
l]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMes
sageDecoder.java:327) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:299) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fina
l]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToM
essageDecoder.java:103) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fina
l]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandle
r.java:286) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fina
l]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushCon
solidationHandler.java:152) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fina
l]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Defau
ltChannelPipeline.java:1410) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Fi
nal]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChanne
lPipeline.java:919) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra
ctNioByteChannel.java:166) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
a:722) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
ntLoop.java:658) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.ja
va:584) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-
transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThread
EventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java
:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ItsFlicker** [comment]
更新
