### ISSUE TITLE
[issue]: 关于TrChat-2.0.0 1.12.2无法加载的问题

### ISSUE THREAD

**Issue by jinghuashang** [FlickerProjects/TrChat#196]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

[16:25:15 INFO]: [TrChat] Enabling TrChat v2.0.0-PRE-35
[16:25:15 ERROR]: Error occurred while enabling TrChat v2.0.0-PRE-35 (Is it up to date?)
java.lang.NullPointerException: null
        at me.arasple.mc.trchat.module.internal.database.DatabaseSQLite.<init>(DatabaseSQLite.kt:24) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.Databases$database$2.invoke(Databases.kt:26) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.Databases$database$2.invoke(Databases.kt:24) ~[?:?]
        at kotlin1510.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.Databases.getDatabase(Databases.kt:24) ~[?:?]
        at me.arasple.mc.trchat.module.internal.TrChatBukkit.onEnable(TrChatBukkit.kt:82) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:65) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [Spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [Spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [Spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [Spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [Spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_333]

### configuration file

```YAML
无
```

### Server environment

Server version: 1.12.2
...
Plugin list: PlaceholderAPI-2.10.1
...

**Comment by ItsFlicker** [comment]
重新生成settings.yml
