### ISSUE TITLE
[Feature]提供对 CardBoard Mod 的支持

### ISSUE THREAD

**Issue by DreamUniverse843** [FlickerProjects/TrChat#197]
[CardBoard](https://github.com/CardboardPowered/cardboard) 是一个运行在 Fabric 上的 Mod，旨在为模组服提供插件接口。
请问能否提供对 CardBoard 的支持以便更好的进行跨服聊天？
~~因为 TrChat 功能太好用了懒得换了(~~

**Comment by ItsFlicker** [comment]
目前是会出现报错吗

**Comment by DreamUniverse843** [comment]
是的，以下是日志信息。
https://pastebin.ubuntu.com/p/v2Yk5wz4vv/

**Comment by ItsFlicker** [comment]
1. 尝试把datasource.yml中的DriverClassName 改为 'com.mysql.cj.jdbc.Driver'
2. 尝试使用mysql数据库

**Comment by DreamUniverse843** [comment]
您好，刚试了还是不行，报同样的错。

[22:50:48] [Server thread/INFO]: [TrChat] 过滤器 | 已载入本地敏感词库总计 3 个.
[22:50:48] [Server thread/FATAL]: Error occurred while enabling TrChat v2.0.0-RC-1 (Is it up to date?)
java.lang.RuntimeException: Failed to load driver class com.mysql.cj.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
        at com.zaxxer.hikari_4_0_3.HikariConfig.setDriverClassName(HikariConfig.java:491) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.database.Database.createHikariConfig(Database.kt:42) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.database.Database.createDataSource(Database.kt:22) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.database.Database.createDataSource$default(Database.kt:21) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.database.Host.createDataSource(Host.kt:22) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.database.Host.createDataSource$default(Host.kt:21) ~[?:?]
        at me.arasple.mc.trchat.module.internal.database.DatabaseSQL.<init>(DatabaseSQL.kt:33) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.Databases$database$2.invoke(Databases.kt:27) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.Databases$database$2.invoke(Databases.kt:24) ~[?:?]
        at kotlin1531.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.Databases.getDatabase(Databases.kt:24) ~[?:?]
        at me.arasple.mc.trchat.module.internal.TrChatBukkit.onEnable(TrChatBukkit.kt:79) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:65) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:257) ~[Cardboard-1.18.2.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:306) ~[Cardboard-1.18.2.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.17-dev.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:490) ~[Cardboard-1.18.2.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:421) ~[Cardboard-1.18.2.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zzb000$afterWorldLoad(MinecraftServer.java:1945) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:345) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:180) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by ItsFlicker** [comment]
不进行1， 只开启mysql呢

**Comment by DreamUniverse843** [comment]
好像可以了，谢谢！已经可以加载了
