### ISSUE TITLE
一条建议

### ISSUE THREAD

**Issue by 157946a** [FlickerProjects/TrChat#2]
能否在点击功能部分加个可选行为,比如我设置个type: clickrun,就是点击直接执行,不用自动输入到聊天里再按回车执行,然后原来的自动输入到聊天栏也用type来选择

**Comment by ItsFlicker** [comment]
这个功能已经支持了
suggest是点击输入到聊天框
command是点击直接执行

**Comment by 157946a** [comment]
好的,我看一下,有的话我自己关闭issues就好

**Comment by 157946a** [comment]
来了个报错,用command执行tell msg会出现以下报错

[13:26:13 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tell' in plugin TrChat v1.81
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.BLOCK_NOTE_BLOCK_PLING
        at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
        at org.bukkit.Sound.valueOf(Sound.java:11) ~[patched_1.12.2.jar:git-Paper-1618]
        at me.arasple.mc.trchat.taboolib.platform.type.BukkitPlayer.playSound(BukkitPlayer.kt:302) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.lang.TypeSound.send(TypeSound.kt:32) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.lang.TypeList.send(TypeList.kt:22) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.lang.LangKt.sendLang(Lang.kt:13) ~[?:?]
        at me.arasple.mc.trchat.module.channels.ChannelPrivate.execute(ChannelPrivate.kt:55) ~[?:?]
        at me.arasple.mc.trchat.module.cmds.CommandPrivateMessage$c$1$1$2$2.invoke(CommandPrivateMessage.kt:38) ~[?:?]
        at me.arasple.mc.trchat.module.cmds.CommandPrivateMessage$c$1$1$2$2.invoke(CommandPrivateMessage.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:178) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:86) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:82) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:98) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:21) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:68) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 15 more

**Comment by ItsFlicker** [comment]
应该是1.12.2没有BLOCK_NOTE_BLOCK_PLING这个声音
请手动把语言文件中的BLOCK_NOTE_BLOCK_PLING声音替换为其他声音或直接删除声音
该问题将在下个版本中默认修复

**Comment by 157946a** [comment]
还有一条
[15:03:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tell' in plugin TrChat v1.81
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.BLOCK_NOTE_BLOCK_PLING
        at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
        at org.bukkit.Sound.valueOf(Sound.java:11) ~[patched_1.12.2.jar:git-Paper-1618]
        at me.arasple.mc.trchat.taboolib.platform.type.BukkitPlayer.playSound(BukkitPlayer.kt:302) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.lang.TypeSound.send(TypeSound.kt:32) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.lang.TypeList.send(TypeList.kt:22) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.lang.LangKt.sendLang(Lang.kt:13) ~[?:?]
        at me.arasple.mc.trchat.module.channels.ChannelPrivate.execute(ChannelPrivate.kt:55) ~[?:?]
        at me.arasple.mc.trchat.module.cmds.CommandPrivateMessage$c$1$1$2$2.invoke(CommandPrivateMessage.kt:38) ~[?:?]
        at me.arasple.mc.trchat.module.cmds.CommandPrivateMessage$c$1$1$2$2.invoke(CommandPrivateMessage.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:178) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:86) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:82) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:98) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:21) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:68) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 15 more

**Comment by ItsFlicker** [comment]
把BLOCK_NOTE_BLOCK_PLING改为BLOCK_ANVIL_LAND
要删的话需要把- type: sound到pitch全部删掉

**Comment by 157946a** [comment]
改完和删完一样
[15:33:04 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tell' in plugin TrChat v1.81
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.BLOCK_NOTE_BLOCK_PLING
        at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
        at org.bukkit.Sound.valueOf(Sound.java:11) ~[patched_1.12.2.jar:git-Paper-1618]
        at me.arasple.mc.trchat.taboolib.platform.type.BukkitPlayer.playSound(BukkitPlayer.kt:302) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.lang.TypeSound.send(TypeSound.kt:32) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.lang.TypeList.send(TypeList.kt:22) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.lang.LangKt.sendLang(Lang.kt:13) ~[?:?]
        at me.arasple.mc.trchat.module.channels.ChannelPrivate.execute(ChannelPrivate.kt:55) ~[?:?]
        at me.arasple.mc.trchat.module.cmds.CommandPrivateMessage$c$1$1$2$2.invoke(CommandPrivateMessage.kt:38) ~[?:?]
        at me.arasple.mc.trchat.module.cmds.CommandPrivateMessage$c$1$1$2$2.invoke(CommandPrivateMessage.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:178) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:86) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:82) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:98) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:21) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:68) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 15 more

**Comment by ItsFlicker** [comment]
把你语言文件发来我看看...

**Comment by 157946a** [comment]
https://cowtransfer.com/s/caa3a410ac1f45这个是未改的,并且重新生成了,https://cowtransfer.com/s/3582a7e0f6df4c这个是修改后的

**Comment by ItsFlicker** [comment]
尝试把lang文件夹删除然后用新版本重新生成

**Comment by 157946a** [comment]
试过了,这个就是删除重新生成的,整个文件

**Comment by ItsFlicker** [comment]
刚刚又发了个 在actions里

**Comment by 157946a** [comment]
好了

**Comment by 157946a** [comment]
优先级能优化下吗,和trmenu3一样,数字越大越靠后

**Comment by 157946a** [comment]
又来了,指令staff执行的报错
[17:57:52 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'staff' in plugin TrChat v1.81
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.BLOCK_NOTE_BLOCK_PLING
        at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
        at org.bukkit.Sound.valueOf(Sound.java:11) ~[patched_1.12.2.jar:git-Paper-1618]
        at me.arasple.mc.trchat.taboolib.platform.type.BukkitPlayer.playSound(BukkitPlayer.kt:302) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.lang.TypeSound.send(TypeSound.kt:32) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.lang.TypeList.send(TypeList.kt:22) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.lang.LangKt.sendLang(Lang.kt:13) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.util.BukkitLangKt.sendLang(BukkitLang.kt:14) ~[?:?]
        at me.arasple.mc.trchat.module.cmds.CommandStaffChat$c$1$2.invoke(CommandStaffChat.kt:34) ~[?:?]
        at me.arasple.mc.trchat.module.cmds.CommandStaffChat$c$1$2.invoke(CommandStaffChat.kt:32) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:178) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:55) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:21) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:68) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 15 more

好像都是执行的时候有声音就出事,目前是staff,msg,spy出事 shout,ignore,reply,没试过

**Comment by ItsFlicker** [comment]
检查下语言文件有没有BLOCK_NOTE_BLOCK_PLING
应该新版本释放的语言文件不会有这个问题的

**Comment by 157946a** [comment]
均有5个,但之前删了也有,之前是把所有有关声音的都删了,也有过报错,内容就是sound.后面没有而已,其他都一样

**Comment by ItsFlicker** [comment]
把那五个的- type: sound到pitch全部删掉试试

**Comment by ItsFlicker** [comment]
> 优先级能优化下吗,和trmenu3一样,数字越大越靠后

就是这样的啊...

**Comment by 157946a** [comment]
删了就没问题了
