### ISSUE TITLE
[问题]: Mohist1.16.5发消息后服务器崩溃

### ISSUE THREAD

**Issue by X-Yunner** [FlickerProjects/TrChat#200]
### 是否已尝试最新的版本

- [x] #201

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.登录服务器
2.发消息
3.消息不出现
4.服务器崩溃

### 配置文件

```YAML
配置文件未修改
```

### 日志

UUID of player X_Yunner is 321b616e-04b5-3ed5-a586-c539aaf06963
[20:35:09 INFO]: Client attempting to join with 2 mods : minecraft, forge
[20:35:11 INFO]: X_Yunner[/183.216.149.146:16208] logged in with entity id 120 at (-491,610.938, 68, -22,129,991.105)
[20:35:12 WARN]: java.lang.NoSuchFieldException: no such field: net.minecraft.entity.player.ServerPlayerEntity.playerConnection/net.minecraft.network.play.ServerPlayNetHandler/getField
[20:35:12 WARN]:        at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:978)
[20:35:12 WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
[20:35:12 WARN]:        at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3641)
[20:35:12 WARN]:        at java.base/java.lang.invoke.MethodHandles$Lookup.findGetter(MethodHandles.java:3019)
[20:35:12 WARN]:        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:14)
[20:35:12 WARN]:        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:10)
[20:35:12 WARN]:        at kotlin1531.UnsafeLazyImpl.getValue(Lazy.kt:81)
[20:35:12 WARN]:        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.getHandleGetter(JavaClassField.kt:10)
[20:35:12 WARN]:        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.get(JavaClassField.kt:34)
[20:35:12 WARN]:        at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getLocalProperty(Reflex.kt:83)
[20:35:12 WARN]:        at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:58)
[20:35:12 WARN]:        at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:56)
[20:35:12 WARN]:        at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.getProperty$default(Reflex.kt:52)
[20:35:12 WARN]:        at me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:39)
[20:35:12 WARN]:        at me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.addPlayerChannel$lambda-0(ChannelExecutor.kt:63)
[20:35:12 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[20:35:12 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[20:35:12 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:35:12 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:35:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[20:35:12 WARN]: Caused by: java.lang.NoSuchFieldError: playerConnection
[20:35:12 WARN]:        at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
[20:35:12 WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
[20:35:12 WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
[20:35:12 WARN]:        ... 18 more
[20:35:12 WARN]: [ProtocolLib] Loaded class net.kyori.adventure.text.Component from TrChat v2.0.0-RC-1 which is not a depend, softdepend or loadbefore of this plugin.

### 服务器环境

服务器版本:
This server is running Mohist version 1.16.5-1085 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)
插件列表:
LuckPerms, EClean, PlaceholderAPI, spark, NBTAPI, Vault, ProtocolLib, LiteSignIn, Essentials, TrChat, EssentialsChat, CMILib, CraftGUI, WkKit, XConomy, EssentialsSpawn, Residence, EssentialsProtect, GlobalMarket, AuthMe

**Comment by ItsFlicker** [comment]
推测为Mohist改变了字段名称
或许你应该向TabooLib反馈此问题

**Comment by ItsFlicker** [comment]
请发送服务端文件 便于调试

**Comment by Mgazul** [comment]
Mohist-1.16.5-1090 https://github.com/MohistMC/Mohist/commit/4349dbf0a0737110474c7ea4aae9e26f790c53db 已修复该问题，感谢使用！
