### ISSUE TITLE
[问题]: purpur1.19.2启动后聊天格式不变，重启有报错

### ISSUE THREAD

**Issue by DenNotFound** [FlickerProjects/TrChat#205]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.启动
2.没现象

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server', 'vault', 'multiverse']
  Prevent-Tab-Complete: false
  ChatEvent-Hooks: ['AmazingBot', 'ChatBubbles', 'PlayMoreSounds', 'QuestCreator']
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: AUTO
  # CHAT, SYSTEM
  Send-Message-Method: CHAT

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  subscribe: []
  host: localhost
  port: 6379
  auth: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### 日志

[13:46:30] [Server thread/INFO]: DenNotFound issued server command: /trchat reload
[13:46:30] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'trchat' in plugin TrChat v2.0.0-RC-3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2386) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2340) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: kotlin1531.io.NoSuchFileException: plugins\TrChat\settings.yml: The source file doesn't exist.
	at kotlin1531.io.FilesKt__UtilsKt.copyTo(Utils.kt:219) ~[TrChat-2.0.0-RC-3.jar:?]
	at kotlin1531.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.taboolib.module.configuration.ConfigFile.loadFromFile(ConfigFile.kt:45) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.taboolib.module.configuration.ConfigFile.reload(ConfigFile.kt:74) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.module.internal.command.CommandHandler$reload$1$1.invoke(CommandHandler.kt:40) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.module.internal.command.CommandHandler$reload$1$1.invoke(CommandHandler.kt:39) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:192) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:102) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:115) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:38) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:70) ~[TrChat-2.0.0-RC-3.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 23 more[13:46:30] [Server thread/INFO]: DenNotFound issued server command: /trchat reload
[13:46:30] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'trchat' in plugin TrChat v2.0.0-RC-3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2386) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2340) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1826]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: kotlin1531.io.NoSuchFileException: plugins\TrChat\settings.yml: The source file doesn't exist.
	at kotlin1531.io.FilesKt__UtilsKt.copyTo(Utils.kt:219) ~[TrChat-2.0.0-RC-3.jar:?]
	at kotlin1531.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.taboolib.module.configuration.ConfigFile.loadFromFile(ConfigFile.kt:45) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.taboolib.module.configuration.ConfigFile.reload(ConfigFile.kt:74) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.module.internal.command.CommandHandler$reload$1$1.invoke(CommandHandler.kt:40) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.module.internal.command.CommandHandler$reload$1$1.invoke(CommandHandler.kt:39) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:192) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:102) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:115) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:38) ~[TrChat-2.0.0-RC-3.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:70) ~[TrChat-2.0.0-RC-3.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 23 more

### 服务器环境

服务器版本:
...Current: git-Purpur-1826 (MC: 1.19.2)*
Previous: git-Paper-43 (MC: 1.19)
* You are 13 version(s) behind
Download the new version at: https://purpurmc.org/downloads
插件列表:
...
![image](https://user-images.githubusercontent.com/103357331/201508046-fa8fdb8d-c998-4378-95f4-e331850acebe.png)

**Comment by ItsFlicker** [comment]
重新生成settings.yml
