### ISSUE TITLE
[问题]: 无法使用

### ISSUE THREAD

**Issue by Arispex** [FlickerProjects/TrChat#209]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.丢到plugins
2.正常开服
3.进服
然后控制台就夸夸疯狂报错

### 配置文件

```YAML
默认配置，什么也没动
```

### 日志

[09:43:06 WARN]: Caused by: java.lang.AbstractMethodError: org.sqlite.Conn.isValid(I)Z
[09:43:06 WARN]:        at com.zaxxer.hikari_4_0_3.pool.PoolBase.checkValidationSupport(PoolBase.java:464)
[09:43:06 WARN]:        at com.zaxxer.hikari_4_0_3.pool.PoolBase.checkDriverSupport(PoolBase.java:447)
[09:43:06 WARN]:        at com.zaxxer.hikari_4_0_3.pool.PoolBase.setupConnection(PoolBase.java:416)
[09:43:06 WARN]:        at com.zaxxer.hikari_4_0_3.pool.PoolBase.newConnection(PoolBase.java:369)
[09:43:06 WARN]:        at com.zaxxer.hikari_4_0_3.pool.PoolBase.newPoolEntry(PoolBase.java:206)
[09:43:06 WARN]:        at com.zaxxer.hikari_4_0_3.pool.HikariPool.createPoolEntry(HikariPool.java:476)
[09:43:06 WARN]:        at com.zaxxer.hikari_4_0_3.pool.HikariPool.checkFailFast(HikariPool.java:561)
[09:43:06 WARN]:        at com.zaxxer.hikari_4_0_3.pool.HikariPool.<init>(HikariPool.java:115)
[09:43:06 WARN]:        at com.zaxxer.hikari_4_0_3.HikariDataSource.<init>(HikariDataSource.java:81)
[09:43:06 WARN]:        at me.arasple.mc.trchat.taboolib.module.database.Database.createDataSource(Database.kt:22)
[09:43:06 WARN]:        at me.arasple.mc.trchat.taboolib.module.database.Database.createDataSource$default(Database.kt:21)
[09:43:06 WARN]:        at me.arasple.mc.trchat.taboolib.module.database.Host.createDataSource(Host.kt:22)
[09:43:06 WARN]:        at me.arasple.mc.trchat.taboolib.module.database.Host.createDataSource$default(Host.kt:21)
[09:43:06 WARN]:        at me.arasple.mc.trchat.module.internal.database.DatabaseSQLite.<init>(DatabaseSQLite.kt:37)
[09:43:06 WARN]:        at me.arasple.mc.trchat.module.internal.data.Databases$database$2.invoke(Databases.kt:24)
[09:43:06 WARN]:        at me.arasple.mc.trchat.module.internal.data.Databases$database$2.invoke(Databases.kt:22)
[09:43:06 WARN]:        at kotlin1531.UnsafeLazyImpl.getValue(Lazy.kt:81)
[09:43:06 WARN]:        at me.arasple.mc.trchat.module.internal.data.Databases.getDatabase(Databases.kt:22)
[09:43:06 WARN]:        at me.arasple.mc.trchat.module.internal.data.Databases.save(Databases.kt:37)
[09:43:06 WARN]:        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
[09:43:06 WARN]:        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[09:43:06 WARN]:        at me.arasple.mc.trchat.taboolib.common.platform.AwakeFunction.visit(AwakeFunction.kt:13)
[09:43:06 WARN]:        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:134)
[09:43:06 WARN]:        ... 13 more

### 服务器环境

服务器版本:This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
插件列表:MultiWorld, WorldEdit, MVdWPlaceholderAPI, PlaceholderAPI, MiaoBoard, NoWeather, ViaVersion, CustomJoinItems, Vault, TimeLock, PlayerPoints, ViaBackwards, ProtocolLib, WorldGuard, Multiverse-Core, Citizens, KitBattle, ChestCommands, Essentials, EssentialsChat, ColorMOTD, CommandNPC, HolographicDisplays, EssentialsSpaw

**Comment by ItsFlicker** [comment]
https://trchat.plugindoc.cn/wen-ti/known/1.8-database

**Comment by Arispex** [comment]
解决了，感谢，是我没认真看wiki，不好意思。
