### ISSUE TITLE
[issue]: 使用两次/trchat:global 会疯狂刷屏

### ISSUE THREAD

**Issue by xiantiao233** [FlickerProjects/TrChat#221]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

使用两次/trchat:global 客户端会疯狂刷屏，吓死人了

### configuration file

```YAML
默认
```

### logs

 by: java.lang.StackOverflowError
        at com.google.gson.internal.bind.JsonTreeWriter.value(JsonTreeWriter.java:161) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$27.write(TypeAdapters.java:705) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$27.write(TypeAdapters.java:721) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$27.write(TypeAdapters.java:655) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.Streams.write(Streams.java:72) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:82) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar:?]
        at net.minecraft.network.chat.Component$Serializer.serializeStyle(Component.java:380) ~[?:?]
        at net.minecraft.network.chat.Component$Serializer.serialize(Component.java:400) ~[?:?]
        at net.minecraft.network.chat.Component$Serializer.serialize(Component.java:410) ~[?:?]
        at net.minecraft.network.chat.Component$Serializer.serialize(Component.java:214) ~[?:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.toJson(Gson.java:714) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.toJson(Gson.java:669) ~[gson-2.8.9.jar:?]
        at com.google.gson.Gson.toJson(Gson.java:649) ~[gson-2.8.9.jar:?]
        at net.minecraft.network.chat.Component$Serializer.toJson(Component.java:502) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:12) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.level.ServerPlayer.sendSystemMessage(ServerPlayer.java:1887) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.sendSystemMessage(ServerPlayer.java:1882) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:328) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:344) ~[paper-1.19.2.jar:git-Paper-307]
        at me.arasple.mc.trchat.taboolib.platform.type.BukkitPlayer.sendMessage(BukkitPlayer.kt:370) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.taboolib.module.lang.TypeText.send(TypeText.kt:38) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.taboolib.module.lang.TypeList.send(TypeList.kt:22) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.taboolib.module.lang.LangKt.sendLang(Lang.kt:13) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.util.BukkitLangKt.sendLang(BukkitLang.kt:14) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.quit(Channel.kt:268) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.join(Channel.kt:243) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.join$default(Channel.kt:239) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.quit(Channel.kt:270) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.join(Channel.kt:243) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.join$default(Channel.kt:239) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.quit(Channel.kt:270) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.join(Channel.kt:243) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.join$default(Channel.kt:239) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.quit(Channel.kt:270) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.join(Channel.kt:243) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.join$default(Channel.kt:239) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.quit(Channel.kt:270) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.join(Channel.kt:243) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.join$default(Channel.kt:239) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.quit(Channel.kt:270) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.join(Channel.kt:243) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.join$default(Channel.kt:239) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.quit(Channel.kt:270) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.join(Channel.kt:243) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.join$default(Channel.kt:239) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.quit(Channel.kt:270) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.join(Channel.kt:243) ~[TrChat-2.0.0-RC-6.jar:?]
        at me.arasple.mc.trchat.module.

### Server environment

Checking version, please wait...
[18:52:26 INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-411 (MC: 1.17.1)

Citizens, CMI, CMILib, ConsoleSpamFix*, DeluxeHub, GadgetsMenu, Images, JukeBox, LiteSignIn, LuckPerms, Mcborder*, MiaoScript, Multiverse-Core, NoteBlockAPI, PlaceholderAPI, PlayerPoints, PlugManX (PlugMan), ProtocolLib, Residence, SkBee, Skript, skript-reflect, TigerReports, TrChat, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGen, WorldEdit, WorldGuard, XConomy

**Comment by ItsFlicker** [comment]
检查你的默认频道设置
