### ISSUE TITLE
[Done] Support to Folia

### ISSUE THREAD

**Issue by HYDeath** [FlickerProjects/TrChat#259]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

Folia 是刚出的新生态核心，因此我暂不期望这个 Trchat 能全面兼容。但我希望能有个基本的兼容和部分功能可用（能与BC互通，其他子服也能收到来自folia端玩家的消息）
Github：https://github.com/PaperMC/Folia
帮助文档：https://docs.papermc.io/folia

### 配置文件

```YAML
无
```

### 服务器环境

服务器核心:
Folia-1.20.1-build1.jar
Java：zulu 18 64位

**Comment by ItsFlicker** [comment]
需要等待 https://github.com/TabooLib/taboolib 先兼容

**Comment by YuanYuanOwO** [comment]
https://github.com/TabooLib/taboolib/issues/317

大概无解

**Comment by xiaoluofa** [comment]
[taboolib]视乎已经支持folia？

**Comment by ItsFlicker** [comment]
是的，但是还要测试一下



---Original---
From: ***@***.***&gt;
Date: Thu, Feb 29, 2024 16:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TrPlugins/TrChat] [Planned] Support to Folia (Issue #259)




 
[taboolib]视乎已经支持folia？

**Comment by xiaoluofa** [comment]
> 是的，但是还要测试一下
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Feb 29, 2024 16:52 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [TrPlugins/TrChat] [Planned] Support to Folia (Issue #259) [taboolib]视乎已经支持folia？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

快点端上来吧

**Comment by ItsFlicker** [comment]
> > 是的，但是还要测试一下
> > […](#)
> > ---Original--- From: _**@**_._**> Date: Thu, Feb 29, 2024 16:52 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [TrPlugins/TrChat] [Planned] Support to Folia (Issue #259) [taboolib]视乎已经支持folia？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 快点端上来吧

有folia的PlaceholderAPI吗

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/8121253118

**Comment by HYDeath** [comment]
真是难得的机会，半年了终于能看到trchat支持folia了

**Comment by xiaoluofa** [comment]
folia无法连接redis，进行跨服聊天

**Comment by xiaoluofa** [comment]
[15:32:37] [pool-38-thread-1/WARN]: java.lang.NoSuchMethodError: 'com.electronwill.nightconfig.core.Config me.arasple.mc.trchat.taboolib.module.configuration.ConfigSection.getRoot()'
[15:32:37] [pool-38-thread-1/WARN]: 	at TrChat-2.0.14.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:64)
[15:32:37] [pool-38-thread-1/WARN]: 	at TrChat-2.0.14.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:44)
[15:32:37] [pool-38-thread-1/WARN]: 	at TrChat-2.0.14.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$createPubSub$1.onMessage(SingleRedisConnection.kt:184)
[15:32:37] [pool-38-thread-1/WARN]: 	at TrChat-2.0.14.jar//redis.clients.jedis_4_2_3.JedisPubSub.process(JedisPubSub.java:156)
[15:32:37] [pool-38-thread-1/WARN]: 	at TrChat-2.0.14.jar//redis.clients.jedis_4_2_3.JedisPubSub.proceed(JedisPubSub.java:125)
[15:32:37] [pool-38-thread-1/WARN]: 	at TrChat-2.0.14.jar//redis.clients.jedis_4_2_3.Jedis.subscribe(Jedis.java:7891)
[15:32:37] [pool-38-thread-1/WARN]: 	at TrChat-2.0.14.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:160)
[15:32:37] [pool-38-thread-1/WARN]: 	at TrChat-2.0.14.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:156)
[15:32:37] [pool-38-thread-1/WARN]: 	at TrChat-2.0.14.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.exec(SingleRedisConnection.kt:40)
[15:32:37] [pool-38-thread-1/WARN]: 	at TrChat-2.0.14.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.subscribe$lambda$2(SingleRedisConnection.kt:156)
[15:32:37] [pool-38-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[15:32:37] [pool-38-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[15:32:37] [pool-38-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:32:37] [pool-38-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:32:37] [pool-38-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by xiaoluofa** [comment]
此外后台还有各种报错，以及placeholderapi在 hover中无法显示

**Comment by xiaoluofa** [comment]
请修复1.20.4

**Comment by ItsFlicker** [comment]
已修复

**Comment by xiaoluofa** [comment]
> 已修复

物品展示无法跨服吗？还是说folia的问题没法跨到paper

**Comment by xiaoluofa** [comment]
默认选择global还是读取的normal，并且可以跨服，非常奇怪

**Comment by ItsFlicker** [comment]
已解决

**Comment by mc2514** [comment]
> 已解决

能更新一下1.21.8版本吗
