### ISSUE TITLE
[问题] Arclight无法读取聊天发包

### ISSUE THREAD

**Issue by BearAnak** [FlickerProjects/TrChat#262]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

进入服务器就会提示

### 配置文件

```YAML
[02:21:08 INFO] [Console]: [TrChat] Error occurred while caching chat packet!Maybe your server doesn't support it
[02:21:08 INFO] [Console]: java.lang.NoSuchMethodException: net.minecraft.network.protocol.game.ClientboundSystemChatPacket#content()
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassStructure.getMethod(JavaClassStructure.kt:25)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getMethod(ReflexClass.kt:42)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.invokeMethod(Reflex.kt:42)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.invokeMethod$default(Reflex.kt:38)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.module.adventure.AdventureKt.getComponent(Adventure.kt:40)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.module.display.ChatSession.addMessage(ChatSession.kt:54)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.module.internal.listener.ListenerPackets.recall(ListenerPackets.kt:38)
[02:21:08 INFO] [Console]:      at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72)
[02:21:08 INFO] [Console]:      at TRANSFORMER/arclight@1.19.2-1.0.2-4a870b30/org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:21:08 INFO] [Console]:      at TRANSFORMER/arclight@1.19.2-1.0.2-4a870b30/org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[02:21:08 INFO] [Console]:      at TRANSFORMER/arclight@1.19.2-1.0.2-4a870b30/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:40)
[02:21:08 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:21)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.codec@4.1.77.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[02:21:08 INFO] [Console]:      at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[02:21:08 INFO] [Console]:      at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[02:21:08 INFO] [Console]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.m_243087_(ConnectionMixin.java:209)
[02:21:08 INFO] [Console]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.lambda$sendPacket$8(ConnectionMixin.java:198)
[02:21:08 INFO] [Console]:      at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[02:21:08 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[02:21:08 INFO] [Console]:      at java.base/java.lang.Thread.run(Thread.java:833)
```

### 服务器环境

服务器版本:
1.19.2  Arclight
插件列表:
...

**Comment by ItsFlicker** [comment]
此报错为无法读取聊天发包，导致无法使用部分功能（如撤回消息），其他功能可正常使用
暂未找到解决方法

**Comment by ItsFlicker** [comment]
已修复
https://github.com/TrPlugins/TrChat/actions/runs/7357248308
