### ISSUE TITLE
[issue]: 进入服务器就会报错

### ISSUE THREAD

**Issue by BearAnak** [FlickerProjects/TrChat#267]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

[19:15:04 INFO] [Console]: [TrChat] Error occurred while caching chat packet!Maybe your server doesn't support it
[19:15:04 INFO] [Console]: java.lang.NoSuchMethodException: net.minecraft.network.protocol.game.ClientboundSystemChatPacket#content()
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassStructure.getMethod(JavaClassStructure.kt:25)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getMethod(ReflexClass.kt:42)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.invokeMethod(Reflex.kt:42)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.invokeMethod$default(Reflex.kt:38)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.module.adventure.AdventureKt.getComponent(Adventure.kt:40)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.module.display.ChatSession.addMessage(ChatSession.kt:54)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.module.internal.listener.ListenerPackets.recall(ListenerPackets.kt:38)
[19:15:04 INFO] [Console]:      at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72)
[19:15:04 INFO] [Console]:      at TRANSFORMER/arclight@1.19.2-1.0.2-4a870b30/org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:15:04 INFO] [Console]:      at TRANSFORMER/arclight@1.19.2-1.0.2-4a870b30/org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[19:15:04 INFO] [Console]:      at TRANSFORMER/arclight@1.19.2-1.0.2-4a870b30/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:40)
[19:15:04 INFO] [Console]:      at me.arasple.mc.trchat.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:21)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.codec@4.1.77.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[19:15:04 INFO] [Console]:      at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[19:15:04 INFO] [Console]:      at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[19:15:04 INFO] [Console]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.m_243087_(ConnectionMixin.java:209)
[19:15:04 INFO] [Console]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.lambda$sendPacket$8(ConnectionMixin.java:198)
[19:15:04 INFO] [Console]:      at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[19:15:04 INFO] [Console]:      at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:15:04 INFO] [Console]:      at java.base/java.lang.Thread.run(Thread.java:833)

### configuration file

```YAML
默认的配置
```

### Server environment

Server version:
1.19.2
Plugin list:
...

**Comment by ItsFlicker** [comment]
> Error occurred while caching chat packet!Maybe your server doesn't support it

#262
