### ISSUE TITLE
[问题] 使用 Velocity 从 1.20.1 发布跨服消息到 1.8.8 接收时出现问题

### ISSUE THREAD

**Issue by MelodyYuuka** [FlickerProjects/TrChat#275]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1. 在 Velocity 与 Paper 1.8.8、purpur 1.20.1 安装 Trchat 2.0.2
2. 使用默认 Global.yml 在 1.20.1 喊话，1.8.8 端报错且收不到消息
3. 使用默认 Global.yml 在 1.8.8 喊话，1.20.1 端正常收到消息

### 配置文件

```YAML
Options:
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  # AUTO, NONE, BUNGEE, VELOCITY
  Proxy: VELOCITY

Database:
  Method: SQLite
  SQLite:
    file: '{plugin_folder}/data/data.db'
    table: trchat_user_data
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  channel: 'trchat-message'
  subscribe: []
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Channel:
  Default: 'Normal'
```

### 日志
```log
[23:00:08] [Server thread/WARN]: Could not pass incoming plugin message to TrChat v2.0.2
java.lang.NullPointerException: null
	at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:65) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:17) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson.fromJson(Gson.java:868) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson$1.deserialize(Gson.java:126) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:62) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:17) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson.fromJson(Gson.java:868) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson$1.deserialize(Gson.java:126) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:50) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:17) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson.fromJson(Gson.java:868) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson$1.deserialize(Gson.java:126) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:62) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:17) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson.fromJson(Gson.java:868) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson$1.deserialize(Gson.java:126) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:50) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:17) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson.fromJson(Gson.java:868) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson$1.deserialize(Gson.java:126) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:62) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:17) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:34) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at me.arasple.mc.trchat.taboolib.module.chat.Components.parseRaw(Components.kt:47) ~[?:?]
	at me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor.execute(BukkitProxyProcessor.kt:77) ~[?:?]
	at me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor$VelocitySide.onPluginMessageReceived(BukkitProxyProcessor.kt:208) ~[?:?]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:429) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:2154) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:55) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_372]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_372]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372]
```
### 服务器环境

服务器版本:
Velocity 3.2.0-SNAPSHOT (git-37fedf50-b260)
git-PaperSpigot-445 (MC: 1.8.8)
purpur-1.20.1-2017 (MC: 1.20.1)

插件列表:
1.8.8 Plugins (16): VoidGen, FastAsyncWorldEdit, PlaceholderAPI, CMILib, PlugMan, ViaVersion, PlugManX, LuckPerms, SkinsRestorer, WorldEdit, TrChat, Vault, CMI, SuperLobby, Citizens, TAB-Bridge
1.20.1 Paper Plugins: (1):
  - MarriageMaster
  Bukkit Plugins: (15):
  - Citizens, CitizensGUI, CMI, CMILib, InteractionVisualizer, LuckPerms, PlaceholderAPI, PlugManX, Residence, SkinsRestorer
  TAB-Bridge, TrChat, Vault, ViaVersion, WorldEdit

**Comment by ItsFlicker** [comment]
https://trchat.trixey.cc/guide/known-issues#%E8%81%8A%E5%A4%A9%E6%97%A0%E6%B3%95%E5%90%91%E4%B8%8B%E7%89%88%E6%9C%AC%E8%B7%A8%E6%9C%8D

**Comment by MelodyYuuka** [comment]
感谢，我看的不是这一版的wiki，抱歉
