### ISSUE TITLE
[issue] 1.20.1客户端每发一条消息后台就会报错

### ISSUE THREAD

**Issue by bananaQwQ666** [FlickerProjects/TrChat#277]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

1.启动服务器
2.在客户端聊天框中随便发一条消息
3.回到服务端发现每发一条消息便会出现一次报错

### configuration file

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32766

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### logs

后台每次给的报错是
`[22:00:23 WARN]: java.lang.NoSuchFieldException: ping
[22:00:23 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[22:00:23 WARN]:        at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:49)
[22:00:23 WARN]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:270)
[22:00:23 WARN]:        at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[22:00:23 WARN]:        at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[22:00:23 WARN]:        at TrChat-2.0.2.jar//me.arasple.mc.trchat.util.BukkitUtilKt.setPlaceholders(BukkitUtil.kt:57)
[22:00:23 WARN]:        at TrChat-2.0.2.jar//me.arasple.mc.trchat.module.display.format.obj.Style$Companion.applyTo(Style.kt:93)
[22:00:23 WARN]:        at TrChat-2.0.2.jar//me.arasple.mc.trchat.module.display.format.JsonComponent.toTextComponent(JsonComponent.kt:23)
[22:00:23 WARN]:        at TrChat-2.0.2.jar//me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:135)
[22:00:23 WARN]:        at TrChat-2.0.2.jar//me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:47)
[22:00:23 WARN]:        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
[22:00:23 WARN]:        at TrChat-2.0.2.jar//me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[22:00:23 WARN]:        at TrChat-2.0.2.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132)
[22:00:23 WARN]:        at TrChat-2.0.2.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130)
[22:00:23 WARN]:        at TrChat-2.0.2.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77)
[22:00:23 WARN]:        at TrChat-2.0.2.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76)
[22:00:23 WARN]:        at TrChat-2.0.2.jar//me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39)
[22:00:23 WARN]:        at TrChat-2.0.2.jar//me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39)
[22:00:23 WARN]:        at TrChat-2.0.2.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35)
[22:00:23 WARN]:        at TrChat-2.0.2.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35)
[22:00:23 WARN]:        at TrChat-2.0.2.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72)
[22:00:23 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[22:00:23 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:00:23 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[22:00:23 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[22:00:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[22:00:23 WARN]:        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414)
[22:00:23 WARN]:        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100)
[22:00:23 WARN]:        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2404)
[22:00:23 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2560)
[22:00:23 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChat$17(PlayerConnection.java:2233)
[22:00:23 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[22:00:23 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[22:00:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:00:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:00:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

### Server environment

Server version:
` --------------------------------------------------
CMI 插件版本: 9.6.0.6 SqLite-> 9.6.1.3
 CMILib: 1.4.0.1
服务器版本: Paper(84) 1.20.1-R0.1-SNAPSHOT
CMI 经济: 启用 经济: 1.7.3-b131(CMIEInjector) CMI 聊天: 禁用
模块 -> 54 已启用 4 已禁用: tablist, ranks, votifier, kits
 --------------------------------------------------`
Plugin list:
` Bukkit Plugins: - AdvancedFish, AllMusic, AureliumSkills, AuthMe, BedrockTechnology, BNes, Boom, BossShopPro, BountifulAPI, CCTV，ChestTerminal, Citizens, CitizensCMD, ClearEntity, CMI, *CMIEInjector, CMILib, ConsoleSpamFix, CoreProtect,DyedBackpacks，EasyGuiShop, EcoPower, EnderDragon, FastLeafDecay, FluffyMachines, Galactifun, GeekCosmetics, GlobalMarket, GSit, Gui，GuizhanCraft, HeadBlocks, *HiaXnLevel, HiveChecker, *HotkeyCommand, ImageOnMap,InfiniteScoreboard, InfinityExpansion, InteractionVisualizer, Ip2region，ItemsAdder, LegendaryGuild, LiteSignIn, LockettePro, LoneLibs, LuckPerms, MinePay, MiraiMC, MobCapturer, Multiverse-Core，NBTAPI, Orebfuscator, PlaceholderAPI, PlayerHeads, PlayerPoints, PlayerTitle, PlugManX, PrivateStorage, ProtocolLib, QuickShop，ReadyCore, ReadyPedia, Residence, Shopkeepers, SimpleJoin, SimpleUtils, SkullAPI, Skulls, Slimefun, SlimefunLuckyBlocks， SlimefunOreChunks, SlimefunWarfare, SlimeTinker, SlotMachine, SoaromaSAC, SoulJars, SoulShards, TAB, TileDataSaver, TrChat
UltimateTimber, Vault, VipSystem, WkKit, WorldEdit`

**Comment by ItsFlicker** [comment]
https://trchat.trixey.cc/guide/known-issues#placeholderapi-%E6%8A%A5%E9%94%99%E9%97%AE%E9%A2%98

**Comment by bananaQwQ666** [comment]
解决了

**Comment by bananaQwQ666** [comment]
解决了
