### ISSUE TITLE
[问题] 1.12.2 Spigot 服务端无法运行Trchat

### ISSUE THREAD

**Issue by BiliRumble** [FlickerProjects/TrChat#330]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1.无法发送聊天信息
2.无法使用命令切换频道

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Kether-Allow-Tolerance-Parser: true

Channel:
  Default: 'Normal'

Database:
  Method: SQLITE
  SQL:
    host: **
    port: 5433
    user: **
    password: **
    database: **
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### 日志
```
[01:36:44 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.8
java.lang.IllegalStateException: unavailable
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.getDataContainer(DatabaseHandler.kt:57) ~[?:?]
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.getDataContainer(DatabaseHandlerForBukkit.kt:7) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData.isVanishing(PlayerData.kt:36) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData.<init>(PlayerData.kt:20) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:115) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:114) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData$lambda$0(PlayerData.kt:114) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_342]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData(PlayerData.kt:114) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession.<init>(ChatSession.kt:109) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion$getSession$1.invoke(ChatSession.kt:99) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion$getSession$1.invoke(ChatSession.kt:99) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion.getSession$lambda$0(ChatSession.kt:99) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_342]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion.getSession(ChatSession.kt:99) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:94) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_342]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:73) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1323) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1261) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_342]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_342]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_342]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_342]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
```
### 服务器环境

服务器版本:
```
This server is running CraftBukkit version git-Spigot-79a30d7-f4830a1 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```
插件列表:
```
Plugins (15): TpLogin, Notbuild, JoinCommands, PlaceholderAPI, PlugMan, AuthMe, ViaVersion, LiteBans, floodgate, ViaBackwards, SkinsRestorer, Citizens, TrChat, CommandNPC, TrMenu
```

**Comment by ItsFlicker** [comment]
需要提供完整日志文件

**Comment by BiliRumble** [comment]
经过检查，是使用Java8导致的，问题已解决。
