### ISSUE TITLE
[issue] 玩家发消息时报错

### ISSUE THREAD

**Issue by DuckLee95** [FlickerProjects/TrChat#336]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

玩家发消息时会有下列错误
peper1.20.2 trchat 和 papi 均为最新

### configuration file

```YAML
均为默认配置
```

### logs

[00:54:11 INFO]: [TrChat] Error occurred when parsing placeholder!This is not a bug of TrChat
[00:54:11 INFO]: java.lang.IllegalArgumentException: Attempt to get boolean field "net.minecraft.server.level.EntityPlayer.f" with illegal data type conversion to int
[00:54:11 INFO]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.newGetIllegalArgumentException(UnsafeFieldAccessorImpl.java:69)
[00:54:11 INFO]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.newGetIntIllegalArgumentException(UnsafeFieldAccessorImpl.java:132)
[00:54:11 INFO]:        at java.base/jdk.internal.reflect.UnsafeBooleanFieldAccessorImpl.getInt(UnsafeBooleanFieldAccessorImpl.java:57)
[00:54:11 INFO]:        at java.base/java.lang.reflect.Field.getInt(Field.java:601)
[00:54:11 INFO]:        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:66)
[00:54:11 INFO]:        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:50)
[00:54:11 INFO]:        at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:131)
[00:54:11 INFO]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:481)
[00:54:11 INFO]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:403)
[00:54:11 INFO]:        at PlaceholderAPI-2.11.5.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[00:54:11 INFO]:        at PlaceholderAPI-2.11.5.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[00:54:11 INFO]:        at TrChat-2.0.9.jar//me.arasple.mc.trchat.util.BukkitUtilKt.setPlaceholders(BukkitUtil.kt:42)
[00:54:11 INFO]:        at TrChat-2.0.9.jar//me.arasple.mc.trchat.module.display.format.obj.Style$Companion.applyTo(Style.kt:93)
[00:54:11 INFO]:        at TrChat-2.0.9.jar//me.arasple.mc.trchat.module.display.format.JsonComponent.toTextComponent(JsonComponent.kt:23)
[00:54:11 INFO]:        at TrChat-2.0.9.jar//me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:147)
[00:54:11 INFO]:        at TrChat-2.0.9.jar//me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:58)
[00:54:11 INFO]:        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
[00:54:11 INFO]:        at TrChat-2.0.9.jar//me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[00:54:11 INFO]:        at TrChat-2.0.9.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132)
[00:54:11 INFO]:        at TrChat-2.0.9.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130)
[00:54:11 INFO]:        at TrChat-2.0.9.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77)
[00:54:11 INFO]:        at TrChat-2.0.9.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76)
[00:54:11 INFO]:        at TrChat-2.0.9.jar//me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39)
[00:54:11 INFO]:        at TrChat-2.0.9.jar//me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39)
[00:54:11 INFO]:        at TrChat-2.0.9.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36)
[00:54:11 INFO]:        at TrChat-2.0.9.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36)
[00:54:11 INFO]:        at TrChat-2.0.9.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:73)
[00:54:11 INFO]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[00:54:11 INFO]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:54:11 INFO]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[00:54:11 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[00:54:11 INFO]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[00:54:11 INFO]:        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:416)
[00:54:11 INFO]:        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:102)
[00:54:11 INFO]:        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2312)
[00:54:11 INFO]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2441)
[00:54:11 INFO]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChat$16(PlayerConnection.java:2141)
[00:54:11 INFO]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[00:54:11 INFO]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[00:54:11 INFO]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:54:11 INFO]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:54:11 INFO]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:54:12 INFO]: ➥ NewPlayerVillage yyyork_: test

### Server environment

Server version:
peper1.20.2
Plugin list:
trchat 和 papi

**Comment by ItsFlicker** [comment]
papi的拓展player不是最新

**Comment by DuckLee95** [comment]
原来如此，多谢！已解决！
