### ISSUE TITLE
paper无法使用TrChat

### ISSUE THREAD

**Issue by lanzhihry** [FlickerProjects/TrChat#34]
paper-1.17.1-372版本加载TrChat时报错,如下
`[13:55:21] [Server thread/INFO]: [TrChat] INFO | 加载完毕. TrChat v1.90-R2 现已启用, 敬请使用.
[13:55:21] [Server thread/ERROR]: Error occurred while enabling TrChat v1.90-R2 (Is it up to date?)
java.lang.ClassCastException: Cannot cast java.lang.String to net.kyori.adventure.text.Component
        at java.lang.Class.cast(Class.java:3818) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.reflect.Ref.put(Ref.kt:37) ~[TrChat-1.90-R2.jar:?]
        at me.arasple.mc.trchat.taboolib.common.reflect.Reflex.set(Reflex.kt:69) ~[TrChat-1.90-R2.jar:?]
        at me.arasple.mc.trchat.taboolib.common.reflect.Reflex.write(Reflex.kt:36) ~[TrChat-1.90-R2.jar:?]
        at me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.setProperty(Reflex.kt:142) ~[TrChat-1.90-R2.jar:?]
        at me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.setProperty$default(Reflex.kt:138) ~[TrChat-1.90-R2.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke(BukkitCommand.kt:78) ~[TrChat-1.90-R2.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke(BukkitCommand.kt:63) ~[TrChat-1.90-R2.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitExecutor$submit$1.<init>(BukkitExecutor.kt:39) ~[TrChat-1.90-R2.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitExecutor.submit(BukkitExecutor.kt:36) ~[TrChat-1.90-R2.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitExecutor.start(BukkitExecutor.kt:28) ~[TrChat-1.90-R2.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ExecutorKt.startExecutor(Executor.kt:11) ~[TrChat-1.90-R2.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:64) ~[TrChat-1.90-R2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-372]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-372]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-372]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-372]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-372]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:730) ~[patched_1.17.1.jar:git-Paper-372]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-372]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[patched_1.17.1.jar:git-Paper-372]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-372]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[13:55:21] [Server thread/INFO]: [TrChat] Disabling TrChat v1.90-R2
[13:55:21] [Server thread/WARN]: [TrChat] Loaded class me.arasple.mc.trmenu.taboolib.common.OpenAPI from TrMenu v3.0-RC-2 which is not a depend, softdepend or loadbefore of this plugin.
[13:55:21] [Server thread/WARN]: [TrChat] Loaded class me.arasple.mc.trhologram.taboolib.common.OpenAPI from TrHologram v2.4-pre20 which is not a depend, softdepend or loadbefore of this plugin.
[13:55:21] [Server thread/INFO]: [TrChat] INFO | 感谢使用本插件, 您在论坛为本插件评分即是对作者最大的鼓励!`

**Comment by NatJerry** [comment]
+1

**Comment by Yurinann** [comment]
https://github.com/FlickerProjects/TrChat/suites/4200042568/artifacts/108384420
在此处下载最新版本后重试

**Comment by lanzhihry** [comment]
看起来这个问题在Trchat1.90-R3解决了
