### ISSUE TITLE
[问题] 使用%i%会出现报错

### ISSUE THREAD

**Issue by PIXELSTORY2** [FlickerProjects/TrChat#340]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

使用%i%会出现报错

### 配置文件

```YAML
默认
```

### 日志

[16:05:37] [Async Chat Thread - #6/ERROR] [Minecraft]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.9
java.util.concurrent.ExecutionException: me.arasple.mc.trchat.taboolib.common.UnsupportedVersionException: Unsupported version
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2461) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2425) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at me.arasple.mc.trchat.module.display.function.standard.ItemShow.parseVariable(ItemShow.kt:114) ~[?:?]
	at me.arasple.mc.trchat.module.display.format.MsgComponent.createComponent(MsgComponent.kt:42) ~[?:?]
	at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:149) ~[?:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:58) ~[?:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:73) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:593) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575) ~[forge:?]
	at net.minecraft.network.play.ServerPlayNetHandler.chat(ServerPlayNetHandler.java:1724) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_244548_c(ServerPlayNetHandler.java:1666) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1605) ~[?:?]
	at net.minecraft.network.play.client.CChatMessagePacket.lambda$handle$0(CChatMessagePacket.java:34) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: me.arasple.mc.trchat.taboolib.common.UnsupportedVersionException: Unsupported version
	at me.arasple.mc.trchat.taboolib.module.nms.NMSItemImpl.getLocaleKey(NMSItem.kt:190) ~[?:?]
	at me.arasple.mc.trchat.taboolib.module.nms.NMSItemKt.getLocaleKey(NMSItem.kt:24) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.standard.ItemShow.getNameComponent(ItemShow.kt:193) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.standard.ItemShow.access$getNameComponent(ItemShow.kt:46) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.standard.ItemShow$parseVariable$1$1.invoke(ItemShow.kt:130) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.standard.ItemShow$parseVariable$1$1.invoke(ItemShow.kt:128) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.Function$Companion.getComponentFromLang(Function.kt:63) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.standard.ItemShow.parseVariable$lambda$5(ItemShow.kt:128) ~[?:?]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[server-1.16.5-20210115.111550-extra.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[server-1.16.5-20210115.111550-extra.jar:?]
	... 31 more

### 服务器环境

服务器版本: 1.16.5 Catserver

**Comment by ItsFlicker** [comment]
之后会修复
现在可以把ItemShow.UI改为false暂时解决

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/7357248308 修复
