### ISSUE TITLE
[问题] TrChat-2.0.10 密语报错

### ISSUE THREAD

**Issue by MOMOas** [FlickerProjects/TrChat#341]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [x] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

密语自己或对方都会显示错误 但是会接收到对方传来密语
![image](https://github.com/TrPlugins/TrChat/assets/25352223/54f2f735-d8db-4f68-a22c-375c8ed87095)

### 配置文件

```YAML
[01:16:13 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tell' in plugin TrChat v2.0.10
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1020) ~[purpur-1.20.1.jar:git-Purpur-2019]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-2019]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2392) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2352) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2019]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2019]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2019]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2019]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2019]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2019]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2019]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2019]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 4 path $
        at com.google.gson.JsonParser.parseReader(JsonParser.java:76) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parse(JsonParser.java:115) ~[gson-2.10.jar:?]
        at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:48) ~[bungeecord-chat-1.16-R0.4-deprecated+build.9.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.type.BukkitPlayer.sendRawMessage(BukkitPlayer.kt:372) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.module.lang.gameside.TypeActionBar.send(TypeActionBar.kt:40) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.module.lang.TypeList.send(TypeList.kt:22) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.module.lang.LangKt.sendLang(Lang.kt:13) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.module.display.channel.PrivateChannel.execute(PrivateChannel.kt:167) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute$default(Channel.kt:121) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.module.display.channel.PrivateChannel$3$2$3$1.invoke(PrivateChannel.kt:78) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.module.display.channel.PrivateChannel$3$2$3$1.invoke(PrivateChannel.kt:75) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.component.CommandExecutor.exec(CommandExecutor.kt:11) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.component.CommandBase.execute$process(CommandBase.kt:87) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.component.CommandBase.execute$process(CommandBase.kt:78) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.component.CommandBase.execute(CommandBase.kt:100) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:40) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:74) ~[TrChat-2.0.10.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 4 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1463) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parseReader(JsonParser.java:71) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parse(JsonParser.java:115) ~[gson-2.10.jar:?]
        at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:48) ~[bungeecord-chat-1.16-R0.4-deprecated+build.9.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.type.BukkitPlayer.sendRawMessage(BukkitPlayer.kt:372) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.module.lang.gameside.TypeActionBar.send(TypeActionBar.kt:40) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.module.lang.TypeList.send(TypeList.kt:22) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.module.lang.LangKt.sendLang(Lang.kt:13) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.module.display.channel.PrivateChannel.execute(PrivateChannel.kt:167) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute$default(Channel.kt:121) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.module.display.channel.PrivateChannel$3$2$3$1.invoke(PrivateChannel.kt:78) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.module.display.channel.PrivateChannel$3$2$3$1.invoke(PrivateChannel.kt:75) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.component.CommandExecutor.exec(CommandExecutor.kt:11) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.component.CommandBase.execute$process(CommandBase.kt:87) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.component.CommandBase.execute$process(CommandBase.kt:78) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.component.CommandBase.execute(CommandBase.kt:100) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:40) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:74) ~[TrChat-2.0.10.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

### 服务器环境

服务器版本:
1.20.1
插件列表:
[01:17:29 INFO]: Bukkit Plugins: (40):
[01:17:29 INFO]:  - AnnouncerPlus, BlockLocker, Citizens, CMI, *CMIEInjector, CMILib, DecentHolograms, DiscordSRV, FastAsyncWorldEdit, *Gifts
[01:17:29 INFO]:  InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, Invero, ItemsAdder, LoneLibs, LotteryItem, LuckPerms, MMOCore, MMOItems
[01:17:29 INFO]:  ModelEngine, *MoreBagPro, Multiverse-Core, MythicLib, MythicMobs, NBTAPI, NoPlugins, PlaceholderAPI, PlayerGuild, PlayerPoints
[01:17:29 INFO]:  PlayerTitle, PlayerWarp, ProtocolLib, QuickShop, RPGInventory, Shopkeepers, spark, TAB, TrChat, Vault

**Comment by ItsFlicker** [comment]
[TrChat-2.0.10.zip](https://github.com/TrPlugins/TrChat/files/13802767/TrChat-2.0.10.zip)
用这个
