### ISSUE TITLE
[问题] 不能@.聊天中含玩家名报错消息不显示

### ISSUE THREAD

**Issue by CuteLittleSky** [FlickerProjects/TrChat#343]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

不能@.聊天中含玩家名报错消息不显示

### 配置文件

```YAML
.
```

### 日志

[21:45:41 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.10
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON
 at line 1 column 12 path $
        at com.google.gson.JsonParser.parseReader(JsonParser.java:76) ~[gson-2.10.1.jar:?]
        at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[gson-2.10.1.jar:?]
        at com.google.gson.JsonParser.parse(JsonParser.java:115) ~[gson-2.10.1.jar:?]
        at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:48) ~[bungeecord-chat-1.20-R0.1-deprecated+build.14.jar:?
]
        at me.arasple.mc.trchat.taboolib.platform.type.BukkitPlayer.sendRawMessage(BukkitPlayer.kt:372) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.module.lang.gameside.TypeActionBar.send(TypeActionBar.kt:40) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.module.lang.TypeList.send(TypeList.kt:22) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.module.lang.LangKt.sendLang(Lang.kt:13) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.api.impl.BukkitProxyManager.sendProxyLang(BukkitProxyManager.kt:136) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.module.display.function.standard.Mention.parseVariable(Mention.kt:68) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.module.display.format.MsgComponent.createComponent(MsgComponent.kt:42) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:149) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:58) ~[TrChat-2.0.10.jar:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[TrChat-2.0.10.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[TrChat-2.0.10
.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[TrChat-2.0.10
.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[TrChat-2.0.10.ja
r:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[TrChat-2.0.10.ja
r:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:73) ~[TrChat-2.0.10.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2111]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-
2111]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:416) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:102) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2393) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.chat(CraftPlayer.java:712) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at cn.daniellee.plugin.wc.core.WelcomeCore.handleWelcome(WelcomeCore.java:77) ~[Welcome-2.1.0.jar:?]
        at cn.daniellee.plugin.wc.command.WelcomeCommand.onCommand(WelcomeCommand.java:30) ~[Welcome-2.1.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1001) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.4.jar:git-Purpur-211
1]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:452) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:353) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2305) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$17(ServerGamePacketListenerImpl.java:2265) ~[?
:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1485) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1462) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1385) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1577) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2111]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path
$
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659) ~[gson-2.10.1.jar:?]
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465) ~[gson-2.10.1.jar:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551) ~[gson-2.10.1.jar:?]
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.1.jar:?]
        at com.google.gson.JsonParser.parseReader(JsonParser.java:71) ~[gson-2.10.1.jar:?]
        ... 64 more

### 服务器环境

服务器版本: 2.0.10
...
插件列表:
...
![image](https://github.com/TrPlugins/TrChat/assets/62592731/6c0004a3-0653-46d5-8795-453131ac4d97)

**Comment by ItsFlicker** [comment]
https://github.com/TabooLib/taboolib/pull/389

**Comment by ItsFlicker** [comment]
[TrChat-2.0.10.zip](https://github.com/TrPlugins/TrChat/files/13802767/TrChat-2.0.10.zip)
用这个
