### ISSUE TITLE
TrChat-1.90-R3跟PuerkasMarriage起冲突

### ISSUE THREAD

**Issue by yuankun1** [FlickerProjects/TrChat#35]
我吧结婚变量放去聊天前面
然后把结婚插件汉化中文就报错
貌似1.17.1也有这样的问题
下面是报错报告
[11:53:40] [Async Chat Thread - 6/ERROR] [Mohist]: Could not pass event AsyncPlayerChatEvent to PuerkasMarriage v1.9.3-BETA
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:63) ~[EventExecutor.class:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:73) ~[TimedEventExecutor.class:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1507) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1442) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.lambda$processPacket$0(CPacketChatMessage.java:42) ~[la.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_291]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_291]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
Caused by: java.lang.NullPointerException
	at es.capitanpuerka.marriage.controller.LanguageController.getMessage(LanguageController.java:35) ~[?:?]
	at es.capitanpuerka.marriage.listener.PlayerListener.onChat(PlayerListener.java:100) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor116.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:?]
	... 11 more
[11:53:40] [Async Chat Thread - 6/ERROR] [Mohist]: Could not pass event TrChatEvent to TrChat v1.90-R3
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_291]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
	at me.arasple.mc.trchat.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:39) ~[?:?]
	at me.arasple.mc.trchat.internal.listener.ListenerChatEvent.onChat(ListenerChatEvent.kt:65) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_291]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1507) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1442) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.lambda$processPacket$0(CPacketChatMessage.java:42) ~[la.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_291]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_291]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
Caused by: java.lang.NullPointerException
	at es.capitanpuerka.marriage.controller.LanguageController.getMessage(LanguageController.java:35) ~[?:?]
	at es.capitanpuerka.marriage.placeholders.Placeholders.onPlaceholderRequest(Placeholders.java:54) ~[?:?]
	at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:326) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:525) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.compat.PlaceholderExpansionKt.replacePlaceholder(PlaceholderExpansion.kt:15) ~[?:?]
	at me.arasple.mc.trchat.common.chat.format.objects.JsonComponent.toTellrawJson(JsonComponent.kt:82) ~[?:?]
	at me.arasple.mc.trchat.common.chat.format.objects.JsonComponent.toTellrawJson$default(JsonComponent.kt:66) ~[?:?]
	at me.arasple.mc.trchat.common.chat.format.Format.apply(Format.kt:32) ~[?:?]
	at me.arasple.mc.trchat.common.chat.format.Format.apply$default(Format.kt:30) ~[?:?]
	at me.arasple.mc.trchat.common.channel.impl.ChannelNormal.execute$TrChat(ChannelNormal.kt:31) ~[?:?]
	at me.arasple.mc.trchat.common.channel.ChatChannels$ChannelListener$callChannel$1.invoke(ChatChannels.kt:58) ~[?:?]
	at me.arasple.mc.trchat.common.channel.ChatChannels$ChannelListener$callChannel$1.invoke(ChatChannels.kt:57) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common5.MirrorKt.mirrorNow(Mirror.kt:17) ~[?:?]
	at me.arasple.mc.trchat.common.channel.ChatChannels$ChannelListener.callChannel(ChatChannels.kt:57) ~[?:?]
	... 32 more

**Comment by ItsFlicker** [comment]
> at es.capitanpuerka.marriage.controller.LanguageController.getMessage(LanguageController.java:35) ~[?:?]
> at es.capitanpuerka.marriage.placeholders.Placeholders.onPlaceholderRequest(Placeholders.java:54) ~[?:?]

这是在获取papi变量时发生错误
似乎不是trchat的bug
请尝试在其他地方是否能使用该变量
