### ISSUE TITLE
[issue] IA 相关报错

### ISSUE THREAD

**Issue by TUCAOEVER** [FlickerProjects/TrChat#351]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

在使用 2.0.11 版本的 TrChat 时 玩家发送信息时报错
翻阅相关代码，在 `me.arasple.mc.trchat.module.display.format.obj.Text.process(Text.kt:29) `位置传输了 null 值导致此错误，此问题未在2.0.10发现。

```
[14:35:38 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.11
java.lang.NullPointerException: Cannot invoke "org.bukkit.permissions.Permissible.hasPermission(String)" because "<parameter1>" is null
        at ia.m.he.a(SourceFile:333) ~[?:?]
        at ia.m.he.a(SourceFile:313) ~[?:?]
        at dev.lone.itemsadder.api.FontImages.FontImageWrapper.replaceFontImages(SourceFile:28) ~[?:?]
        at me.arasple.mc.trchat.module.internal.hook.impl.HookItemsAdder.replaceFontImages(HookItemsAdder.kt:15) ~[?:?]
        at me.arasple.mc.trchat.module.display.format.obj.Text.process(Text.kt:29) ~[?:?]
        at me.arasple.mc.trchat.module.display.format.JsonComponent.toTextComponent(JsonComponent.kt:21) ~[?:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:148) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:58) ~[?:?]
```

### configuration file

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true

Channel:
  Default: 'Normal'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### Server environment

Server version:
git-Purpur-1171 (MC: 1.16.5)
Plugin list:
Plugins (60): Announce, AuctionGUIPlus, BattlePass, BattlepassExtension, BetonQuest, ChestShop, ChestShopICON, Citizens, CommandWhitelist, CrazyCrates, DeluxeMenus, Essentials, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), Fatigue, GlowAPI*, HolographicDisplays, Images, ItemsAdder, JetsMinions, LangUtils, LeaderMobs, LibsDisguises, LoneLibs, LuckPerms, MiraiMC, MMOCore, MMOItems, MMOREFORGE, Multiverse-Core, MyPet, MythicLib, MythicMobs, ObsidianToLava, PacketListenerApi, PayAPI, PlaceholderAPI, PlayerPoints, PlayerVaults, ProtocolLib, Quests, ShopGUIPlus, SilkSpawners, Skript, skript-fishing, SUPERBIND, SUPERLIB, SUPERPAY, SUPERPORTAL, Sweety, TAB-Bridge, TrChat, TrHologram, Vault, ViaVersion, VirtualSlot*, VoidGen, WorldEditSUI, WorldGuard, WorldGuardExtraFlags

**Comment by ItsFlicker** [comment]
2.0.12 修复
