### ISSUE TITLE
[问题] 玩家进入退出服务器，提示Could not pass event PlayerJoinEvent(PlayerQuitEvent) to TrChat v2.0.11

### ISSUE THREAD

**Issue by WrenZmusic** [FlickerProjects/TrChat#357]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

1、正常开启服务端
2、玩家正常通过velocity代理进入后端服务器
3、错误提示Could not pass event PlayerJoinEvent to TrChat v2.0.11
java.lang.NullPointerException: null
4、玩家通过velocity代理退出后端服务器
5、错误提示Could not pass event PlayerQuitEvent to TrChat v2.0.11
java.lang.IllegalStateException: unavailable

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true

Channel:
  Default: 'Global'

Database:
  Method: SQL
  SQL:
    host: xxxxx.mysql.rds.aliyuncs.com
    port: 3306
    user: xxxxx
    password: xxxx
    database: xxxxxx
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### 日志

[01:10:46] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to TrChat v2.0.11
java.lang.NullPointerException: null
	at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.setupDataContainer(DatabaseHandler.kt:62) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.setupDataContainer(DatabaseHandlerForBukkit.kt:11) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.setupDataContainer$default(DatabaseHandlerForBukkit.kt:10) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerJoin.onJoin(ListenerJoin.kt:31) ~[TrChat-2.0.11.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:73) ~[TrChat-2.0.11.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-318]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:346) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[01:10:46] [Server thread/INFO]: Zhenlilik joined the game

[01:12:53] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to TrChat v2.0.11
java.lang.IllegalStateException: unavailable
	at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.getDataContainer(DatabaseHandler.kt:57) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.getDataContainer(DatabaseHandlerForBukkit.kt:7) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.module.internal.data.PlayerData.isVanishing(PlayerData.kt:36) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.module.internal.data.PlayerData.<init>(PlayerData.kt:20) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:115) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:114) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData$lambda$0(PlayerData.kt:114) ~[TrChat-2.0.11.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData(PlayerData.kt:114) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.module.display.ChatSession.<init>(ChatSession.kt:115) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.module.display.ChatSession$Companion$getSession$1.invoke(ChatSession.kt:104) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.module.display.ChatSession$Companion$getSession$1.invoke(ChatSession.kt:104) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.module.display.ChatSession$Companion.getSession$lambda$0(ChatSession.kt:104) ~[TrChat-2.0.11.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at me.arasple.mc.trchat.module.display.ChatSession$Companion.getSession(ChatSession.kt:104) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.module.display.channel.Channel$Companion.quit(Channel.kt:260) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.module.display.channel.Channel$Companion.quit$default(Channel.kt:241) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.module.display.ChatSession$Companion.removeSession(ChatSession.kt:108) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerQuit.onQuit(ListenerQuit.kt:24) ~[TrChat-2.0.11.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[TrChat-2.0.11.jar:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:73) ~[TrChat-2.0.11.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-318]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:615) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:600) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2066) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2046) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2033) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:837) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:260) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1578) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[01:12:53] [Server thread/INFO]: Zhenlilik left the game

### 服务器环境

服务器版本:
velocity3.3.0
paper1.20.2build#318
插件列表:
TrChat-2.0.11.jar
EssentialsX-2.21.0-dev+33-16e2972.jar
EssentialsXAntiBuild-2.21.0-dev+33-16e2972.jar
EssentialsXProtect-2.21.0-dev+33-16e2972.jar
EssentialsXSpawn-2.21.0-dev+33-16e2972.jar
HuskClaims-Paper-1.0.3-5c217eb.jar
HuskHomes-Plugin-4.5.5-afd6425.jar
HuskSync-Paper-3.3-dabd9bc.jar
LuckPerms-Bukkit-5.4.117.jar
PAPIProxyBridge-1.5.jar
PlaceholderAPI-2.11.5.jar
SignedVelocity-Paper-1.2.3.jar
TAB-Bridge v5.0.2.jar
Vault.jar
worldedit-bukkit-7.3.0-beta-03-dist.jar

**Comment by ItsFlicker** [comment]
检查数据库配置
开服时应该还有其他报错

**Comment by ItsFlicker** [comment]
检查数据库配置
开服时应该还有其他报错

**Comment by ItsFlicker** [comment]
@WrenZmusic
