### ISSUE TITLE
[问题] 无法发送消息

### ISSUE THREAD

**Issue by jhqwqmc** [FlickerProjects/TrChat#361]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

聊天就会立刻warn，等待什么都不干也会时不时的warn

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true

Channel:
  Default: 'Global'

Database:
  Method: MySQL
  SQL:
    host: 192.168.1.100
    port: 3306
    user: root
    password: ***********
    database: trchat
    table: trchat_user_data

Redis:
  enabled: true
  host: localhost
  port: 6380
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### 日志

[04:17:26 WARN]: java.lang.NoSuchMethodError: 'com.electronwill.nightconfig.core.Config me.arasple.mc.trchat.taboolib.module.configuration.ConfigSection.getRoot()'
[04:17:26 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:64)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:44)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$createPubSub$1.onMessage(SingleRedisConnection.kt:184)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.process(JedisPubSub.java:156)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.proceed(JedisPubSub.java:125)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.Jedis.subscribe(Jedis.java:7891)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:160)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:156)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.exec(SingleRedisConnection.kt:40)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.subscribe$lambda$2(SingleRedisConnection.kt:156)
[04:17:26 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[04:17:26 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[04:17:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[04:17:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[04:17:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[04:17:26 WARN]: java.lang.NoSuchMethodError: 'com.electronwill.nightconfig.core.Config me.arasple.mc.trchat.taboolib.module.configuration.ConfigSection.getRoot()'
[04:17:26 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:64)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:44)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$createPubSub$1.onMessage(SingleRedisConnection.kt:184)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.process(JedisPubSub.java:156)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.proceed(JedisPubSub.java:125)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.Jedis.subscribe(Jedis.java:7891)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:160)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:156)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.exec(SingleRedisConnection.kt:40)
[04:17:26 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.subscribe$lambda$2(SingleRedisConnection.kt:156)
[04:17:26 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[04:17:26 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[04:17:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[04:17:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[04:17:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[04:17:30 WARN]: java.lang.NoSuchMethodError: 'com.electronwill.nightconfig.core.Config me.arasple.mc.trchat.taboolib.module.configuration.ConfigSection.getRoot()'
[04:17:30 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:64)
[04:17:30 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:44)
[04:17:30 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$createPubSub$1.onMessage(SingleRedisConnection.kt:184)
[04:17:30 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.process(JedisPubSub.java:156)
[04:17:30 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.proceed(JedisPubSub.java:125)
[04:17:30 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.Jedis.subscribe(Jedis.java:7891)
[04:17:30 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:160)
[04:17:30 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:156)
[04:17:30 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.exec(SingleRedisConnection.kt:40)
[04:17:30 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.subscribe$lambda$2(SingleRedisConnection.kt:156)
[04:17:30 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[04:17:30 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[04:17:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[04:17:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[04:17:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[04:17:40 WARN]: java.lang.NoSuchMethodError: 'com.electronwill.nightconfig.core.Config me.arasple.mc.trchat.taboolib.module.configuration.ConfigSection.getRoot()'
[04:17:40 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:64)
[04:17:40 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:44)
[04:17:40 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$createPubSub$1.onMessage(SingleRedisConnection.kt:184)
[04:17:40 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.process(JedisPubSub.java:156)
[04:17:40 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.proceed(JedisPubSub.java:125)
[04:17:40 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.Jedis.subscribe(Jedis.java:7891)
[04:17:40 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:160)
[04:17:40 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:156)
[04:17:40 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.exec(SingleRedisConnection.kt:40)
[04:17:40 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.subscribe$lambda$2(SingleRedisConnection.kt:156)
[04:17:40 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[04:17:40 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[04:17:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[04:17:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[04:17:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[04:17:50 WARN]: java.lang.NoSuchMethodError: 'com.electronwill.nightconfig.core.Config me.arasple.mc.trchat.taboolib.module.configuration.ConfigSection.getRoot()'
[04:17:50 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:64)
[04:17:50 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:44)
[04:17:50 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$createPubSub$1.onMessage(SingleRedisConnection.kt:184)
[04:17:50 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.process(JedisPubSub.java:156)
[04:17:50 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.proceed(JedisPubSub.java:125)
[04:17:50 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.Jedis.subscribe(Jedis.java:7891)
[04:17:50 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:160)
[04:17:50 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:156)
[04:17:50 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.exec(SingleRedisConnection.kt:40)
[04:17:50 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.subscribe$lambda$2(SingleRedisConnection.kt:156)
[04:17:50 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[04:17:50 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[04:17:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[04:17:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[04:17:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[04:18:00 WARN]: java.lang.NoSuchMethodError: 'com.electronwill.nightconfig.core.Config me.arasple.mc.trchat.taboolib.module.configuration.ConfigSection.getRoot()'
[04:18:00 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:64)
[04:18:00 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:44)
[04:18:00 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$createPubSub$1.onMessage(SingleRedisConnection.kt:184)
[04:18:00 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.process(JedisPubSub.java:156)
[04:18:00 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.proceed(JedisPubSub.java:125)
[04:18:00 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.Jedis.subscribe(Jedis.java:7891)
[04:18:00 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:160)
[04:18:00 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:156)
[04:18:00 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.exec(SingleRedisConnection.kt:40)
[04:18:00 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.subscribe$lambda$2(SingleRedisConnection.kt:156)
[04:18:00 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[04:18:00 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[04:18:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[04:18:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[04:18:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[04:18:10 WARN]: java.lang.NoSuchMethodError: 'com.electronwill.nightconfig.core.Config me.arasple.mc.trchat.taboolib.module.configuration.ConfigSection.getRoot()'
[04:18:10 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:64)
[04:18:10 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:44)
[04:18:10 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$createPubSub$1.onMessage(SingleRedisConnection.kt:184)
[04:18:10 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.process(JedisPubSub.java:156)
[04:18:10 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.proceed(JedisPubSub.java:125)
[04:18:10 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.Jedis.subscribe(Jedis.java:7891)
[04:18:10 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:160)
[04:18:10 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:156)
[04:18:10 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.exec(SingleRedisConnection.kt:40)
[04:18:10 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.subscribe$lambda$2(SingleRedisConnection.kt:156)
[04:18:10 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[04:18:10 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[04:18:10 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[04:18:10 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[04:18:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[04:18:20 WARN]: java.lang.NoSuchMethodError: 'com.electronwill.nightconfig.core.Config me.arasple.mc.trchat.taboolib.module.configuration.ConfigSection.getRoot()'
[04:18:20 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:64)
[04:18:20 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:44)
[04:18:20 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$createPubSub$1.onMessage(SingleRedisConnection.kt:184)
[04:18:20 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.process(JedisPubSub.java:156)
[04:18:20 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.JedisPubSub.proceed(JedisPubSub.java:125)
[04:18:20 WARN]:        at TrChat-2.0.12.jar//redis.clients.jedis_4_2_3.Jedis.subscribe(Jedis.java:7891)
[04:18:20 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:160)
[04:18:20 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:156)
[04:18:20 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.exec(SingleRedisConnection.kt:40)
[04:18:20 WARN]:        at TrChat-2.0.12.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.subscribe$lambda$2(SingleRedisConnection.kt:156)
[04:18:20 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[04:18:20 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[04:18:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[04:18:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[04:18:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

### 服务器环境

服务器版本:
git-Paper-430 (MC: 1.20.4)
插件列表:
Server Plugins (12):
Paper Plugins:
 - HuskHomes
Bukkit Plugins:
 - InvSync, JPremium, LiteBans, LuckPerms, PlaceholderAPI, ProtocolLib, spark, TrChat, Triton, Vault
 XConomy

**Comment by ItsFlicker** [comment]
关闭redis功能
