### ISSUE TITLE
[问题] 混合端环境下无法展示物品

### ISSUE THREAD

**Issue by KanyShigure** [FlickerProjects/TrChat#363]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 详细描述

使用[I][item]或%i%等配置里写的key展示物品，报错，与wiki上操作无差别，开启兼容模式也无法使用

### 配置文件

```YAML
无变化
```

### 日志

[23:25:36 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.11
 java.util.concurrent.ExecutionException: java.lang.NoSuchMethodException: no such method: net.minecraftforge.registries.NamespacedWrapper.b(Object)Object/invokeVirtual
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2461) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2425) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060) ~[minecraft_server.1.12.2.jar:?]
	at me.arasple.mc.trchat.module.display.function.standard.ItemShow.parseVariable(ItemShow.kt:113) ~[?:?]
	at me.arasple.mc.trchat.module.display.format.MsgComponent.createComponent(MsgComponent.kt:45) ~[?:?]
	at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:150) ~[?:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:58) ~[?:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_352]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:73) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1508) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1443) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.lambda$processPacket$0(CPacketChatMessage.java:42) ~[la.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_352]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
Caused by: java.lang.NoSuchMethodException: no such method: net.minecraftforge.registries.NamespacedWrapper.b(Object)Object/invokeVirtual
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:871) ~[?:1.8.0_352]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1003) ~[?:1.8.0_352]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1386) ~[?:1.8.0_352]
	at java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:861) ~[?:1.8.0_352]
	at com.mohistmc.bukkit.nms.proxy.ProxyMethodHandlesLookup.findVirtual(ProxyMethodHandlesLookup.java:31) ~[server.jar:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod$handle$2.invoke(JavaClassMethod.kt:16) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod$handle$2.invoke(JavaClassMethod.kt:12) ~[?:?]
	at kotlin190.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.getHandle(JavaClassMethod.kt:12) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.invokeMethod(Reflex.kt:42) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.invokeMethod$default(Reflex.kt:38) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.util.BukkitTellrawJsonKt.toNMSKeyAndItemData(BukkitTellrawJson.kt:32) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.util.BukkitTellrawJsonKt.hoverItem(BukkitTellrawJson.kt:39) ~[?:?]
	at me.arasple.mc.trchat.util.ComponentUtilKt.hoverItemFixed(ComponentUtil.kt:23) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.standard.ItemShow$parseVariable$1$1.invoke(ItemShow.kt:132) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.standard.ItemShow$parseVariable$1$1.invoke(ItemShow.kt:126) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.Function$Companion.getComponentFromLang(Function.kt:63) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.standard.ItemShow.parseVariable$lambda$4(ItemShow.kt:126) ~[?:?]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[minecraft_server.1.12.2.jar:?]
	... 30 more
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.registries.NamespacedWrapper.b(Ljava/lang/Object;)Ljava/lang/Object;
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_352]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_352]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_352]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1386) ~[?:1.8.0_352]
	at java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:861) ~[?:1.8.0_352]
	at com.mohistmc.bukkit.nms.proxy.ProxyMethodHandlesLookup.findVirtual(ProxyMethodHandlesLookup.java:31) ~[server.jar:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod$handle$2.invoke(JavaClassMethod.kt:16) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod$handle$2.invoke(JavaClassMethod.kt:12) ~[?:?]
	at kotlin190.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.getHandle(JavaClassMethod.kt:12) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.invokeMethod(Reflex.kt:42) ~[?:?]
	at me.arasple.mc.trchat.taboolib.library.reflex.Reflex$Companion.invokeMethod$default(Reflex.kt:38) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.util.BukkitTellrawJsonKt.toNMSKeyAndItemData(BukkitTellrawJson.kt:32) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.util.BukkitTellrawJsonKt.hoverItem(BukkitTellrawJson.kt:39) ~[?:?]
	at me.arasple.mc.trchat.util.ComponentUtilKt.hoverItemFixed(ComponentUtil.kt:23) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.standard.ItemShow$parseVariable$1$1.invoke(ItemShow.kt:132) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.standard.ItemShow$parseVariable$1$1.invoke(ItemShow.kt:126) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.Function$Companion.getComponentFromLang(Function.kt:63) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.standard.ItemShow.parseVariable$lambda$4(ItemShow.kt:126) ~[?:?]
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[minecraft_server.1.12.2.jar:?]
	... 30 more

### 服务器环境

服务器版本:
This server is running Mohist version 1.12.2-340 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)
插件列表:
§aANine-Title§f, §aAttributePlus§f, §aCrackShot§f, §aDragonCore§f, §aEssentials§f, §aEssentialsChat§f, §aEssentialsProtect§f, §aEssentialsSpawn§f, §aFastAsyncWorldEdit§f, §aGroupManager§f, §aInfiniteScoreboard§f, §aLibsDisguises§f, §aMultiverse-Core§f, §aMythicMobs§f, §aNBTAPI§f, §aNeigeItems§f, §aPlaceholderAPI§f, §aPlayerPoints§f, §aProtocolLib§f, §aTrChat§f, §aTrMenu§f, §aVault§f, §aWorldEdit§f, §aWorldEditSUI§f, §aWorldGuard

**Comment by ItsFlicker** [comment]
尝试 https://github.com/TrPlugins/TrChat/actions/runs/8030903080

**Comment by KanyShigure** [comment]
> 尝试 https://github.com/TrPlugins/TrChat/actions/runs/8030903080

已测试，似乎解决，但出现了在加载lib时的大量log刷屏，如下
[23:18:48 INFO]: Loading library 
[23:18:48 INFO]: org.jetbrains.kotlin
[23:18:48 INFO]: :
[23:18:48 INFO]: kotlin-stdlib-common
[23:18:48 INFO]: :
[23:18:48 INFO]: 1.8.22
[23:18:48 INFO]: Relocating ...
[23:18:49 INFO]: Loading library 
[23:18:49 INFO]: org.jetbrains.kotlin
[23:18:49 INFO]: :
[23:18:49 INFO]: kotlin-stdlib
[23:18:49 INFO]: :
[23:18:49 INFO]: 1.8.22
[23:18:49 INFO]: Loading library 
[23:18:49 INFO]: org.jetbrains
[23:18:49 INFO]: :
[23:18:49 INFO]: annotations
[23:18:49 INFO]: :
[23:18:49 INFO]: 13.0
[23:18:49 INFO]: Relocating ...

**Comment by KanyShigure** [comment]
> 尝试 https://github.com/TrPlugins/TrChat/actions/runs/8030903080

新问题，展示空气会产生如下报错
[17:35:29 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.13
 java.lang.IllegalStateException: air
	at me.arasple.mc.trchat.taboolib.platform.util.ItemBuilderKt.buildItem(ItemBuilder.kt:46) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.standard.ItemShow.parseVariable(ItemShow.kt:105) ~[?:?]
	at me.arasple.mc.trchat.module.display.format.MsgComponent.createComponent(MsgComponent.kt:46) ~[?:?]
	at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:147) ~[?:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:48) ~[?:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_352]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1508) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1443) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.lambda$processPacket$0(CPacketChatMessage.java:42) ~[la.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_352]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
被恶意用来刷log了

**Comment by ItsFlicker** [comment]
> 新问题，展示空气会产生如下报错

关闭兼容模式应该没有这个问题

**Comment by KanyShigure** [comment]
> > 新问题，展示空气会产生如下报错
> 
> 关闭兼容模式应该没有这个问题

关闭兼容模式会使控制台收到的是原始消息而非trc处理过的消息，之前不清楚甚至还发过issues

**Comment by KanyShigure** [comment]
> > 新问题，展示空气会产生如下报错
> 
> 关闭兼容模式应该没有这个问题

关闭兼容模式仍然存在该问题
[19:09:46 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.13
 java.lang.IllegalStateException: air
	at me.arasple.mc.trchat.taboolib.platform.util.ItemBuilderKt.buildItem(ItemBuilder.kt:46) ~[?:?]
	at me.arasple.mc.trchat.module.display.function.standard.ItemShow.parseVariable(ItemShow.kt:105) ~[?:?]
	at me.arasple.mc.trchat.module.display.format.MsgComponent.createComponent(MsgComponent.kt:46) ~[?:?]
	at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:147) ~[?:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:48) ~[?:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_352]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1508) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1443) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.lambda$processPacket$0(CPacketChatMessage.java:42) ~[la.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_352]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]

**Comment by ItsFlicker** [comment]
/trchat reload了吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月25日(周日) 晚上7:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TrPlugins/TrChat] [问题] 混合端环境下无法展示物品 (Issue #363)




   
新问题，展示空气会产生如下报错
  
关闭兼容模式应该没有这个问题
  
关闭兼容模式仍然存在该问题
 [19:09:46 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.13
 java.lang.IllegalStateException: air
 at me.arasple.mc.trchat.taboolib.platform.util.ItemBuilderKt.buildItem(ItemBuilder.kt:46) ~[?:?]
 at me.arasple.mc.trchat.module.display.function.standard.ItemShow.parseVariable(ItemShow.kt:105) ~[?:?]
 at me.arasple.mc.trchat.module.display.format.MsgComponent.createComponent(MsgComponent.kt:46) ~[?:?]
 at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:147) ~[?:?]
 at me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:48) ~[?:?]
 at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_352]
 at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
 at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?]
 at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?]
 at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
 at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
 at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
 at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
 at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
 at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
 at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[?:?]
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
 at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1508) ~[pa.class:?]
 at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1443) ~[pa.class:?]
 at net.minecraft.network.play.client.CPacketChatMessage.lambda$processPacket$0(CPacketChatMessage.java:42) ~[la.class:?]
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352]
 at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_352]
 at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_352]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
 at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]

**Comment by KanyShigure** [comment]
> /trchat reload了吗
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年2月25日(周日) 晚上7:10 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [TrPlugins/TrChat] [问题] 混合端环境下无法展示物品 (Issue #363) 新问题，展示空气会产生如下报错 关闭兼容模式应该没有这个问题 关闭兼容模式仍然存在该问题 [19:09:46 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.13 java.lang.IllegalStateException: air at me.arasple.mc.trchat.taboolib.platform.util.ItemBuilderKt.buildItem(ItemBuilder.kt:46) ~[?:?] at me.arasple.mc.trchat.module.display.function.standard.ItemShow.parseVariable(ItemShow.kt:105) ~[?:?] at me.arasple.mc.trchat.module.display.format.MsgComponent.createComponent(MsgComponent.kt:46) ~[?:?] at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:147) ~[?:?] at me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:48) ~[?:?] at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_352] at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?] at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?] at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?] at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?] at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[?:?] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?] at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1508) ~[pa.class:?] at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1443) ~[pa.class:?] at net.minecraft.network.play.client.CPacketChatMessage.lambda$processPacket$0(CPacketChatMessage.java:42) ~[la.class:?] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352] at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_352] at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_352] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352] at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352] — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

本地测试服，平时关服，测试时修改完才开服的

**Comment by ItsFlicker** [comment]
试试 
[TrChat-2.0.13.zip](https://github.com/TrPlugins/TrChat/files/14396189/TrChat-2.0.13.zip)

**Comment by KanyShigure** [comment]
> 试试 [TrChat-2.0.13.zip](https://github.com/TrPlugins/TrChat/files/14396189/TrChat-2.0.13.zip)
不报错了，基本没有问题，但hover到聊天栏上显示的是石头

**Comment by ItsFlicker** [comment]
你没有关function.yml里的Item-Show.Compatible

**Comment by KanyShigure** [comment]
> 你没有关function.yml里的Item-Show.Compatible

似乎没有问题了
