### ISSUE TITLE
[问题] at功能失效

### ISSUE THREAD

**Issue by YuanYuanOwO** [FlickerProjects/TrChat#365]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

1.无法@玩家

### 配置文件

```YAML
无
```

### 日志

```
[02:03:41 WARN]: [TrChat] Plugin TrChat v2.0.13 generated an exception whilst handling plugin message
java.lang.IllegalStateException: Got an error translating component!Please report!
        at me.arasple.mc.trchat.api.nms.NMSImpl.craftChatMessageFromComponent(NMSImpl.kt:41) ~[?:?]
        at me.arasple.mc.trchat.api.nms.NMSImpl.sendMessage(NMSImpl.kt:60) ~[?:?]
        at me.arasple.mc.trchat.api.impl.BukkitComponentManager.sendComponent(BukkitComponentManager.kt:67) ~[TrChat-2.0.13.jar:?]
        at me.arasple.mc.trchat.util.BukkitUtilKt.sendComponent(BukkitUtil.kt:74) ~[TrChat-2.0.13.jar:?]
        at me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor.execute(BukkitProxyProcessor.kt:97) ~[TrChat-2.0.13.jar:?]
        at me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor$BungeeSide.onPluginMessageReceived(BukkitProxyProcessor.kt:197) ~[TrChat-2.0.13.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleCustomPayload(ServerCommonPacketListenerImpl.java:164) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:46) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.a(ServerboundCustomPayloadPacket.java:12) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[paper-1.20.4.jar:git-Paper-430]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-430]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: com.google.gson.JsonParseException: Invalid color name: reset
        at net.minecraft.Util.getOrThrow(Util.java:879) ~[?:?]
        at net.minecraft.network.chat.Component$Serializer.deserialize(Component.java:291) ~[?:?]
        at net.minecraft.network.chat.Component$Serializer.fromJson(Component.java:310) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.util.CraftChatMessage.fromJSON(CraftChatMessage.java:216) ~[paper-1.20.4.jar:git-Paper-430]
        at me.arasple.mc.trchat.api.nms.NMSImpl.craftChatMessageFromComponent(NMSImpl.kt:34) ~[?:?]
        ... 23 more
```

### 服务器环境

```
plugins
[02:05:16 INFO]: Server Plugins (92):
[02:05:16 INFO]: Paper Plugins:
[02:05:16 INFO]:  - HuskSync, MarriageMaster, PCGF_PluginLib
[02:05:16 INFO]: Bukkit Plugins:
[02:05:16 INFO]:  - AntiEndermanMushroom, AntiPopup, BarbatosStoryBook, BetterLogStrip, BetterRTP, BetterTridents, Billboards, BlockLocker, BungeeTabListPlus, ChestSort
[02:05:16 INFO]:  ChunkHeat, Chunky, Citizens, CMI, CMILib, CodFrame, ControlPlayer, CoreProtect, CoreProtectTNT, CrateReloaded
[02:05:16 INFO]:  DailyTaxEconomy, DeluxeMenus, DiscordSRV, DoDoSRV, dynmap, eco, EcoEnchants, EntityDetection, FancyCropTrample, FancyFirework
[02:05:16 INFO]:  FastMinecart, GlobalMarketPlus, GSit, HoloMobHealth, ImageFrame, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, *IronElevators, ItemVoid
[02:05:16 INFO]:  Jobs, *KeepItems, libreforge, LibsDisguises, LiteBans, Lootin, LuckPerms, *MapModCompanion, mcMMO, MelonScoop
[02:05:16 INFO]:  Multiverse-Core, MyPet, NBTAPI, NyaaCore, OreBroadcast, PetMaster, PhantomSMP, PlaceholderAPI, Plan, PlayTimeTracker
[02:05:16 INFO]:  PlugManX, PremiumVanish, ProtocolLib, PvPManager, qsaddon-discordsrv, qsaddon-discount, qsaddon-list, qscompat-ecoenchants, qscompat-worldedit, qssuite-limited
[02:05:16 INFO]:  QuickShop-Hikari, Residence, Shopkeepers, ShopkeepersStandardization, spark, Spectator, Tether, TheSearch, TrChat, TreeAssist
[02:05:16 INFO]:  UserPrefix, Vault, ViewDistanceTweaks, VillagerTradeLimiter, WorldBorder, WorldEdit, WorldEditSUI, WorldGuard, XConomy
paper version
[02:05:24 INFO]: Checking version, please wait...
[02:05:27 INFO]: This server is running Paper version git-Paper-430 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 4939f87)
You are 5 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-424 (MC: 1.20.4)
```

**Comment by ItsFlicker** [comment]
把所有配置文件中的&r替换为&f

**Comment by YuanYuanOwO** [comment]
> 把所有配置文件中的&r替换为&f

虽然很暴力，但是修好了，谢谢

**Comment by YuanYuanOwO** [comment]
> 把所有配置文件中的&r替换为&f

似乎不太管用，可以考虑修复这个问题吗

**Comment by ItsFlicker** [comment]
我这里无法复现这个问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月12日(周二) 下午2:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TrPlugins/TrChat] [问题] at功能失效 (Issue #365)




  
把所有配置文件中的&amp;r替换为&amp;f
  
似乎不太管用，可以考虑修复这个问题吗

**Comment by YuanYuanOwO** [comment]
等我研究一个本地可以复现的方法...  

`例如:玩家ID是Pemdow 但你实际输入@PemDow` 会报错
