### ISSUE TITLE
[issue] folia 2个报错，并且会炸服

### ISSUE THREAD

**Issue by xiaoluofa** [FlickerProjects/TrChat#370]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

报错

### configuration file

```YAML
无
```

### logs

[21:06:25] [pool-35-thread-1/WARN]: java.lang.IllegalStateException: unavailable
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.getDataContainer(DatabaseHandler.kt:57)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.getDataContainer(DatabaseHandlerForBukkit.kt:7)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.data.PlayerData.isVanishing(PlayerData.kt:36)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.data.PlayerData.<init>(PlayerData.kt:20)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:115)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:114)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData$lambda$0(PlayerData.kt:114)
[21:06:25] [pool-35-thread-1/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData(PlayerData.kt:114)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.api.impl.BukkitComponentManager.sendComponent(BukkitComponentManager.kt:97)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.util.BukkitUtilKt.sendComponent(BukkitUtil.kt:74)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor.execute(BukkitProxyProcessor.kt:97)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor$RedisSide.execute(BukkitProxyProcessor.kt:270)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:46)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:44)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$createPubSub$1.onMessage(SingleRedisConnection.kt:184)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//redis.clients.jedis_4_2_3.JedisPubSub.process(JedisPubSub.java:156)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//redis.clients.jedis_4_2_3.JedisPubSub.proceed(JedisPubSub.java:125)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//redis.clients.jedis_4_2_3.Jedis.subscribe(Jedis.java:7891)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:160)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:156)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.exec(SingleRedisConnection.kt:40)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.subscribe$lambda$2(SingleRedisConnection.kt:156)
[21:06:25] [pool-35-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:06:25] [pool-35-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:06:25] [pool-35-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:06:25] [pool-35-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:06:25] [pool-35-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

### Server environment

Server version:
...folia
Plugin list:
...

**Comment by xiaoluofa** [comment]
[21:06:25] [pool-35-thread-1/WARN]: java.lang.IllegalStateException: unavailable
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.getDataContainer(DatabaseHandler.kt:57)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.getDataContainer(DatabaseHandlerForBukkit.kt:7)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.data.PlayerData.isVanishing(PlayerData.kt:36)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.data.PlayerData.<init>(PlayerData.kt:20)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:115)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:114)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData$lambda$0(PlayerData.kt:114)
[21:06:25] [pool-35-thread-1/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData(PlayerData.kt:114)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.api.impl.BukkitComponentManager.sendComponent(BukkitComponentManager.kt:97)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.util.BukkitUtilKt.sendComponent(BukkitUtil.kt:74)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor.execute(BukkitProxyProcessor.kt:97)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor$RedisSide.execute(BukkitProxyProcessor.kt:270)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:46)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.module.internal.proxy.redis.RedisManager$init$1.invoke(RedisManager.kt:44)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$createPubSub$1.onMessage(SingleRedisConnection.kt:184)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//redis.clients.jedis_4_2_3.JedisPubSub.process(JedisPubSub.java:156)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//redis.clients.jedis_4_2_3.JedisPubSub.proceed(JedisPubSub.java:125)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//redis.clients.jedis_4_2_3.Jedis.subscribe(Jedis.java:7891)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:160)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection$subscribe$1$1.invoke(SingleRedisConnection.kt:156)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.exec(SingleRedisConnection.kt:40)
[21:06:25] [pool-35-thread-1/WARN]: 	at TrChat-2.0.15.jar//me.arasple.mc.trchat.taboolib.expansion.SingleRedisConnection.subscribe$lambda$2(SingleRedisConnection.kt:156)
[21:06:25] [pool-35-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:06:25] [pool-35-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:06:25] [pool-35-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:06:25] [pool-35-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:06:25] [pool-35-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by xiaoluofa** [comment]
[20:47:56] [Region Scheduler Thread #12/ERROR]: Thread Region Scheduler Thread #12 failed main thread check: Cannot read world asynchronously
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:57) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlock.getNMS(CraftBlock.java:80) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockStates.getBlockState(CraftBlockStates.java:242) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlock.getState(CraftBlock.java:349) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at net.minecraft.world.level.block.entity.BlockEntity.getOwner(BlockEntity.java:259) ~[?:?]
	at net.minecraft.world.level.block.entity.BlockEntity.getOwner(BlockEntity.java:252) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftInventoryFurnace.getHolder(CraftInventoryFurnace.java:59) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftInventoryFurnace.getHolder(CraftInventoryFurnace.java:8) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at io.github.rypofalem.armorstandeditor.PlayerEditorManager.onPlayerMenuClose(PlayerEditorManager.java:436) ~[armorstandeditor-1.20.4-45.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:git-Luminol-"01abc6c"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1627) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2955) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callInventoryOpenEventWithTitle(CraftEventFactory.java:1420) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callInventoryOpenEventWithTitle(CraftEventFactory.java:1408) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntity.java:369) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:353) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at cn.handyplus.menu.util.MenuUtil.lambda$null$0(MenuUtil.java:71) ~[PlayerMenu-1.2.8.jar:?]
	at cn.handyplus.menu.lib.expand.adapter.FoliaScheduler.lambda$runTask$0(FoliaScheduler.java:25) ~[PlayerMenu-1.2.8.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[luminol-1.20.4.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[luminol-1.20.4.jar:?]
	at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by ItsFlicker** [comment]
第二个报错与trchat无关
可能与armorstandeditor, PlayerMenu有关

**Comment by ItsFlicker** [comment]
第一个报错频繁出现吗?
