### ISSUE TITLE
[问题] 玩家将彩色自定义名称的物品放入铁砧,就会报错

### ISSUE THREAD

**Issue by DanDanisme** [FlickerProjects/TrChat#379]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

玩家将彩色自定义名称的物品放入铁砧,就会报错
§f[§7§l古代剑§f]§e§l七星龙渊§f[§f§l凡品§f]
关闭了铁砧屏蔽词功能也没有解决报错
  Anvil: false

### 配置文件

```YAML
Enable:
  Chat: true
  Sign: true
  Anvil: false

Cloud-Thesaurus:
  Enabled: false
  Ignored: ['nt']
  Urls:
    - 'https://raw.githubusercontent.com/Yurinann/Filter-Thesaurus-Cloud/main/database.json' # 感谢南城提供的词库

Local:
  - 'fuck'
  - 'fuck'
  - 'fucku'
  - 'nmsl'
  - 'sb'
  - 'lj'
```

### 日志

[00:24:05 ERROR]: Could not pass event PrepareAnvilEvent to TrChat v2.0.11
java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.setDisplayNameComponent([Lnet/md_5/bungee/api/chat/BaseComponent;)V
        at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:51) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:42) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.util.ItemModifierKt.modifyMeta(ItemModifier.kt:46) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange.onAnvilCraft(ListenerAnvilChange.kt:42) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_345]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:39) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:73) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1102) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.ContainerAnvil.e(ContainerAnvil.java:296) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.ContainerAnvil.a(ContainerAnvil.java:109) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.ContainerAnvil$1.update(ContainerAnvil.java:20) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.Slot.f(SourceFile:84) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.Container.a(Container.java:321) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2010) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_345]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_345]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_345]

### 服务器环境

服务器版本:
... This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
插件列表:
...

**Comment by ItsFlicker** [comment]
先关闭settings.yml中的Color.Anvil

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/8770523938
