### ISSUE TITLE
[issue] trchat在BC服务器上无法启动

### ISSUE THREAD

**Issue by DuckLee95** [FlickerProjects/TrChat#387]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

trchat在BC服务器上无法启动，给出报错，但不知道原因为何

### configuration file

```YAML
无
```

### logs

00:28:11 [信息] Using standard Java JCE cipher.
00:28:11 [信息] Using standard Java compressor.
00:28:11 [信息] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.20-R0.3-SNAPSHOT:67c65e0:1828
[authlib-injector] [INFO] Httpd is running on port 49512
[authlib-injector] [INFO] Transformed [net.md_5.bungee.connection.InitialHandler] with [Constant URL Transformer]
00:28:12 [信息] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())

00:28:12 [信息] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())

00:28:12 [信息] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())

00:28:12 [信息] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())

00:28:12 [信息] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())

00:28:12 [信息] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())

00:28:12 [信息] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.20-R0.3-SNAPSHOT:67c65e0:1828 by SpigotMC
00:28:12 [信息] Loaded plugin LuckPerms version 5.4.122 by Luck
00:28:12 [信息] Loaded plugin cmd_find version git:cmd_find:1.20-R0.3-SNAPSHOT:67c65e0:1828 by SpigotMC
00:28:12 [信息] Loaded plugin TAB version 4.1.2 by NEZNAMY
00:28:12 [信息] Loaded plugin cmd_server version git:cmd_server:1.20-R0.3-SNAPSHOT:67c65e0:1828 by SpigotMC
00:28:12 [信息] Loaded plugin cmd_alert version git:cmd_alert:1.20-R0.3-SNAPSHOT:67c65e0:1828 by SpigotMC
00:28:12 [信息] Loading library org.jetbrains.kotlin:kotlin-stdlib-common:1.8.22
00:28:12 [信息] Loading library org.jetbrains.kotlin:kotlin-stdlib:1.8.22
00:28:12 [信息] Loading library org.jetbrains:annotations:13.0
00:28:14 [信息] Loading library org.slf4j:slf4j-api:2.0.8
00:28:14 [信息] Loading library com.zaxxer:HikariCP:4.0.3
00:28:14 [信息] Loading library org.openjdk.nashorn:nashorn-core:15.4
00:28:14 [信息] Loading library org.ow2.asm:asm-commons:7.3.1
00:28:14 [信息] Loading library org.ow2.asm:asm-tree:7.3.1
00:28:14 [信息] Loading library org.ow2.asm:asm:7.3.1
00:28:14 [信息] Loading library org.ow2.asm:asm-util:7.3.1
00:28:14 [信息] Loading library org.apache.commons:commons-jexl3:3.2.1
00:28:14 [信息] Loading library com.mojang:datafixerupper:4.0.26
00:28:14 [信息] Loading library redis.clients:jedis:4.2.3
00:28:14 [信息] Loading library org.apache.commons:commons-pool2:2.11.1
00:28:14 [信息] Loading library org.json:json:20211205
00:28:14 [信息] Loading library org.yaml:snakeyaml:2.2
00:28:14 [信息] Loading library com.typesafe:config:1.4.3
00:28:14 [信息] Loading library com.electronwill.night-config:core:3.6.7
00:28:14 [信息] Loading library com.electronwill.night-config:toml:3.6.7
00:28:14 [信息] Loading library com.electronwill.night-config:json:3.6.7
00:28:14 [信息] Loading library com.typesafe:config:1.4.2
00:28:15 [信息] Loading library com.electronwill.night-config:hocon:3.6.7
00:28:15 [警告] Error loading plugin TrChat
java.lang.ExceptionInInitializerError
    at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:12)
    at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:10)
    at kotlin1822.UnsafeLazyImpl.getValue(Lazy.kt:81)
    at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.getHandleGetter(JavaClassField.kt:10)
    at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.get(JavaClassField.kt:31)
    at me.arasple.mc.trchat.taboolib.library.reflex.ClassField.get$default(ClassField.kt:11)
    at me.arasple.mc.trchat.taboolib.common.io.ProjectScannerKt$getInstance$2.invoke(ProjectScanner.kt:158)
    at me.arasple.mc.trchat.taboolib.common.io.ProjectScannerKt$sup$1$value$2.invoke(ProjectScanner.kt:232)
    at kotlin1822.UnsafeLazyImpl.getValue(Lazy.kt:81)
    at me.arasple.mc.trchat.taboolib.common.io.ProjectScannerKt$sup$1.getValue(ProjectScanner.kt:232)
    at me.arasple.mc.trchat.taboolib.common.io.ProjectScannerKt$sup$1.get(ProjectScanner.kt:235)
    at me.arasple.mc.trchat.taboolib.common.platform.PlatformFactory.init$lambda$7(PlatformFactory.kt:57)
    at me.arasple.mc.trchat.taboolib.common.TabooLib$1.run(TabooLib.java:79)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
    at me.arasple.mc.trchat.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56)
    at java.base/java.util.Optional.ifPresent(Optional.java:178)
    at me.arasple.mc.trchat.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56)
    at me.arasple.mc.trchat.taboolib.platform.BungeePlugin.<clinit>(BungeePlugin.java:45)
    at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
    at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
    at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:340)
    at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
    at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:173)
    at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:342)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:251)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:284)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.IllegalStateException: Unsafe not found
    at me.arasple.mc.trchat.taboolib.library.reflex.UnsafeAccess.<clinit>(UnsafeAccess.kt:28)
    ... 31 more

### Server environment

Server version:
BungeeCord #1828 (2024年4月18日 下午8:58:38)
Plugin list:
LuckPerms-Bungee-5.4.122
CMIB-1.0.3.1
TAB.v4.1.2
TrChat-2.1.0

**Comment by DuckLee95** [comment]
JDK22不支持，切换为JDK17问题得到解决
