### ISSUE TITLE
TrChat v1.90-R4

### ISSUE THREAD

**Issue by AspireNewWorld** [FlickerProjects/TrChat#39]
[Netty Server IO #3][ERROR]: Could not pass event PacketSendEvent to TrChat v1.90-R4
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:37) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:37) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:571) [forge:?]
        at me.arasple.mc.trchat.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:39) [TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:18) [TrChat-1.90-R4.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) [server-1.16.5-20210115.111550-extra.jar:?]
        at me.arasple.mc.trhologram.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:19) [TrHologram-2.4-pre24.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [server-1.16.5-20210115.111550-extra.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Caused by: java.lang.IllegalStateException: unavailable
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.getDataContainer(DatabaseHandler.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.getDataContainer(DatabaseHandlerForBukkit.kt:7) ~[?:?]
        at me.arasple.mc.trchat.internal.data.Users.isFilterEnabled(Users.kt:45) ~[?:?]
        at me.arasple.mc.trchat.internal.listener.ListenerPackets.e(ListenerPackets.kt:25) ~[?:?]
        ... 30 more

**Comment by MCJiaoLong** [comment]
同样
Spigot1.17.1
![image](https://user-images.githubusercontent.com/75253383/147384546-8abd334a-746e-4396-8c81-18208307cde2.png)

**Comment by ItsFlicker** [comment]
请给出完整日志

**Comment by ItsFlicker** [comment]
请使用1.90-R5
