### ISSUE TITLE
[问题] java22报错

### ISSUE THREAD

**Issue by MrM88M** [FlickerProjects/TrChat#391]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

java21没事换22后启动时候报错Caused by: java.lang.IllegalStateException: Unsafe not found

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: auto
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server', 'vault', 'multiverse']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true

Channel:
  Default: 'global'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0
  Cooldown: '1.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### 日志

[15:53:50 INFO]: [TrChat-2.1.0.jar] Loading library org.jetbrains.kotlin:kotlin-stdlib-common:1.8.22
[15:53:50 INFO]: [TrChat-2.1.0.jar] Loading library org.jetbrains.kotlin:kotlin-stdlib:1.8.22
[15:53:50 INFO]: [TrChat-2.1.0.jar] Loading library org.jetbrains:annotations:13.0
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library org.slf4j:slf4j-api:2.0.8
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library com.zaxxer:HikariCP:4.0.3
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library org.openjdk.nashorn:nashorn-core:15.4
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library org.ow2.asm:asm-commons:7.3.1
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library org.ow2.asm:asm-tree:7.3.1
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library org.ow2.asm:asm:7.3.1
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library org.ow2.asm:asm-util:7.3.1
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library org.apache.commons:commons-jexl3:3.2.1
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library redis.clients:jedis:4.2.3
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library org.apache.commons:commons-pool2:2.11.1
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library org.json:json:20211205
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library org.yaml:snakeyaml:2.2
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library com.typesafe:config:1.4.3
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library com.electronwill.night-config:core:3.6.7
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library com.electronwill.night-config:toml:3.6.7
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library com.electronwill.night-config:json:3.6.7
[15:53:51 INFO]: [TrChat-2.1.0.jar] Loading library com.typesafe:config:1.4.2
[15:53:52 INFO]: [TrChat-2.1.0.jar] Loading library com.electronwill.night-config:hocon:3.6.7
[15:53:52 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'TrChat-2.1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[purpur-1.20.4.jar:git-Purpur-2171]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.20.4.jar:git-Purpur-2171]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.4.jar:git-Purpur-2171]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[purpur-1.20.4.jar:git-Purpur-2171]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.4.jar:git-Purpur-2171]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:521) ~[purpur-1.20.4.jar:git-Purpur-2171]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[purpur-1.20.4.jar:git-Purpur-2171]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2171]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2171]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:12) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:10) ~[TrChat-2.1.0.jar:?]
        at kotlin1822.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.getHandleGetter(JavaClassField.kt:10) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.get(JavaClassField.kt:31) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.ClassField.get$default(ClassField.kt:11) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.io.ProjectScannerKt$getInstance$2.invoke(ProjectScanner.kt:158) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.io.ProjectScannerKt$sup$1$value$2.invoke(ProjectScanner.kt:232) ~[TrChat-2.1.0.jar:?]
        at kotlin1822.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.io.ProjectScannerKt$sup$1.getValue(ProjectScanner.kt:232) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.io.ProjectScannerKt$sup$1.get(ProjectScanner.kt:235) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.PlatformFactory.init$lambda$7(PlatformFactory.kt:57) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLib$1.run(TabooLib.java:79) ~[TrChat-2.1.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1597) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56) ~[TrChat-2.1.0.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:53) ~[TrChat-2.1.0.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:529) ~[?:?]
        at java.lang.Class.forName(Class.java:508) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.20.4.jar:git-Purpur-2171]
        ... 9 more
Caused by: java.lang.IllegalStateException: Unsafe not found
        at me.arasple.mc.trchat.taboolib.library.reflex.UnsafeAccess.<clinit>(UnsafeAccess.kt:28) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:12) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:10) ~[TrChat-2.1.0.jar:?]
        at kotlin1822.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.getHandleGetter(JavaClassField.kt:10) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.get(JavaClassField.kt:31) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.ClassField.get$default(ClassField.kt:11) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.io.ProjectScannerKt$getInstance$2.invoke(ProjectScanner.kt:158) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.io.ProjectScannerKt$sup$1$value$2.invoke(ProjectScanner.kt:232) ~[TrChat-2.1.0.jar:?]
        at kotlin1822.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.io.ProjectScannerKt$sup$1.getValue(ProjectScanner.kt:232) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.io.ProjectScannerKt$sup$1.get(ProjectScanner.kt:235) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.PlatformFactory.init$lambda$7(PlatformFactory.kt:57) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLib$1.run(TabooLib.java:79) ~[TrChat-2.1.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1597) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56) ~[TrChat-2.1.0.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56) ~[TrChat-2.1.0.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:53) ~[TrChat-2.1.0.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:529) ~[?:?]
        at java.lang.Class.forName(Class.java:508) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.20.4.jar:git-Purpur-2171]
        ... 9 more

### 服务器环境

服务器版本:
purpur1.20.4
插件列表:
...

**Comment by ItsFlicker** [comment]
我无法修复，你可以到 https://github.com/TabooLib/taboolib 提交issue

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/10979411611
