### ISSUE TITLE
1.81报错日志  不影响运行 创造模式下拿取物品放进背包就会刷这个错误

### ISSUE THREAD

**Issue by GoaTham** [FlickerProjects/TrChat#4]
[18:51:48] [Netty Server IO #1/ERROR]: Could not pass event BukkitProxyEvent to TrChat v1.81
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:57) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-26208f0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) ~[SimplePluginManager.class:git-CatServer-1.12.2-26208f0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[SimplePluginManager.class:git-CatServer-1.12.2-26208f0]
        at me.arasple.mc.trchat.taboolib.platform.BukkitEvent.callEvent(BukkitEvent.kt:28) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.EventKt.callEvent(Event.kt:8) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.ProxyEvent.call(ProxyEvent.kt:20) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:18) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at me.arasple.mc.trhologram.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:19) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at com.interactiveboard.utility.nms.map.MapPacket_1_12_R1$1.write(MapPacket_1_12_R1.java:57) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at me.arasple.mc.trmenu.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:19) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) ~[?:?]
        at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:204) ~[gw$4.class:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:310) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.NoSuchMethodError: org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack.asCraftMirror(Lnet/minecraft/item/ItemStack;)Lorg/bukkit/craftbukkit/v1_12_R1/inventory/CraftItemStack;
        at me.arasple.mc.trchat.api.nms.PacketUtilsImpl.filterItem(PacketUtilsImpl.kt:29) ~[?:?]
        at me.arasple.mc.trchat.module.filter.listeners.FilterListener.filterPacket(FilterListener.kt:51) ~[?:?]
        ... 48 more
[18:51:49] [Netty Server IO #1/ERROR]: Could not pass event BukkitProxyEvent to TrChat v1.81
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:57) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-26208f0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) ~[SimplePluginManager.class:git-CatServer-1.12.2-26208f0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[SimplePluginManager.class:git-CatServer-1.12.2-26208f0]
        at me.arasple.mc.trchat.taboolib.platform.BukkitEvent.callEvent(BukkitEvent.kt:28) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.EventKt.callEvent(Event.kt:8) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.ProxyEvent.call(ProxyEvent.kt:20) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:18) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at me.arasple.mc.trhologram.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:19) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at com.interactiveboard.utility.nms.map.MapPacket_1_12_R1$1.write(MapPacket_1_12_R1.java:57) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at me.arasple.mc.trmenu.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:19) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[netty-all-4.1.24.Final.jar:4.1.24.Final]
        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) ~[?:?]
        at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:204) ~[gw$4.class:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:310) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.24.Final.jar:4.1.24.Final]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.NoSuchMethodError: org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack.asCraftMirror(Lnet/minecraft/item/ItemStack;)Lorg/bukkit/craftbukkit/v1_12_R1/inventory/CraftItemStack;
        at me.arasple.mc.trchat.api.nms.PacketUtilsImpl.filterItem(PacketUtilsImpl.kt:29) ~[?:?]
        at me.arasple.mc.trchat.module.filter.listeners.FilterListener.filterPacket(FilterListener.kt:51) ~[?:?]
        ... 48 more

版本 1.12.2
核心 CatServer-26208f0-universal.jar

**Comment by ItsFlicker** [comment]
将在下个版本修复
mod服务端无法过滤物品
