### ISSUE TITLE
[问题]  跨分流[i] 回到大厅

### ISSUE THREAD

**Issue by MOMOas** [FlickerProjects/TrChat#400]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

在server1 展示物品  被踢回大厅  不管展示任何物品 空气 都会被踢回大厅

### 配置文件

```YAML
21:04:38 [WARNING] [MoMo_DD] <-> DownstreamBridge <-> [server1] - could not decode packet!
io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "minecraft:air"
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:455)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "minecraft:air"
    at com.google.gson.Gson.fromJson(Gson.java:1238)
    at com.google.gson.Gson.fromJson(Gson.java:1329)
    at com.google.gson.Gson.fromJson(Gson.java:1300)
    at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
    at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:77)
    at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:26)
    at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:13)
    at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
    at com.google.gson.Gson.fromJson(Gson.java:1227)
    at com.google.gson.Gson.fromJson(Gson.java:1329)
    at com.google.gson.Gson.fromJson(Gson.java:1300)
    at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
    at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:211)
    at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:30)
    at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
    at com.google.gson.Gson.fromJson(Gson.java:1227)
    at com.google.gson.Gson.fromJson(Gson.java:1329)
    at com.google.gson.Gson.fromJson(Gson.java:1300)
    at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
    at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:93)
    at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:26)
    at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:13)
    at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
    at com.google.gson.Gson.fromJson(Gson.java:1227)
    at com.google.gson.Gson.fromJson(Gson.java:1329)
    at com.google.gson.Gson.fromJson(Gson.java:1300)
    at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179)
    at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:211)
    at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:30)
    at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
    at com.google.gson.Gson.fromJson(Gson.java:1227)
    at com.google.gson.Gson.fromJson(Gson.java:1329)
    at com.google.gson.Gson.fromJson(Gson.java:1271)
    at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:120)
    at net.md_5.bungee.protocol.DefinedPacket.readBaseComponent(DefinedPacket.java:113)
    at net.md_5.bungee.protocol.packet.SystemChat.read(SystemChat.java:27)
    at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:524)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:42)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:11)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    ... 26 more
Caused by: java.lang.IllegalStateException: Not a JSON Object: "minecraft:air"
    at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:101)
    at net.md_5.bungee.api.chat.hover.content.ItemSerializer.deserialize(ItemSerializer.java:20)
    at net.md_5.bungee.api.chat.hover.content.ItemSerializer.deserialize(ItemSerializer.java:14)
    at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
    at com.google.gson.Gson.fromJson(Gson.java:1227)
    ... 67 more
```

### 服务器环境

服务器版本:
1.20.4
插件列表:
[21:06:12 INFO]: Paper Plugins: (1):
[21:06:12 INFO]:  - HuskSync
[21:06:12 INFO]: Bukkit Plugins: (76):
[21:06:12 INFO]:  - AnnouncerPlus, Bank, BlockLocker, ChestPreview, Citizens, CMI, *CMIEInjector, CMILib, Core, CoreProtect
[21:06:12 INFO]:  CosmeticsCore, DecentHolograms, DiscordBoost, DiscordSRV, DungeonPlus, DungeonPlusPatcher, eco, EcoEnchants, Elevator, EpicCraftingsPlus
[21:06:12 INFO]:  FastAsyncWorldEdit, Gifts, HeadDatabase, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, Invero, ItemsAdder, libreforge
[21:06:12 INFO]:  LibsDisguises, LiteSignIn, LoneLibs, LotteryItem, LuckPerms, MagicGestures, MessageSender, MiniMOTD, MMOCore, MMOItems
[21:06:12 INFO]:  ModelEngine, MoreBagPro, Multiverse-Core, MythicChanger, MythicCrucible, MythicLib, MythicMobs, NBTAPI, NoPlugins, packetevents
[21:06:12 INFO]:  PlaceholderAPI, PlayerGuild, PlayerPoints, PlayerTitle, PlayerWarp, PlugManX, ProtocolLib, QuickShop-Hikari, Residence, RPGInventory
[21:06:12 INFO]:  Shopkeepers, spark, Spectator, TAB-Bridge, TempFly, TimedItem, Translator, TrChat, TreasureChestX, Typewriter
[21:06:12 INFO]:  UltimateTimber, Vault, WorldBorder, WorldGuard, YuBattleMusic, YuIllustration

**Comment by ItsFlicker** [comment]
尝试切换Double-Transfer

**Comment by ItsFlicker** [comment]
用velocity
