### ISSUE TITLE
[issue] 玩家说话没有反应，聊天栏不显示，后台显示

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [FlickerProjects/TrChat#402]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

1.8的paper服务端，复制粘贴的配置文件和插件，在另一个1.20.1的服务端运行正常

### configuration file

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true
  Disabled-Commands: []

Channel:
  Default: 'kuafu'

Database:
  Method: SQLite
  SQL:
    host: localhost
    port: 3306
    user: root
    password: root
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true
```

### logs

[17:11:58 INFO]: UUID of player The_Leopard_King is db4cd43b-72e5-32d3-928b-189e456886b8
[17:11:58 ERROR]: Could not pass event PlayerJoinEvent to TrChat v2.1.0
java.lang.NullPointerException
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.setupDataContainer(DatabaseHandler.kt:62) ~[?:?]
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.setupDataContainer(DatabaseHandlerForBukkit.kt:11) ~[?:?]
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.setupDataContainer$default(DatabaseHandlerForBukkit.kt:10) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerJoin.onJoin(ListenerJoin.kt:30) ~[?:?]
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:872) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at java.base/java.lang.Thread.run(Thread.java:842) [?:?]
[17:11:58 INFO]: The_Leopard_King[/116.29.247.119:46689] logged in with entity id 13 at ([world]-273.48651768507284, 104.0, 452.55578165921554)
[17:12:01 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.1.0
java.lang.IllegalStateException: unavailable
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.getDataContainer(DatabaseHandler.kt:57) ~[?:?]
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.getDataContainer(DatabaseHandlerForBukkit.kt:7) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData.isVanishing(PlayerData.kt:36) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData.<init>(PlayerData.kt:20) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:115) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:114) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData$lambda$0(PlayerData.kt:114) ~[?:?]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData(PlayerData.kt:114) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession.<init>(ChatSession.kt:115) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion$getSession$1.invoke(ChatSession.kt:104) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion$getSession$1.invoke(ChatSession.kt:104) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion.getSession$lambda$0(ChatSession.kt:104) ~[?:?]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion.getSession(ChatSession.kt:104) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:53) ~[?:?]
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1087) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1025) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.base/java.lang.Thread.run(Thread.java:842) [?:?]
[17:12:01 INFO]: <The_Leopard_King> t

[17:12:03 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.1.0
java.lang.IllegalStateException: unavailable
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.getDataContainer(DatabaseHandler.kt:57) ~[?:?]
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.getDataContainer(DatabaseHandlerForBukkit.kt:7) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData.isVanishing(PlayerData.kt:36) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData.<init>(PlayerData.kt:20) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:115) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:114) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData$lambda$0(PlayerData.kt:114) ~[?:?]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData(PlayerData.kt:114) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession.<init>(ChatSession.kt:115) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion$getSession$1.invoke(ChatSession.kt:104) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion$getSession$1.invoke(ChatSession.kt:104) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion.getSession$lambda$0(ChatSession.kt:104) ~[?:?]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion.getSession(ChatSession.kt:104) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:53) ~[?:?]
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1087) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1025) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-5be55c3-18fbb24]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.base/java.lang.Thread.run(Thread.java:842) [?:?]
[17:12:03 INFO]: <The_Leopard_King> ttt

### Server environment

Server version:
...[17:14:58 INFO]: This server is running CraftBukkit version git-PaperSpigot-5be55c3-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Plugin list:
...
<img width="426" alt="image" src="https://github.com/TrPlugins/TrChat/assets/141799770/b650ba55-acb3-4558-ba4f-8a70cae365c9">

另外插件指令不见了
<img width="311" alt="image" src="https://github.com/TrPlugins/TrChat/assets/141799770/6b65906a-6de9-4d8e-ab06-560436234fb2">
<img width="334" alt="image" src="https://github.com/TrPlugins/TrChat/assets/141799770/26ff2570-d64a-4003-ab4e-6b5166fec1d6">

**Comment by ItsFlicker** [comment]
https://trchat.trixey.cc/guide/known-issues#_1-8%E7%89%88%E6%9C%AC%E5%8A%A0%E8%BD%BD%E9%94%99%E8%AF%AF

**Comment by MinecraftEarthVillage** [comment]
> https://trchat.trixey.cc/guide/known-issues#_1-8%E7%89%88%E6%9C%AC%E5%8A%A0%E8%BD%BD%E9%94%99%E8%AF%AF

懂了
对了，怎么进群

**Comment by ItsFlicker** [comment]
907851976

**Comment by MinecraftEarthVillage** [comment]
> 907851976

你确定这是官方群????
为什么管理员有它![Screenshot_2024-05-16-17-23-01-288_com.tencent.mobileqq-edit.jpg](https://github.com/TrPlugins/TrChat/assets/141799770/f985e30a-a66c-4566-be31-fa61bd6c55e8)

![Image_1715851377009.jpg](https://github.com/TrPlugins/TrChat/assets/141799770/ebd1ea1a-1681-4ecf-991b-861c1d57e04c)

它有没有参与开发
因为之前服务端被入侵过，我对这个人的插件十分警惕

**Comment by ItsFlicker** [comment]
没有参与开发
并且这只是交流群，没有trchat官方群
