### ISSUE TITLE
[issue] trchat 一说话就会提示错误。游戏版本1.20.4

### ISSUE THREAD

**Issue by xingfujiuhao** [FlickerProjects/TrChat#405]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

一说话就会提示错误。游戏版本1.20.4
原版生成配置没动，想知道这个是哪里的问题

### configuration file

```YAML
123
```

### logs

[21:25:48 INFO]: [TrChat] Error occurred when parsing placeholder!This is not a bug of TrChat
[21:25:48 INFO]: java.lang.IllegalArgumentException: Attempt to get net.minecraft.server.level.PlayerInteractManager field "net.minecraft.server.level.EntityPlayer.e" with illegal data type conversion to int
[21:25:48 INFO]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.newGetIllegalArgumentException(UnsafeFieldAccessorImpl.java:69)
[21:25:48 INFO]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.newGetIntIllegalArgumentException(UnsafeFieldAccessorImpl.java:132)
[21:25:48 INFO]:        at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.getInt(UnsafeQualifiedObjectFieldAccessorImpl.java:59)
[21:25:48 INFO]:        at java.base/java.lang.reflect.Field.getInt(Field.java:601)
[21:25:48 INFO]:        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:66)
[21:25:48 INFO]:        at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:50)
[21:25:48 INFO]:        at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:122)
[21:25:48 INFO]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:481)
[21:25:48 INFO]:        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:403)
[21:25:48 INFO]:        at PlaceholderAPI.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[21:25:48 INFO]:        at PlaceholderAPI.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[21:25:48 INFO]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.util.BukkitUtilKt.setPlaceholders(BukkitUtil.kt:42)
[21:25:48 INFO]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.module.display.format.obj.Style$Companion.applyTo(Style.kt:93)
[21:25:48 INFO]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.module.display.format.JsonComponent.toTextComponent(JsonComponent.kt:23)
[21:25:48 INFO]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:148)
[21:25:48 INFO]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:48)
[21:25:48 INFO]:        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
[21:25:48 INFO]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[21:25:48 INFO]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107)
[21:25:48 INFO]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105)
[21:25:48 INFO]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75)
[21:25:48 INFO]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75)
[21:25:48 INFO]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36)
[21:25:48 INFO]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36)
[21:25:48 INFO]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34)
[21:25:48 INFO]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34)
[21:25:48 INFO]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55)
[21:25:48 INFO]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[21:25:48 INFO]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:25:48 INFO]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[21:25:48 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[21:25:48 INFO]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[21:25:48 INFO]:        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378)
[21:25:48 INFO]:        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85)
[21:25:48 INFO]:        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2389)
[21:25:48 INFO]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2518)
[21:25:48 INFO]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChat$14(PlayerConnection.java:2238)
[21:25:48 INFO]:        at net.minecraft.util.FutureChain.a(FutureChain.java:25)
[21:25:48 INFO]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[21:25:48 INFO]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[21:25:48 INFO]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:25:48 INFO]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:25:48 INFO]:        at java.base/java.lang.Thread.run(Thread.java:833)
[21:25:48 INFO]: [world] xinbuzaiyan: adad

### Server environment

Server version:
...
Plugin list:
...

**Comment by xingfujiuhao** [comment]
已修复重新安装变量
