### ISSUE TITLE
[问题] 增加.1.20.5/1.20.6支持

### ISSUE THREAD

**Issue by ZoruaFox** [FlickerProjects/TrChat#408]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

增加1.20.5/1.20.6以及Java21的支持

### 配置文件

```YAML
Unnecessary
```

### 日志

```java
[20:28:06 INFO]: [TrChat] Loading server plugin TrChat v2.1.0
[20:28:06 WARN]: me.arasple.mc.trchat.taboolib.common.inject.ClassVisitException: class me.arasple.mc.trchat.taboolib.module.nms.MinecraftVersion#init: VisitorGroup{priority=0, list=[AwakeFunction(lifeCycle=NONE), AwakeFunction(lifeCycle=CONST), AwakeFunction(lifeCycle=INIT), AwakeFunction(lifeCycle=LOAD), AwakeFunction(lifeCycle=ENABLE), AwakeFunction(lifeCycle=ACTIVE), AwakeFunction(lifeCycle=DISABLE), me.arasple.mc.trchat.taboolib.common.platform.command.SimpleCommandRegister@198d0310, me.arasple.mc.trchat.taboolib.platform.compat.PlaceholderExpansion$PlaceholderRegister@44288c2f, me.arasple.mc.trchat.taboolib.module.kether.KetherLoader@3f8eaa5b]} (LOAD)
[20:28:06 WARN]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:144)
[20:28:06 WARN]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:112)
[20:28:06 WARN]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:75)
[20:28:06 WARN]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.lambda$init$0(VisitorHandler.java:42)
[20:28:06 WARN]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.common.TabooLib$1.run(TabooLib.java:79)
[20:28:06 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[20:28:06 WARN]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56)
[20:28:06 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)
[20:28:06 WARN]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56)
[20:28:06 WARN]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onLoad(BukkitPlugin.java:73)
[20:28:06 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[20:28:06 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[20:28:06 WARN]:        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[20:28:06 WARN]:        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[20:28:06 WARN]:        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:524)
[20:28:06 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:320)
[20:28:06 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150)
[20:28:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[20:28:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[20:28:06 WARN]: Caused by: java.lang.IllegalStateException: Unsupported Minecraft version, plugin disabled
[20:28:06 WARN]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.module.nms.MinecraftVersion.init(MinecraftVersion.kt:206)
[20:28:06 WARN]:        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
[20:28:06 WARN]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[20:28:06 WARN]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.common.platform.AwakeFunction.visit(AwakeFunction.kt:13)
[20:28:06 WARN]:        at TrChat-2.1.0.jar//me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:142)
[20:28:06 WARN]:        ... 18 more
```

### 服务器环境

服务器版本:
`Current Purpur Version: 1.20.6-2224-be3a6d5 (MC: 1.20.6)*`
插件列表:
Unnecessary

**Comment by CuteLittleSky** [comment]
增加 1.21 支持 QAQ

**Comment by ItsFlicker** [comment]
@CuteLittleSky 
https://github.com/user-attachments/files/15884557/TrChat-2.1.3.zip

**Comment by ZoruaFox** [comment]
> @CuteLittleSky https://github.com/user-attachments/files/15884557/TrChat-2.1.3.zip

https://mclo.gs/iYqRoXk

Current Purpur Version: 1.20.6-2233-0d6766e (MC: 1.20.6)*
* You are running the latest version
Previous: 1.20.6-2232-f1c87e4 (MC: 1.20.6)

**Comment by YuanYuanOwO** [comment]
打扰了，BC端有报错
```
[01:07:57 WARN]: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@6b00b6b, receiver=Daylight_Yuan), cancelled=false, tag=trchat:main) to listener me.arasple.mc.trchat.taboolib.platform.BungeeListener$BungeeListener@1b83fac3
java.lang.IllegalStateException: Not a JSON Object: null
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:101) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at me.arasple.mc.trchat.util.proxy.common.MessageReader.read(MessageReader.java:39) ~[?:?]
        at me.arasple.mc.trchat.util.proxy.common.MessageReader.read(MessageReader.java:30) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerBungeeTransfer.onTransfer(ListenerBungeeTransfer.kt:37) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBungee$2.invoke(EventBus.kt:89) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBungee$2.invoke(EventBus.kt:89) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBungeeListener$1.invoke(Listener.kt:58) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBungeeListener$1.invoke(Listener.kt:58) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BungeeListener$registerListener$listener$1.invoke(BungeeListener.kt:44) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BungeeListener$registerListener$listener$1.invoke(BungeeListener.kt:44) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BungeeListener$BungeeListener.handle(BungeeListener.kt:64) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:321) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:93) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:128) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
```
