### ISSUE TITLE
[issue] 玩家进服会报错

### ISSUE THREAD

**Issue by Luoboawa** [FlickerProjects/TrChat#410]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

玩家进服就会报错，用的luminol-1.20.4-paperclip核心
trchat用的最新构建的2.1.0版本，还使用了https://github.com/TrPlugins/TrChat/actions/runs/9451980664里构建的版本
均有此报错，现将报错发送给您
[TrChat配置文件打包.zip](https://github.com/user-attachments/files/15903594/TrChat.zip)
[报错日志.gz](https://github.com/user-attachments/files/15903603/default.gz)

### configuration file

```YAML
[23:40:28] [Region Scheduler Thread #0/ERROR]: Could not pass event PlayerLoginEvent to TrChat v2.1.2
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at java.lang.invoke.DirectMethodHandle.checkBase(DirectMethodHandle.java:547) ~[?:?]
	at jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.get(MethodHandleObjectFieldAccessorImpl.java:57) ~[?:?]
	at java.lang.reflect.Field.get(Field.java:444) ~[?:?]
	at me.arasple.mc.trchat.taboolib.module.nms.TinyReflection$1.get(TinyReflection.java:153) ~[TrChat-2.1.2.jar:?]
	at me.arasple.mc.trchat.taboolib.module.nms.TinyProtocol.getChannel(TinyProtocol.java:391) ~[TrChat-2.1.2.jar:?]
	at me.arasple.mc.trchat.taboolib.module.nms.TinyProtocol$4.onPlayerLogin(TinyProtocol.java:167) ~[TrChat-2.1.2.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:git-Luminol-"b22fc1f"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[luminol-1.20.4.jar:git-Luminol-"b22fc1f"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[luminol-1.20.4.jar:git-Luminol-"b22fc1f"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.canPlayerLogin(PlayerList.java:1020) ~[luminol-1.20.4.jar:git-Luminol-"b22fc1f"]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.verifyLoginAndFinishConnectionSetup(ServerLoginPacketListenerImpl.java:200) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:91) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:657) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedServer.tickConnections(RegionizedServer.java:369) ~[luminol-1.20.4.jar:git-Luminol-"b22fc1f"]
	at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:313) ~[luminol-1.20.4.jar:git-Luminol-"b22fc1f"]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[luminol-1.20.4.jar:git-Luminol-"b22fc1f"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"b22fc1f"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"b22fc1f"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Server environment

Server version:
luminol-1.20.4-paperclip
Plugin list:
![image](https://github.com/TrPlugins/TrChat/assets/79266315/856ee741-1cb9-4c4b-95d5-0a1f50fad603)

**Comment by HaHaWTH** [comment]
TabooLib/taboolib#423 🤔

**Comment by Luoboawa** [comment]
> [禁忌库/禁忌库#423](https://github.com/TabooLib/taboolib/issues/423) 🤔

我没用间歇泉啊
I'm not using the Geyser plugin

**Comment by ItsFlicker** [comment]
不太清楚是什么问题
把settings.yml里的Use-Packets改为false

**Comment by Luoboawa** [comment]
> settings.yml里的Use-Packets

settings.yml里似乎没有Use-Packets这个配置选项

**Comment by ItsFlicker** [comment]
https://trchat.trixey.cc/guide/configuration#settings-yml

**Comment by Luoboawa** [comment]
> https://trchat.trixey.cc/guide/configuration#settings-yml

好的谢谢
