### ISSUE TITLE
[issue] 增加1.21兼容

### ISSUE THREAD

**Issue by HYDeath** [FlickerProjects/TrChat#412]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

无

### configuration file

```YAML
[15:34:26 WARN]: [TrChat] Plugin TrChat v2.1.2 generated an exception whilst handling plugin message
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/CraftServer/entity/CraftPlayer
        at me.arasple.mc.trchat.api.nms.NMSImpl.sendMessage(NMSImpl.kt:69) ~[?:?]
        at TrChat-2.1.2.jar/me.arasple.mc.trchat.api.impl.BukkitComponentManager.sendComponent(BukkitComponentManager.kt:73) ~[TrChat-2.1.2.jar:?]
        at TrChat-2.1.2.jar/me.arasple.mc.trchat.util.BukkitUtilKt.sendComponent(BukkitUtil.kt:74) ~[TrChat-2.1.2.jar:?]
        at TrChat-2.1.2.jar/me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor.execute(BukkitProxyProcessor.kt:97) ~[TrChat-2.1.2.jar:?]
        at TrChat-2.1.2.jar/me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor$VelocitySide.onPluginMessageReceived(BukkitProxyProcessor.kt:238) ~[TrChat-2.1.2.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleCustomPayload(ServerCommonPacketListenerImpl.java:197) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:26) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:13) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1408) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1415) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-2-b4b8208]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.CraftServer.entity.CraftPlayer
        ... 24 more
[15:34:33 WARN]: [TrChat] Plugin TrChat v2.1.2 generated an exception whilst handling plugin message
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/CraftServer/entity/CraftPlayer
        at me.arasple.mc.trchat.api.nms.NMSImpl.sendMessage(NMSImpl.kt:69) ~[?:?]
        at TrChat-2.1.2.jar/me.arasple.mc.trchat.api.impl.BukkitComponentManager.sendComponent(BukkitComponentManager.kt:73) ~[TrChat-2.1.2.jar:?]
        at TrChat-2.1.2.jar/me.arasple.mc.trchat.util.BukkitUtilKt.sendComponent(BukkitUtil.kt:74) ~[TrChat-2.1.2.jar:?]
        at TrChat-2.1.2.jar/me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor.execute(BukkitProxyProcessor.kt:97) ~[TrChat-2.1.2.jar:?]
        at TrChat-2.1.2.jar/me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor$VelocitySide.onPluginMessageReceived(BukkitProxyProcessor.kt:238) ~[TrChat-2.1.2.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleCustomPayload(ServerCommonPacketListenerImpl.java:197) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:26) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:13) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1408) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1415) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-2-b4b8208]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.CraftServer.entity.CraftPlayer
        ... 24 more
[15:34:48 WARN]: [TrChat] Plugin TrChat v2.1.2 generated an exception whilst handling plugin message
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/CraftServer/entity/CraftPlayer
        at me.arasple.mc.trchat.api.nms.NMSImpl.sendMessage(NMSImpl.kt:69) ~[?:?]
        at TrChat-2.1.2.jar/me.arasple.mc.trchat.api.impl.BukkitComponentManager.sendComponent(BukkitComponentManager.kt:73) ~[TrChat-2.1.2.jar:?]
        at TrChat-2.1.2.jar/me.arasple.mc.trchat.util.BukkitUtilKt.sendComponent(BukkitUtil.kt:74) ~[TrChat-2.1.2.jar:?]
        at TrChat-2.1.2.jar/me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor.execute(BukkitProxyProcessor.kt:97) ~[TrChat-2.1.2.jar:?]
        at TrChat-2.1.2.jar/me.arasple.mc.trchat.module.internal.proxy.BukkitProxyProcessor$VelocitySide.onPluginMessageReceived(BukkitProxyProcessor.kt:238) ~[TrChat-2.1.2.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleCustomPayload(ServerCommonPacketListenerImpl.java:197) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:26) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:13) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-2-b4b8208]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.CraftServer.entity.CraftPlayer
        ... 23 more
```

### Server environment

Server version:Paper 1.21
...
Plugin list:
...

**Comment by YuanYuanOwO** [comment]
https://github.com/user-attachments/files/15884557/TrChat-2.1.3.zip

**Comment by HYDeath** [comment]
> https://github.com/user-attachments/files/15884557/TrChat-2.1.3.zip

[22:48:08 ERROR]: Could not pass event PlayerItemHeldEvent to TrChat v2.1.3
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at TrChat-2.1.3.jar/me.arasple.mc.trchat.taboolib.module.ui.ClickListener.onItemHeld(ClickListener.kt:134) ~[TrChat-2.1.3.jar:?]
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
        at TrChat-2.1.3.jar/me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[TrChat-2.1.3.jar:?]
        at TrChat-2.1.3.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[TrChat-2.1.3.jar:?]
        at TrChat-2.1.3.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[TrChat-2.1.3.jar:?]
        at TrChat-2.1.3.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[TrChat-2.1.3.jar:?]
        at TrChat-2.1.3.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[TrChat-2.1.3.jar:?]
        at TrChat-2.1.3.jar/me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[TrChat-2.1.3.jar:?]
        at TrChat-2.1.3.jar/me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[TrChat-2.1.3.jar:?]
        at TrChat-2.1.3.jar/me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[TrChat-2.1.3.jar:?]
        at TrChat-2.1.3.jar/me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[TrChat-2.1.3.jar:?]
        at TrChat-2.1.3.jar/me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[TrChat-2.1.3.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-37-dd49fba]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-37-dd49fba]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-37-dd49fba]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCarriedItem(ServerGamePacketListenerImpl.java:2061) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.handle(ServerboundSetCarriedItemPacket.java:33) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.handle(ServerboundSetCarriedItemPacket.java:15) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1408) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1415) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by CCjun6** [comment]
我也在等1.21

**Comment by HYDeath** [comment]
> 我也在等1.21

他能用，就是会后台报错而已，能用

**Comment by HYDeath** [comment]
> https://github.com/user-attachments/files/15884557/TrChat-2.1.3.zip

能否稍微小小兼容下1.21.1？
![image](https://github.com/user-attachments/assets/261701c7-f71b-4a49-b0ab-6f6a404367e2)

**Comment by ItsFlicker** [comment]
@HYDeath https://github.com/TrPlugins/TrChat/actions/runs/10385139571
