### ISSUE TITLE
[问题] 在重启后的首次进入服务器，会被踢出

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [FlickerProjects/TrChat#424]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

在玩家首次在服务器启动后进入服务器，会被直接踢出，则第二次正常

### 配置文件

```YAML
Options:
  Target: ALL
  Auto-Join: true

Formats:
  - condition: ~
    priority: 100
    msg:
      default-color: '&7'
      hover: '&7聊天时间: %server_time_h:mm:ss a%'
    prefix: 
      world:
        text: '&7[ &e%multiverse_world_alias%&7 ] '
        hover: |-
          &r
          &6▶ &e点击发送传送请求
          &r
        command: '/tpa %player_name%'
      Ch:
        text: '&8&l%tab_replace_eternaltags_tag%'
        command: '/tags'
      player:
        - text: '&a%player_name%'
          hover: |-
            &r
            &e▪  &c生命值: &e%player_health_rounded% ❤
            &r
            &6▶ &e点击发送私聊
            &r
          suggest: '/tell %player_name% '
      part-before-msg:
        text: 
        - '&f：&f{condition: perm "group.vip"}'
        - '&f：&7{condition: perm "group.default"}'
```

### 日志

[11:02:15 INFO]: UUID of player Thexiaoyu is d695da24-caa3-3e06-aa1d-ec5122924d78
[11:02:17 ERROR]: Couldn't place player in world
net.minecraft.ReportedException: Sending packet
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2168) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2146) ~[?:?]
        at net.minecraft.server.players.PlayerList.sendPlayerPermissionLevel(PlayerList.java:1136) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.players.PlayerList.sendPlayerPermissionLevel(PlayerList.java:1121) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.players.PlayerList.sendPlayerPermissionLevel(PlayerList.java:980) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:290) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:595) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1576) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: type cannot be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar:?]
        at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138) ~[P&协议库-ProtocolLib.jar:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126) ~[P&协议库-ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[P&协议库-P
rotocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[P&协议库-Prot
ocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[P&协议库-Pr
otocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[P&协议库-ProtocolL
ib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[P&协议库-ProtocolLib.ja
r:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:442) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:385) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2160) ~[?:?]
        ... 16 more
[11:02:18 INFO]: Thexiaoyu lost connection: Invalid player data
[11:02:19 ERROR]: Could not pass event PlayerQuitEvent to TrChat v2.1.3
java.lang.IllegalStateException: unavailable
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.getDataContainer(DatabaseHandler.kt:57) ~[T&聊天系统-TrChat-2.1.3.jar:?
]
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.getDataContainer(DatabaseHandlerForBukkit.kt:7) ~[T&聊天系统-T
rChat-2.1.3.jar:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData.isVanishing(PlayerData.kt:36) ~[T&聊天系统-TrChat-2.1.3.jar:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData.<init>(PlayerData.kt:20) ~[T&聊天系统-TrChat-2.1.3.jar:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:115) ~[T&聊天系统-TrChat-2.1.3.jar:
?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:114) ~[T&聊天系统-TrChat-2.1.3.jar:
?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData$lambda$0(PlayerData.kt:114) ~[T&聊天系统-TrChat-2.1.3.jar:
?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData(PlayerData.kt:114) ~[T&聊天系统-TrChat-2.1.3.jar:?]
        at me.arasple.mc.trchat.module.display.ChatSession.<init>(ChatSession.kt:115) ~[T&聊天系统-TrChat-2.1.3.jar:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion$getSession$1.invoke(ChatSession.kt:104) ~[T&聊天系统-TrChat-2.1.3.jar:?
]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion$getSession$1.invoke(ChatSession.kt:104) ~[T&聊天系统-TrChat-2.1.3.jar:?
]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion.getSession$lambda$0(ChatSession.kt:104) ~[T&聊天系统-TrChat-2.1.3.jar:?
]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion.getSession(ChatSession.kt:104) ~[T&聊天系统-TrChat-2.1.3.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.quit(Channel.kt:303) ~[T&聊天系统-TrChat-2.1.3.jar:?]
        at me.arasple.mc.trchat.module.display.channel.Channel$Companion.quit$default(Channel.kt:284) ~[T&聊天系统-TrChat-2.1.3.jar:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion.removeSession(ChatSession.kt:108) ~[T&聊天系统-TrChat-2.1.3.jar:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerQuit.onQuit(ListenerQuit.kt:24) ~[T&聊天系统-TrChat-2.1.3.jar:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[T&聊天系统-TrChat-2.1.3.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[T&聊天系统-TrChat-2.1.3.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[T&聊天系统-TrChat-2.1.3.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[T&聊天系统-TrChat-2.1.3.ja
r:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[T&聊天系统-TrChat-2.1.3.ja
r:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[T&聊天系统-Tr
Chat-2.1.3.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[T&聊天系统-Tr
Chat-2.1.3.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[T&聊天系统-TrCha
t-2.1.3.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[T&聊天系统-TrCha
t-2.1.3.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[T&聊天系统-TrChat-2.1.3.jar:
?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-55
0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:592) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:577) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2121) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2100) ~[?:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:796) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1576) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:02:19 INFO]: VIP > Thexiaoyu 悄悄的离开了单方块生存!

### 服务器环境

服务器版本: This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 48336
8e on ver/1.19.4)
...
插件列表:
[11:07:02 INFO]: Server Plugins (100):
[11:07:02 INFO]: Paper Plugins:
[11:07:02 INFO]:  - WolfyUtilities
[11:07:02 INFO]: Bukkit Plugins:
[11:07:02 INFO]:  - AlchimiaVitae, ArmorPlaceholders, AttributePlus, BeautyQuests, BeeHivesTrees, BentoBox, BentoBox-AOneBlock, BentoBox-Isl
andFly, BentoBox-Level, BentoBox-MagicCobblestoneGenerator
[11:07:02 INFO]:  BentoBox-Warps, BetterReactor, Bump, ChocoHills, Citizens, CMI, CMILib, CoreProtect, CropsPlus, *Ddog-Api-Command
[11:07:02 INFO]:  DeathMessages, DeluxeMenus, DynaTech, EcoPower, enchantlevelLimit, EnchantLimit, EternalTags, ExoticGarden, ExtraGear, flo
odgate
[11:07:02 INFO]:  FluffyMachines, FNAmplifications, FoxyMachines, Gastronomicon, GeekMail-Pro, GeneticChickengineering, GrimAC, GuizhanLibPl
ugin, HolographicDisplays, HoloMobHealth
[11:07:02 INFO]:  *HotkeyCommand, Images, InfernalExpansion, InfinityExpansion, InteractionVisualizer, IronElevators, JoinPlugin, LagAssist,
 LegendarySevenDayGift, LevelledMobs
[11:07:02 INFO]:  LibsDisguises, LiteSignIn, LiteXpansion, LootConomy, LuckPerms, Matrix, MineResetLite, MobCapturer, Multiverse-Core, Netwo
rks
[11:07:02 INFO]:  NexEngine, PlaceholderAPI, PlugManX, ProtocolLib, Quaptics, QuickShop, RealisticSeasons, RykenSlimefunCustomizer, SellChao
ji, Shopkeepers
[11:07:02 INFO]:  SimpleUtils, SkinsRestorer, SkyDream, SlimeCustomizer, Slimefun, SlimeGlue, SlimyRepair, spark, SunSTCore, SuperLobby
[11:07:02 INFO]:  Supreme, TAB, TileDataSaver, TranscEndence, TrChat, UltimateTimber, UpgradeableHoppers, Vault, ViaBackwards, ViaRewind
[11:07:02 INFO]:  ViaVersion, VillagerUtil, VoidGen, WkKit, WorldBorderAPI, WorldEdit, WorldGuard, XConomy, XenoWorldReset
...

**Comment by ItsFlicker** [comment]
测试一下删除trchat还会不会出现

**Comment by Thexiaoyuqaq** [comment]
> 测试一下删除trchat还会不会出现

并不会出现，删除后一切正常

**Comment by ItsFlicker** [comment]
关闭settings.yml的Options.Use-Packets

**Comment by Thexiaoyuqaq** [comment]
> 关闭settings.yml的Options.Use-Packets

关闭Options.Use-Packets后
java.lang.IllegalStateException: unavailable依旧存在

**Comment by Thexiaoyuqaq** [comment]
> > 关闭settings.yml的Options.Use-Packets
> 
> 关闭Options.Use-Packets后 java.lang.IllegalStateException: unavailable依旧存在

并且玩家被踢出问题依旧存在

**Comment by huanli233** [comment]
同样的问题

**Comment by Thexiaoyuqaq** [comment]
小雨已收到你的来信已存放至小雨的收件箱

**Comment by Thexiaoyuqaq** [comment]
> 引用到

我这里尝试了很多方法，好像删除libraries让库重新生成似乎可行
并把sqlite的db存储删掉

只不过现在有的问题是 物品展示 有时 出现 物品描述 变成石头 和 at无法使用

**Comment by Thexiaoyuqaq** [comment]
小雨已收到你的来信已存放至小雨的收件箱
