### ISSUE TITLE
[问题] TrChat-2.2.0-beta在Velocity上报错

### ISSUE THREAD

**Issue by CatTeaA** [FlickerProjects/TrChat#428]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

安装

### 配置文件

```YAML
默认
```

### 日志

```log
[03:22:49 ERROR]: [TabooLib] Failed to initialize primitive loader, the plugin "TrChat-2.2.0-beta1.jar" will be disabled!
[03:22:49 ERROR]: Can't create plugin trchat
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: ExceptionInInitializerError
  at VelocityPlugin.<init>(VelocityPlugin.java:68)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating VelocityPlugin

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
VelocityPlugin:              "me.arasple.mc.trchat.taboolib.platform.VelocityPlugin"
VelocityPluginModule:        "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:131) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:168) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:362) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:239) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
Caused by: java.lang.ExceptionInInitializerError
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$46094b.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$46094b.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	... 6 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.init(IsolatedClassLoader.java:30) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.<clinit>(VelocityPlugin.java:46) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$46094b.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$46094b.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.init(IsolatedClassLoader.java:28) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.<clinit>(VelocityPlugin.java:46) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$46094b.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$46094b.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	... 6 more
Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/commons/Remapper
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.findClassOrNull(IsolatedClassLoader.java:121) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:103) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:85) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at me.lucko.jarrelocator.JarRelocator.<init>(JarRelocator.java:57) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.loadFile(PrimitiveLoader.java:209) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.load(PrimitiveLoader.java:149) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.init(PrimitiveLoader.java:104) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.init(IsolatedClassLoader.java:28) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.<clinit>(VelocityPlugin.java:46) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$46094b.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$46094b.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.commons.Remapper
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:110) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:85) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.findClassOrNull(IsolatedClassLoader.java:121) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:103) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:85) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at me.lucko.jarrelocator.JarRelocator.<init>(JarRelocator.java:57) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.loadFile(PrimitiveLoader.java:209) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.load(PrimitiveLoader.java:149) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.init(PrimitiveLoader.java:104) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.init(IsolatedClassLoader.java:28) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.<clinit>(VelocityPlugin.java:46) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$46094b.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$46094b.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
	... 6 more
```

### 服务器环境

velocity-3.3.0-SNAPSHOT-415

**Comment by ItsFlicker** [comment]
velocity上先用旧版本吧

**Comment by CatTeaA** [comment]
> velocity上先用旧版本吧

Velocity用旧版本的trchat，跟1.21.1子服务器上的新版trchat，当双方版本不一致，会不会出现不兼容的情况

**Comment by ItsFlicker** [comment]
不会

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/10869239536
