### ISSUE TITLE
玩家加入/离开服务器报错

### ISSUE THREAD

**Issue by williambacteria** [FlickerProjects/TrChat#43]
服务端版本：PaperSpigot-377
触发方式：玩家加入/离开服务器时
报错内容：
[20:14:26 WARN]: java.lang.NoSuchFieldException: playerConnection at class net.minecraft.server.level.EntityPlayer
[20:14:26 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.get(Reflex.kt:60)
[20:14:26 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.read(Reflex.kt:25)
[20:14:26 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:128)
[20:14:26 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:124)
[20:14:26 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:29)
[20:14:26 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.addPlayerChannel$lambda-0(ChannelExecutor.kt:36)
[20:14:26 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor$$Lambda$7201/0x00000000047e6d70.run(Unknown Source)
[20:14:26 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[20:14:26 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[20:14:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:14:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:14:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:884)

**Comment by radiation-chan** [comment]
一样的情况，我的是PAPER 1.18.1

**Comment by ItsFlicker** [comment]
请更新到1.90-R5
