### ISSUE TITLE
[issue] 一个错误导致插件无法正常使用  1

### ISSUE THREAD

**Issue by uouiiu** [FlickerProjects/TrChat#433]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

[20:33:03 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.2.0-beta1
java.lang.IllegalStateException: unavailable
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.getDataContainer(DatabaseHandler.kt:57) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.getDataContainer(DatabaseHandlerForBukkit.kt:7) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.internal.data.PlayerData.isVanishing(PlayerData.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.internal.data.PlayerData.<init>(PlayerData.kt:20) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:115) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:114) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData$lambda$0(PlayerData.kt:114) ~[TrChat-2.2.0-beta1.jar:?]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData(PlayerData.kt:114) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.display.ChatSession.<init>(ChatSession.kt:115) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.display.ChatSession$Companion$getSession$1.invoke(ChatSession.kt:104) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.display.ChatSession$Companion$getSession$1.invoke(ChatSession.kt:104) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.display.ChatSession$Companion.getSession$lambda$0(ChatSession.kt:104) ~[TrChat-2.2.0-beta1.jar:?]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.display.ChatSession$Companion.getSession(ChatSession.kt:104) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:53) ~[TrChat-2.2.0-beta1.jar:?]
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:109) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:107) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:57) ~[TrChat-2.2.0-beta1.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2286-366af80]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2414) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2530) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$13(ServerGamePacketListenerImpl.java:2186) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### configuration file

```YAML
prefix:
      world:
        text: '%playerTitle_use% %player_displayname%'
        hover: |-
          &f
          &8▪ &7Location: &3%player_world%&7, &2%player_x%/%player_y%/%player_z%
          &f
          &6▶ &eClick here to send a teleport request
          &f
        command: '/tpa %player_name%'


把text的变量换成这俩个，然后重启服务器就会出现这种错误
```

### logs

1111111111111111111111111111

### Server environment

Server version:
...purpur 1.21.1
Plugin list:
...TrChat-2.2.0-beta1
 1

**Comment by ItsFlicker** [comment]
数据库未初始化
