### ISSUE TITLE
[issue] Could not pass event AsyncPlayerChatEvent to TrChat v2.2.0-beta1

### ISSUE THREAD

**Issue by hed516** [FlickerProjects/TrChat#437]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.2.0-beta1
java.lang.NoSuchMethodError: 'java.lang.String dev.lone.itemsadder.api.FontImages.FontImageWrapper.replaceFontImages(org.bukkit.entity.Player, java.lang.String)'
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.internal.hook.impl.HookItemsAdder.replaceFontImages(HookItemsAdder.kt:20) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.display.format.MsgComponent.createComponent(MsgComponent.kt:25) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:152) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:48) ~[TrChat-2.2.0-beta1.jar:?]
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:109) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:107) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:57) ~[TrChat-2.2.0-beta1.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-57-b483da4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2406) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2522) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$9(ServerGamePacketListenerImpl.java:2178) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[18:19:56 ERROR]: Failed to request yggdrasil public key
com.mojang.authlib.exceptions.MinecraftClientException: Failed to read from https://api.minecraftservices.com/publickeys due to Connect timed out
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:108) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo.fetch(YggdrasilServicesKeyInfo.java:114) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo$1.run(YggdrasilServicesKeyInfo.java:89) ~[authlib-6.0.54.jar:?]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[?:?]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.base/java.net.Socket.connect(Socket.java:751) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531) ~[?:?]
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636) ~[?:?]
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:?]
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377) ~[?:?]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1282) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123) ~[?:?]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599) ~[?:?]
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531) ~[?:?]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307) ~[?:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:84) ~[authlib-6.0.54.jar:?]
        ... 9 more

### configuration file

```YAML
ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.2.0-beta1
java.lang.NoSuchMethodError: 'java.lang.String dev.lone.itemsadder.api.FontImages.FontImageWrapper.replaceFontImages(org.bukkit.entity.Player, java.lang.String)'
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.internal.hook.impl.HookItemsAdder.replaceFontImages(HookItemsAdder.kt:20) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.display.format.MsgComponent.createComponent(MsgComponent.kt:25) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:152) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:48) ~[TrChat-2.2.0-beta1.jar:?]
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:109) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:107) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:57) ~[TrChat-2.2.0-beta1.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-57-b483da4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2406) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2522) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$9(ServerGamePacketListenerImpl.java:2178) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[18:19:56 ERROR]: Failed to request yggdrasil public key
com.mojang.authlib.exceptions.MinecraftClientException: Failed to read from https://api.minecraftservices.com/publickeys due to Connect timed out
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:108) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo.fetch(YggdrasilServicesKeyInfo.java:114) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo$1.run(YggdrasilServicesKeyInfo.java:89) ~[authlib-6.0.54.jar:?]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[?:?]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.base/java.net.Socket.connect(Socket.java:751) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531) ~[?:?]
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636) ~[?:?]
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:?]
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377) ~[?:?]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1282) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123) ~[?:?]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599) ~[?:?]
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531) ~[?:?]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307) ~[?:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:84) ~[authlib-6.0.54.jar:?]
        ... 9 more
```

### logs

ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.2.0-beta1
java.lang.NoSuchMethodError: 'java.lang.String dev.lone.itemsadder.api.FontImages.FontImageWrapper.replaceFontImages(org.bukkit.entity.Player, java.lang.String)'
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.internal.hook.impl.HookItemsAdder.replaceFontImages(HookItemsAdder.kt:20) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.display.format.MsgComponent.createComponent(MsgComponent.kt:25) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:152) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:48) ~[TrChat-2.2.0-beta1.jar:?]
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:109) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:107) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[TrChat-2.2.0-beta1.jar:?]
        at TrChat-2.2.0-beta1.jar/me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:57) ~[TrChat-2.2.0-beta1.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-57-b483da4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2406) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2522) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$9(ServerGamePacketListenerImpl.java:2178) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[18:19:56 ERROR]: Failed to request yggdrasil public key
com.mojang.authlib.exceptions.MinecraftClientException: Failed to read from https://api.minecraftservices.com/publickeys due to Connect timed out
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:108) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo.fetch(YggdrasilServicesKeyInfo.java:114) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo$1.run(YggdrasilServicesKeyInfo.java:89) ~[authlib-6.0.54.jar:?]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[?:?]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.base/java.net.Socket.connect(Socket.java:751) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531) ~[?:?]
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636) ~[?:?]
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:?]
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377) ~[?:?]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1282) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123) ~[?:?]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599) ~[?:?]
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531) ~[?:?]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307) ~[?:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:84) ~[authlib-6.0.54.jar:?]
        ... 9 more

### Server environment

Server version:1.21.1
...
Plugin list: itemsadder trhcat
...

**Comment by ItsFlicker** [comment]
已修复
