### ISSUE TITLE
[问题] Velocity插件加载失败：org/objectweb/asm/commons/Remapper类未找到

### ISSUE THREAD

**Issue by zyramystic** [FlickerProjects/TrChat#438]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

1. 启动Velocity
2. 安装TrChat v2.2.0-Beta2 (Git-b2a485e) (https://github.com/TrPlugins/TrChat/actions/runs/10752455117)
3. 报错

### 配置文件

```YAML
第一次启动就报错 没有生成配置文件
```

### 日志

[20:41:53] [main/ERROR] [TrChat-2.2.0-beta2]: Failed to initialize primitive loader, the plugin "TrChat-2.2.0-beta2" will be disabled!
[20:41:53] [main/ERROR] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Can't create plugin trchat
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: ExceptionInInitializerError
  at VelocityPlugin.<init>(VelocityPlugin.java:64)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating VelocityPlugin

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
VelocityPlugin:              "me.arasple.mc.trchat.taboolib.platform.VelocityPlugin"
VelocityPluginModule:        "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:131) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:168) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:362) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:239) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
Caused by: java.lang.ExceptionInInitializerError
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$1744c58.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$1744c58.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	... 6 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.init(IsolatedClassLoader.java:30) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.lambda$static$0(VelocityPlugin.java:46) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.<clinit>(VelocityPlugin.java:43) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$1744c58.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$1744c58.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.init(IsolatedClassLoader.java:28) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.lambda$static$0(VelocityPlugin.java:46) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.<clinit>(VelocityPlugin.java:43) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$1744c58.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$1744c58.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	... 6 more
Caused by: java.lang.IllegalStateException: java.lang.NoClassDefFoundError: org/objectweb/asm/commons/Remapper
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.load(PrimitiveLoader.java:154) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.lambda$init$0(PrimitiveLoader.java:104) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.init(PrimitiveLoader.java:95) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.init(IsolatedClassLoader.java:28) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.lambda$static$0(VelocityPlugin.java:46) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.<clinit>(VelocityPlugin.java:43) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$1744c58.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$1744c58.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	... 6 more
Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/commons/Remapper
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.findClassOrNull(IsolatedClassLoader.java:122) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:104) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:86) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at me.lucko.jarrelocator.JarRelocator.<init>(JarRelocator.java:57) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.loadFile(PrimitiveLoader.java:221) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.load(PrimitiveLoader.java:152) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.lambda$init$0(PrimitiveLoader.java:104) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.init(PrimitiveLoader.java:95) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.init(IsolatedClassLoader.java:28) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.lambda$static$0(VelocityPlugin.java:46) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.<clinit>(VelocityPlugin.java:43) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$1744c58.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$1744c58.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.commons.Remapper
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:111) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:86) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.findClassOrNull(IsolatedClassLoader.java:122) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:104) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:86) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at me.lucko.jarrelocator.JarRelocator.<init>(JarRelocator.java:57) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.loadFile(PrimitiveLoader.java:221) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.load(PrimitiveLoader.java:152) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.lambda$init$0(PrimitiveLoader.java:104) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.PrimitiveLoader.init(PrimitiveLoader.java:95) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.classloader.IsolatedClassLoader.init(IsolatedClassLoader.java:28) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.lambda$static$0(VelocityPlugin.java:46) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin.<clinit>(VelocityPlugin.java:43) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$1744c58.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.VelocityPlugin$$FastClassByGuice$$1744c58.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[Velocity.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
	... 6 more

### 服务器环境

服务器版本:
Velocity 3.3.0-SNAPSHOT (git-6100e675-b416)
插件列表:
floodgate,Geyser,TrChat

**Comment by zyramystic** [comment]
找到同Issue 故关闭
