### ISSUE TITLE
[问题] TrChat-2.2.0-beta3在folia1.21.1中无法初始化

### ISSUE THREAD

**Issue by Hiddenmn** [FlickerProjects/TrChat#442]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

使用folia1.21.1核心同时装入TrChat-2.2.0-beta3，然后启动

### 配置文件

```YAML
没有生成trchat文件夹
```

### 日志

[22:25:32] [ServerMain/INFO]: [bootstrap] Running Java 22 (OpenJDK 64-Bit Server VM 22.0.1+8; Azul Systems, Inc. Zulu22.30+13-CA) on Windows 10 10.0 (amd64)
[22:25:32] [ServerMain/INFO]: [bootstrap] Loading Folia 1.21.1-DEV-master@9a19e42 (2024-08-31T12:16:29Z) for Minecraft 1.21.1
[22:25:33] [ServerMain/INFO]: [PluginInitializerManager] Initializing plugins...
[22:25:33] [ServerMain/INFO]: [PluginInitializerManager] Initialized 2 plugins
[22:25:33] [ServerMain/INFO]: [PluginInitializerManager] Bukkit plugins (2):
 - PlaceholderAPI (2.11.7-DEV-null), TrChat (2.2.0-beta3)
[22:25:37] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[22:25:38] [ServerMain/INFO]: Loaded 1290 recipes
[22:25:39] [ServerMain/INFO]: Loaded 1399 advancements
[22:25:39] [Server thread/INFO]: Starting minecraft server version 1.21.1
[22:25:39] [Server thread/INFO]: Loading properties
[22:25:39] [Server thread/INFO]: This server is running Folia version 1.21.1-DEV-master@9a19e42 (2024-08-31T12:16:29Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
[22:25:40] [Server thread/INFO]: [spark] This server bundles the spark profiler. For more information please visit https://docs.papermc.io/paper/profiling
[22:25:40] [Server thread/INFO]: Using 4 threads for Netty based IO
[22:25:40] [Server thread/INFO]: Server Ping Player Sample Count: 12
[22:25:40] [Server thread/WARN]: [!] The timings system cannot be enabled on Folia, and has been scheduled for removal from Paper in the future.
    We recommend migrating to the spark profiler.
    For more information please visit: https://github.com/PaperMC/Paper/discussions/10565
[22:25:40] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and population gen parallelism of 3 threads
[22:25:40] [Server thread/INFO]: [io.papermc.paper.threadedregions.TickRegions] Regionised ticking is enabled with 1 tick threads
[22:25:40] [Server thread/INFO]: Default game type: SURVIVAL
[22:25:40] [Server thread/INFO]: Generating keypair
[22:25:40] [Server thread/INFO]: Starting Minecraft server on *:25565
[22:25:40] [Server thread/INFO]: Using default channel type
[22:25:40] [Server thread/INFO]: Paper: Using Java compression from Velocity.
[22:25:40] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[22:25:41] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'TrChat-2.2.0-beta3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:129) ~[folia-1.21.1.jar:1.21.1-DEV-9a19e42]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[folia-1.21.1.jar:1.21.1-DEV-9a19e42]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[folia-1.21.1.jar:1.21.1-DEV-9a19e42]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[folia-1.21.1.jar:1.21.1-DEV-9a19e42]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[folia-1.21.1.jar:1.21.1-DEV-9a19e42]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:552) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[folia-1.21.1.jar:1.21.1-DEV-9a19e42]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281) ~[folia-1.21.1.jar:1.21.1-DEV-9a19e42]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:357) ~[folia-1.21.1.jar:1.21.1-DEV-9a19e42]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:12) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:10) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/kotlin1822.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.getHandleGetter(JavaClassField.kt:10) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.get(JavaClassField.kt:31) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.library.reflex.ClassField.get$default(ClassField.kt:13) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getInstance(ReflexClass.kt:84) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getInstance(ReflexClass.kt:65) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.common.platform.PlatformFactory.init$lambda$5(PlatformFactory.kt:68) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.common.TabooLib$2.run(TabooLib.java:113) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:80) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.common.TabooLib.lifeCycle(TabooLib.java:73) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.lambda$static$0(BukkitPlugin.java:48) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:35) ~[TrChat-2.2.0-beta3.jar:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[folia-1.21.1.jar:1.21.1-DEV-9a19e42]
	... 9 more
Caused by: java.lang.IllegalStateException: Unsafe not found
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.library.reflex.UnsafeAccess.<clinit>(UnsafeAccess.kt:34) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:12) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:10) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/kotlin1822.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.getHandleGetter(JavaClassField.kt:10) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.library.reflex.JavaClassField.get(JavaClassField.kt:31) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.library.reflex.ClassField.get$default(ClassField.kt:13) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getInstance(ReflexClass.kt:84) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.library.reflex.ReflexClass.getInstance(ReflexClass.kt:65) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.common.platform.PlatformFactory.init$lambda$5(PlatformFactory.kt:68) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.common.TabooLib$2.run(TabooLib.java:113) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:80) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.common.TabooLib.lifeCycle(TabooLib.java:73) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.lambda$static$0(BukkitPlugin.java:48) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[TrChat-2.2.0-beta3.jar:?]
	at TrChat-2.2.0-beta3.jar/me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:35) ~[TrChat-2.2.0-beta3.jar:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[folia-1.21.1.jar:1.21.1-DEV-9a19e42]
	... 9 more
[22:25:41] [Server thread/INFO]: [PlaceholderAPI] Loading server plugin PlaceholderAPI v2.11.7-DEV-null
[22:25:41] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[22:25:41] [Server thread/INFO]: Preparing level "world"
[22:25:42] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[22:25:42] [Server thread/INFO]: Time elapsed: 1 ms
[22:25:42] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[22:25:42] [Server thread/INFO]: Time elapsed: 0 ms
[22:25:42] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[22:25:42] [Server thread/INFO]: Time elapsed: 0 ms
[22:25:42] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.7-DEV-null
[22:25:43] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[22:25:43] [Server thread/INFO]: [spark] The spark plugin has been preferred but was not loaded. The bundled spark profiler will enabled instead.
[22:25:43] [Server thread/INFO]: [spark] The spark profiler will not be enabled because it is currently disabled in the configuration.
[22:25:43] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[22:25:43] [Server thread/INFO]: 0 placeholder hook(s) registered!
[22:25:43] [Server thread/INFO]: Done preparing level "world" (1.249s)
[22:25:43] [Server thread/INFO]: Done (3.788s)! For help, type "help"
[22:25:43] [Region Scheduler Thread #0/INFO]: Initialising world 'world' before it can be ticked...
[22:25:43] [Region Scheduler Thread #0/INFO]: Initialised world 'world'
[22:25:43] [Region Scheduler Thread #0/INFO]: Timings Reset
[22:25:43] [Region Scheduler Thread #0/INFO]: Initialising world 'world_nether' before it can be ticked...
[22:25:43] [Region Scheduler Thread #0/INFO]: Initialised world 'world_nether'
[22:25:43] [Region Scheduler Thread #0/INFO]: Initialising world 'world_the_end' before it can be ticked...
[22:25:43] [Region Scheduler Thread #0/INFO]: Initialised world 'world_the_end'
[22:27:09] [Region Scheduler Thread #0/INFO]: Checking version, please wait...
[22:27:10] [Thread-6/INFO]: This server is running Folia version 1.21.1-DEV-master@9a19e42 (2024-08-31T12:16:29Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-2300-49db849 (MC: 1.21.1)
[22:27:30] [Region Scheduler Thread #0/INFO]: Server Plugins (2):
[22:27:30] [Region Scheduler Thread #0/INFO]: Bukkit Plugins:
[22:27:30] [Region Scheduler Thread #0/INFO]:  - PlaceholderAPI, TrChat
[22:27:58] [Region Scheduler Thread #0/INFO]: Stopping the server
[22:27:58] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[22:27:58] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[22:27:58] [Region shutdown thread/INFO]: Stopping server
[22:27:58] [Region shutdown thread/INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.11.7-DEV-null
[22:27:58] [Region shutdown thread/INFO]: [RegionShutdownThread] Halting chunk systems
[22:27:58] [Region shutdown thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[22:27:58] [Region shutdown thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[22:27:58] [Region shutdown thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[22:27:58] [Region shutdown thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[22:27:58] [Region shutdown thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[22:27:58] [Region shutdown thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[22:27:58] [Region shutdown thread/INFO]: [RegionShutdownThread] Halted chunk systems
[22:27:58] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving chunks around region around chunk [0, 0] in world 'world'
[22:27:58] [Region shutdown thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[22:27:58] [Region shutdown thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[22:27:58] [Region shutdown thread/INFO]: [ChunkHolderManager] Saved 49 block chunks, 49 entity chunks, 0 poi chunks in world 'world' in 0.23s
[22:27:58] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving chunks around region around chunk [0, 0] in world 'world_nether'
[22:27:58] [Region shutdown thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[22:27:58] [Region shutdown thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[22:27:58] [Region shutdown thread/INFO]: [ChunkHolderManager] Saved 49 block chunks, 49 entity chunks, 0 poi chunks in world 'world_nether' in 0.10s
[22:27:58] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving chunks around region around chunk [0, 0] in world 'world_the_end'
[22:27:58] [Region shutdown thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[22:27:58] [Region shutdown thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[22:27:59] [Region shutdown thread/INFO]: [ChunkHolderManager] Saved 49 block chunks, 49 entity chunks, 0 poi chunks in world 'world_the_end' in 0.07s
[22:27:59] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving players

### 服务器环境

服务器版本:
1.21.1-2300-49db849 (MC: 1.21.1)
插件列表:
Server Plugins (2):
Bukkit Plugins:
 - PlaceholderAPI, TrChat

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/10979411611
