### ISSUE TITLE
[问题] 我把物品放入铁砧内他后台就报错

### ISSUE THREAD

**Issue by orange1184258252** [FlickerProjects/TrChat#444]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

我把物品放入铁砧内他后台就报错

### 配置文件

```YAML
无
```

### 日志

[19:31:40] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to TrChat v2.1.0
java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.setDisplayNameComponent([Lnet/md_5/bungee/api/chat/BaseComponent;)V
	at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:51) ~[?:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:42) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.util.ItemModifierKt.modifyMeta(ItemModifier.kt:44) ~[?:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange.onAnvilCraft(ListenerAnvilChange.kt:42) ~[?:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:1.8.0_411]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1015) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.ContainerAnvil.e(ContainerAnvil.java:296) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.ContainerAnvil.a(ContainerAnvil.java:109) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.ContainerAnvil$1.update(ContainerAnvil.java:20) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.Slot.f(SourceFile:84) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.Slot.set(SourceFile:80) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.Container.a(Container.java:274) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1899) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_411]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_411]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_411]
[19:31:40] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to TrChat v2.1.0
java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.setDisplayNameComponent([Lnet/md_5/bungee/api/chat/BaseComponent;)V
	at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:51) ~[?:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange$onAnvilCraft$1.invoke(ListenerAnvilChange.kt:42) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.util.ItemModifierKt.modifyMeta(ItemModifier.kt:44) ~[?:?]
	at me.arasple.mc.trchat.module.internal.listener.ListenerAnvilChange.onAnvilCraft(ListenerAnvilChange.kt:42) ~[?:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:1.8.0_411]
	at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1015) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.ContainerAnvil.e(ContainerAnvil.java:296) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.ContainerAnvil.a(ContainerAnvil.java:109) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.ContainerAnvil$1.update(ContainerAnvil.java:20) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.Slot.f(SourceFile:84) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.Container.a(Container.java:321) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1899) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_411]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_411]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_411]

### 服务器环境

服务器版本:
1.12.2- spigot
插件列表:
FileListener, AttackSpeedRemover, AntiBoat, PlugMan, DreamDelayCmd, PlayerTpPlayer, LuckPerms, LiteItemShow, VoidGen, FyTrash, XinxinBotApi, EssentialsPowerExp, Sell, AnCDK, Fgive, ProtocolLib, AckmanLoader, MCCore, FantaLib1.12, ChineseCommand, ReNoPlayerCommand, JulyLibrary, XinxinAutoReview, Law, ZombieNoBurn, PlaceholderAPI, MinePay, WorldCommandBlock, Friends3_0, EClean, GuoItemLoreCommand, TrChat, WzAwakening, BlueBossChallenge, DreamAntiFly, WorldEdit, DecentHolograms, CrazyAuctionsPlus, bAnnouncer, EP-WorldNotInteract, ILoreEdit, ItemControl, Adyeshach, LegendMaid, PlugManX, Vault, DragonChatBubble, DogHook, Chemdah, XinxinCustomMessage, XinxinBindKit, GemsPAPI, AkariCDK, HolographicDisplays, PackPlaceholderAPI, PlayerPoints, GrScriptBlock, ChestCommands, DreamBind, PuerkasMarriage, DreamPoints, CowMonthCard, BilibiliVideo, CMILib, LiteSignIn, LiteInvitation, TAB, XinxinApi, OhTheWorld, CrazyCrates, XinxinBotShop, Fsell, GPS, JBank, PlotSquared, WorldGuard, Dantiao, RenameCard, WorldEditSUI, Essentials, TrMenu, MakeWishX-personal, PlayerInv, JulyGuild, Multiverse-Core, EWarp, QuickShop, AutoSpawnWorld, EssentialsProtect, DragonGPS, EssentialsSpawn, KeepInventory, Residence, AuthMe, MythicMobs, TradeMe, DreamRobot, LootChest, DungeonPlus, UltimateChairs, DragonArmourers, SkillAPI, FivePlanetSpawn, MythicMobsExtension, AkariLevel, AttributePlus, DreamSpawners, MythicAnimatorStands, AzureFlow, AP-Potion, MonsterManual, MythicArtifacts, AP-CowAttribute, MythicAttributePlaceholder, DreamShowcase, SimpleLib, DragonInventory, RuomoeCore, DreamCountdown, AttributeCompatibleAPI, DragonCore, D-AttSuit, FlameTabInfo, DragonAreaSound, DragonInteract, StarLibrary, SpawnProtect, DragonRide, RotateAnimation, DragonAnimation, DragonActivity, D-command, AttributePotion, DrFlyingSword, SenCore, LegendCore, LegendStrengthen, LegendCollapse, LegendPets, DreamAction, RuomoeMap, BukkitLibrary, StarCombatPro, StarTraders, StarKit, StarTaskView, StarTeam, StarSkillViewDrive, GDDPRevive

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/10979411611
