### ISSUE TITLE
无法加载插件

### ISSUE THREAD

**Issue by XiaoShuaiOwO** [FlickerProjects/TrChat#448]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

服务器环境为1.12.2 Catserver
使用TrChat-2.1.0时，无法生成配置文件，且插件无法加载
`[Server thread/ERROR]: Could not load 'plugins\TrChat-2.1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[JavaPluginLoader.class:git-CatServer-1.12.2-090a6ffb]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[SimplePluginManager.class:git-CatServer-1.12.2-090a6ffb]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [SimplePluginManager.class:git-CatServer-1.12.2-090a6ffb]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:359) [CraftServer.class:git-CatServer-1.12.2-090a6ffb]
        at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:340) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:330) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-090a6ffb]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-090a6ffb]
        ... 7 more
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.AnnotationTypeMismatchExceptionProxy
        at sun.reflect.annotation.AnnotationParser.parseEnumArray(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.annotation.AnnotationParser.parseArray(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.annotation.AnnotationParser.parseAnnotation2(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(Unknown Source) ~[?:1.8.0_281]
        at java.lang.Class.createAnnotationData(Unknown Source) ~[?:1.8.0_281]
        at java.lang.Class.annotationData(Unknown Source) ~[?:1.8.0_281]
        at java.lang.Class.getAnnotation(Unknown Source) ~[?:1.8.0_281]
        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.checkPlatform(VisitorHandler.java:193) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.getClasses(VisitorHandler.java:179) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:74) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.lambda$init$0(VisitorHandler.java:42) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLib$1.run(TabooLib.java:79) ~[?:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_281]
        at me.arasple.mc.trchat.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56) ~[?:?]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_281]
        at me.arasple.mc.trchat.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:53) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-090a6ffb]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-090a6ffb]
        ... 7 more`

使用TrChat-2.1.3时，可以生成配置文件，但依旧无法加载插件
`Error occurred while enabling TrChat v2.1.3 (Is it up to date?)
java.lang.ArrayStoreException: sun.reflect.annotation.AnnotationTypeMismatchExceptionProxy
        at sun.reflect.annotation.AnnotationParser.parseEnumArray(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.annotation.AnnotationParser.parseArray(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.annotation.AnnotationParser.parseAnnotation2(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(Unknown Source) ~[?:1.8.0_281]
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(Unknown Source) ~[?:1.8.0_281]
        at java.lang.Class.createAnnotationData(Unknown Source) ~[?:1.8.0_281]
        at java.lang.Class.annotationData(Unknown Source) ~[?:1.8.0_281]
        at java.lang.Class.getAnnotation(Unknown Source) ~[?:1.8.0_281]
        at java.lang.reflect.AnnotatedElement.isAnnotationPresent(Unknown Source) ~[?:1.8.0_281]
        at java.lang.Class.isAnnotationPresent(Unknown Source) ~[?:1.8.0_281]
        at me.arasple.mc.trchat.module.display.function.Function$Companion.reload(Function.kt:42) ~[?:?]
        at me.arasple.mc.trchat.module.conf.Loader.loadFunctions(Loader.kt:209) ~[?:?]
        at me.arasple.mc.trchat.module.conf.Loader.loadFunctions(Loader.kt:191) ~[?:?]
        at me.arasple.mc.trchat.module.conf.file.Functions.init$lambda$0(Functions.kt:33) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.configuration.ConfigFile.loadFromFile(ConfigFile.kt:51) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.configuration.ConfigFile.reload(ConfigFile.kt:78) ~[?:?]
        at me.arasple.mc.trchat.module.internal.TrChatBukkit.reload(TrChatBukkit.kt:81) ~[?:?]
        at me.arasple.mc.trchat.module.internal.TrChatBukkit.onEnable(TrChatBukkit.kt:65) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:88) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-090a6ffb]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-090a6ffb]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-090a6ffb]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:438) [CraftServer.class:git-CatServer-1.12.2-090a6ffb]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServer-1.12.2-090a6ffb]
        at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:383) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:330) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]`

### 配置文件

```YAML
默认配置文件
```

### 服务器环境

服务器版本:
This server is running CatServer version git-CatServer-1.12.2-090a6ffb (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)
插件列表:
Plugins (115): XsNoRefineInAnvil, BossCooling, AntiExplosion, FileListener, GiveItem, ExpController, Stp, MythicLib, PlugMan, WeatherTimeLock, FarmProtect, ConsoleSpamFix, XsGiveitem, EntitySearch, AntiItemRepeatedRnchanting, NBTAPI, LuckPerms, VoidGen, PlayerDataSQL, AloneOpenGui, Ae2Fix, NBTEditPanel, BanItemList, WashEnchanting, IronElevators, LaggRemover, ProtocolLib, antijei, ImageOnMap, XsKeepFoodSaturation, NBTLibrary, DelayUnloadChunk, CalendarEvents, tpbd, ErrorFixer, BladePlus, InfoQuery, PlaceholderAPI, UltimateAutoRestart, tpLogin, FixPrimordialPearl, Sudo, TrChat, BanItem, AntiLoop, BanSA, CoreProtect, ClearEntity, DisableKickSpam, WorldEdit, DecentHolograms, WorldBorder, XsEntityDrop, NWorldPermissions, XsPlayerBan, FixIEDoubleDrop, Vault, ChairStairs, EastLandLog4jFixer, HeadBlocks, SbPlaceholder, ShadowCore, BKCommonLib, PlayerPoints, DeluxeTags, NoSa, BungeeGuard, XsMc12hFix, CMILib, spark, LiteSignIn, SakuraBind, MPoints, LiteAnnouncer, PlotSquared, QuickShop, WorldGuard, ItemCommand, YukiNoaAPI, Essentials, NeonRewardPlus, ColorMOTD, CustomChunkLimits, TrMenu, ShadowLevels, ajLeaderboards, RandomBox, SeekInventory, Multiverse-Core, Citizens, TAB, CitizensCMD, BanIt, EssentialsSpawn, KeepInventory, Residence, LockettePro, MythicMobs, BattlePass, ResidenceProtectExpand, Skript, YuhaiBlocklimit, DragonArmourers, BetterRTP, skript-yaml, MythicMobsExtension, MundoSK, skript-placeholders, DragonCore, NeigeItems, StarLibrary, DragonInventory, DragonActivity, BukkitLibrary, StarCrate

**Comment by ItsFlicker** [comment]
用2.2.0-beta4
