### ISSUE TITLE
[问题] 不支持Mysql 9.0

### ISSUE THREAD

**Issue by DustAlone** [FlickerProjects/TrChat#450]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

1. 我将TrChat安装在了Velocity代理端
2. 我将TrChat安装在子服务器当中
3. 子服务器当中的TrChat无法正常启动

### 配置文件

```YAML
Options:
  Check-Update: true
  Proxy: AUTO
  Log-Normal: '[{0}] {1}: {2}'
  Log-Private: '[{0}] {1} -> {2}: {3}'
  Log-Delete-Time: 0
  Depend-Expansions: ['player', 'server']
  Prevent-Tab-Complete: false
  Component-Max-Length: 32700
  Always-Cancel-Chat-Event: false
  Cheat-Client-Secure-Chat: true
  Use-Packets: true
  Disabled-Commands: []

Channel:
  Default: 'Normal'

Database:
  Method: SQL
  SQL:
    host: localhost
    port: 3306
    user: root
    password: mypassword
    database: trixey
    table: trchat_user_data

Redis:
  enabled: false
  host: localhost
  port: 6379
  user: ~
  password: ~
  connect: 32
  timeout: 1000

Chat:
  Anti-Repeat: 0.85
  Cooldown: '2.0s'
  Length-Limit: 100

Color:
  Chat: true
  Sign: true
  Anvil: true
  Book: true

Simple-Component:
  Hover: false
  Anvil: false
  Sign: false
```

### 日志

[17:53:11 INFO]: [TrChat] Enabling TrChat v2.1.3
[17:53:11 WARN]: [TrChat] org.bukkit.event.inventory.PrepareAnvilEvent not found, use @Ghost to turn off this warning
[17:53:11 INFO]: [PlaceholderAPI] Successfully registered internal expansion: trchat [2.1.3]
[17:53:11 WARN]: SLF4J: No SLF4J providers were found.

[17:53:11 WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation

[17:53:11 WARN]: SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.

[17:53:11 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.NBTTagLongArray

[17:53:11 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)

[17:53:11 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)

[17:53:11 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)

[17:53:11 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

[17:53:11 WARN]:        at java.base/java.lang.Class.forName0(Native Method)

[17:53:11 WARN]:        at java.base/java.lang.Class.forName(Class.java:467)

[17:53:11 WARN]:        at me.arasple.mc.trchat.taboolib.module.nms.AsmClassLoader.findClass(AsmClassLoader.kt:9)

[17:53:11 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)

[17:53:11 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

[17:53:11 WARN]:        at me.arasple.mc.trchat.taboolib.module.nms.NMSItemTagImpl1.<init>(NMSItemTag.kt:196)

[17:53:11 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

[17:53:11 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)

[17:53:11 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

[17:53:11 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)

[17:53:11 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)

[17:53:11 WARN]:        at me.arasple.mc.trchat.taboolib.module.nms.MinecraftServerUtilKt.nmsProxy(MinecraftServerUtil.kt:92)

[17:53:11 WARN]:        at me.arasple.mc.trchat.taboolib.module.nms.NMSItemTag$Companion$instance$2.invoke(NMSItemTag.kt:77)

[17:53:11 WARN]:        at me.arasple.mc.trchat.taboolib.module.nms.NMSItemTag$Companion$instance$2.invoke(NMSItemTag.kt:56)

[17:53:11 WARN]:        at kotlin1822.UnsafeLazyImpl.getValue(Lazy.kt:81)

[17:53:11 WARN]:        at me.arasple.mc.trchat.taboolib.module.nms.NMSItemTag$Companion.getInstance(NMSItemTag.kt:56)

[17:53:11 WARN]:        at me.arasple.mc.trchat.taboolib.module.nms.NMSPreheatKt.nmsPreheat$lambda$0(NMSPreheat.kt:15)

[17:53:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)

[17:53:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)

[17:53:11 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)

[17:53:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)

[17:53:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)

[17:53:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)

[17:53:11 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

[17:53:12 INFO]: [TrChat] Failed to load database! Plugin will be disabled.

[17:53:12 INFO]: com.zaxxer.hikari_4_0_3.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Client does not support authentication protocol requested by server; consider upgrading MySQL client

[17:53:12 INFO]:        at com.zaxxer.hikari_4_0_3.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)

[17:53:12 INFO]:        at com.zaxxer.hikari_4_0_3.pool.HikariPool.checkFailFast(HikariPool.java:582)

[17:53:12 INFO]:        at com.zaxxer.hikari_4_0_3.pool.HikariPool.<init>(HikariPool.java:115)

[17:53:12 INFO]:        at com.zaxxer.hikari_4_0_3.HikariDataSource.<init>(HikariDataSource.java:81)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.module.database.Database.createDataSource(Database.kt:43)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.module.database.Database.createDataSource$default(Database.kt:42)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.module.database.Host.createDataSource(Host.kt:25)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.module.database.Host.createDataSource$default(Host.kt:24)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.expansion.Database.<init>(Database.kt:6)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.setupPlayerDatabase(DatabaseHandler.kt:34)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.setupPlayerDatabase$default(DatabaseHandler.kt:18)

[17:53:12 INFO]:        at me.arasple.mc.trchat.module.internal.data.Databases.init(Databases.kt:26)

[17:53:12 INFO]:        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.platform.AwakeFunction.visit(AwakeFunction.kt:13)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:144)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:114)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:77)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.lambda$init$0(VisitorHandler.java:44)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.TabooLib$1.run(TabooLib.java:79)

[17:53:12 INFO]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56)

[17:53:12 INFO]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:83)

[17:53:12 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)

[17:53:12 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)

[17:53:12 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)

[17:53:12 INFO]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)

[17:53:12 INFO]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)

[17:53:12 INFO]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)

[17:53:12 INFO]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)

[17:53:12 INFO]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)

[17:53:12 INFO]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)

[17:53:12 INFO]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)

[17:53:12 INFO]:        at java.base/java.lang.Thread.run(Thread.java:842)

[17:53:12 INFO]: Caused by: com.zaxxer.hikari_4_0_3.pool.HikariPool$PoolInitializationException: Client does not support authentication protocol requested by server; consider upgrading MySQL client

[17:53:12 INFO]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

[17:53:12 INFO]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)

[17:53:12 INFO]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

[17:53:12 INFO]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)

[17:53:12 INFO]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)

[17:53:12 INFO]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)

[17:53:12 INFO]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)

[17:53:12 INFO]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)

[17:53:12 INFO]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)

[17:53:12 INFO]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)

[17:53:12 INFO]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)

[17:53:12 INFO]:        at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)

[17:53:12 INFO]:        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)

[17:53:12 INFO]:        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)

[17:53:12 INFO]:        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)

[17:53:12 INFO]:        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)

[17:53:12 INFO]:        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)

[17:53:12 INFO]:        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)

[17:53:12 INFO]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

[17:53:12 INFO]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)

[17:53:12 INFO]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

[17:53:12 INFO]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)

[17:53:12 INFO]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)

[17:53:12 INFO]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)

[17:53:12 INFO]:        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)

[17:53:12 INFO]:        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)

[17:53:12 INFO]:        at com.zaxxer.hikari_4_0_3.util.DriverDataSource.getConnection(DriverDataSource.java:138)

[17:53:12 INFO]:        at com.zaxxer.hikari_4_0_3.pool.PoolBase.newConnection(PoolBase.java:364)

[17:53:12 INFO]:        at com.zaxxer.hikari_4_0_3.pool.PoolBase.newPoolEntry(PoolBase.java:206)

[17:53:12 INFO]:        at com.zaxxer.hikari_4_0_3.pool.HikariPool.createPoolEntry(HikariPool.java:476)

[17:53:12 INFO]:        at com.zaxxer.hikari_4_0_3.pool.HikariPool.checkFailFast(HikariPool.java:561)

[17:53:12 INFO]:        at com.zaxxer.hikari_4_0_3.pool.HikariPool.<init>(HikariPool.java:115)

[17:53:12 INFO]:        at com.zaxxer.hikari_4_0_3.HikariDataSource.<init>(HikariDataSource.java:81)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.module.database.Database.createDataSource(Database.kt:43)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.module.database.Database.createDataSource$default(Database.kt:42)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.module.database.Host.createDataSource(Host.kt:25)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.module.database.Host.createDataSource$default(Host.kt:24)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.expansion.Database.<init>(Database.kt:6)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.setupPlayerDatabase(DatabaseHandler.kt:34)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.setupPlayerDatabase$default(DatabaseHandler.kt:18)

[17:53:12 INFO]:        at me.arasple.mc.trchat.module.internal.data.Databases.init(Databases.kt:26)

[17:53:12 INFO]:        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.platform.AwakeFunction.visit(AwakeFunction.kt:13)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:144)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:114)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:77)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.lambda$init$0(VisitorHandler.java:44)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.TabooLib$1.run(TabooLib.java:79)

[17:53:12 INFO]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56)

[17:53:12 INFO]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56)

[17:53:12 INFO]:        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:83)

[17:53:12 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)

[17:53:12 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)

[17:53:12 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)

[17:53:12 INFO]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)

[17:53:12 INFO]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)

[17:53:12 INFO]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)

[17:53:12 INFO]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)

[17:53:12 INFO]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)

[17:53:12 INFO]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)

[17:53:12 INFO]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)

[17:53:12 INFO]:        at java.base/java.lang.Thread.run(Thread.java:842)

### 服务器环境

服务器版本:
... [17:55:53 INFO]: This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
插件列表:
...[17:56:08 INFO]: Plugins (20): WorldEdit, Notbuild, PlaceholderAPI, PlugMan, ViaVersion, tpLogin, LiteBans, PlayerHide, ViaBackwards, ProtocolLib, LuckPerms, SkinsRestorer, TrChat, Vault, Citizens, ChestCommands, Essentials, AuthMe, TAB, CommandNPC

**Comment by DustAlone** [comment]
补充: 我使用 Mysql 9.0

**Comment by DustAlone** [comment]
当我使用SQLite的时候 报错如下: [12:34:30 INFO]: [TrChat] Failed to load database! Plugin will be disabled.

[12:34:30 INFO]: java.lang.AbstractMethodError: Receiver class org.sqlite.Conn does not define or inherit an implementation of the resolved method 'abstract boolean isValid(int)' of interface java.sql.Connection.

[12:34:30 INFO]:        at com.zaxxer.hikari_4_0_3.pool.PoolBase.checkValidationSupport(PoolBase.java:464)

[12:34:30 INFO]:        at com.zaxxer.hikari_4_0_3.pool.PoolBase.checkDriverSupport(PoolBase.java:447)

[12:34:30 INFO]:        at com.zaxxer.hikari_4_0_3.pool.PoolBase.setupConnection(PoolBase.java:416)

[12:34:30 INFO]:        at com.zaxxer.hikari_4_0_3.pool.PoolBase.newConnection(PoolBase.java:369)

[12:34:30 INFO]:        at com.zaxxer.hikari_4_0_3.pool.PoolBase.newPoolEntry(PoolBase.java:206)

[12:34:30 INFO]:        at com.zaxxer.hikari_4_0_3.pool.HikariPool.createPoolEntry(HikariPool.java:476)

[12:34:30 INFO]:        at com.zaxxer.hikari_4_0_3.pool.HikariPool.checkFailFast(HikariPool.java:561)

[12:34:30 INFO]:        at com.zaxxer.hikari_4_0_3.pool.HikariPool.<init>(HikariPool.java:115)

[12:34:30 INFO]:        at com.zaxxer.hikari_4_0_3.HikariDataSource.<init>(HikariDataSource.java:81)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.module.database.Database.createDataSource(Database.kt:43)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.module.database.Database.createDataSource$default(Database.kt:42)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.module.database.Host.createDataSource(Host.kt:25)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.module.database.Host.createDataSource$default(Host.kt:24)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.expansion.Database.<init>(Database.kt:6)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.setupPlayerDatabase(DatabaseHandler.kt:53)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.setupPlayerDatabase$default(DatabaseHandler.kt:52)

[12:34:30 INFO]:        at me.arasple.mc.trchat.module.internal.data.Databases.init(Databases.kt:25)

[12:34:30 INFO]:        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.common.platform.AwakeFunction.visit(AwakeFunction.kt:13)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:144)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:114)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:77)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.lambda$init$0(VisitorHandler.java:44)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.common.TabooLib$1.run(TabooLib.java:79)

[12:34:30 INFO]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56)

[12:34:30 INFO]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56)

[12:34:30 INFO]:        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:83)

[12:34:30 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)

[12:34:30 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)

[12:34:30 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)

[12:34:30 INFO]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)

[12:34:30 INFO]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)

[12:34:30 INFO]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)

[12:34:30 INFO]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)

[12:34:30 INFO]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)

[12:34:30 INFO]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)

[12:34:30 INFO]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)

[12:34:30 INFO]:        at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/11190945348
https://trchat.trixey.cc/guide/known-issues#_1-8%E7%89%88%E6%9C%AC%E5%8A%A0%E8%BD%BD%E9%94%99%E8%AF%AF

**Comment by DustAlone** [comment]
> https://github.com/TrPlugins/TrChat/actions/runs/11190945348 https://trchat.trixey.cc/guide/known-issues#_1-8%E7%89%88%E6%9C%AC%E5%8A%A0%E8%BD%BD%E9%94%99%E8%AF%AF

在此之前已经查阅过很多遍文档，将 DriverClassName 改为 com.mysql.cj.jdbc.Driver 也无法使用

**Comment by DustAlone** [comment]
SQLite: [13:49:25 INFO]: [TrChat] Failed to load database! Plugin will be disabled.
            [13:49:25 INFO]: java.lang.AbstractMethodError: org.sqlite.Conn.isValid(I)Z
MySQL com.mysql.jdbc.Driver: [13:50:12 INFO]: [TrChat] Failed to load database! Plugin will be disabled.
                                                  [13:50:12 INFO]: com.zaxxer.hikari_4_0_3.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Client does not support authentication protocol requested by server; consider upgrading MySQL client
MySQL com.mysql.cj.jdbc.Driver [13:50:51 INFO]: [TrChat] Failed to load database! Plugin will be disabled.
                                                    [13:50:51 INFO]: java.lang.RuntimeException: Failed to load driver class com.mysql.cj.jdbc.Driver in either of HikariConfig class loader or Thread context classloader

尝试删除过libraries重新下载环境，ConnectionTestQuery 也尝试过设置为 1，重新做一个端只添加量 PlaceholderAPI 与 TrChat 都会出现这种情况

**Comment by DustAlone** [comment]
提供一个测试端的链接: https://www.123pan.com/s/iMfXjv-vPgld

**Comment by DustAlone** [comment]
使用最新快照版本之后连接数据库仍然出现以上错误，但是插件可以运行了

**Comment by DustAlone** [comment]
[14:16:56 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.2.0-beta4
java.lang.IllegalStateException: unavailable
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.getDataContainer(DatabaseHandler.kt:162) ~[?:?]
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.getDataContainer(DatabaseHandlerForBukkit.kt:12) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData.isVanishing(PlayerData.kt:36) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData.<init>(PlayerData.kt:20) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:115) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion$getData$1.invoke(PlayerData.kt:114) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData$lambda$0(PlayerData.kt:114) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at me.arasple.mc.trchat.module.internal.data.PlayerData$Companion.getData(PlayerData.kt:114) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession.<init>(ChatSession.kt:132) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion$getSession$1.invoke(ChatSession.kt:107) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion$getSession$1.invoke(ChatSession.kt:107) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion.getSession$lambda$0(ChatSession.kt:107) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at me.arasple.mc.trchat.module.display.ChatSession$Companion.getSession(ChatSession.kt:107) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerBukkitChat.onBukkitChat(ListenerBukkitChat.kt:53) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:112) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:110) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:80) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:80) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:57) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1111) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1026) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:842) [?:?] 最新快照版本说话报错 并且仍然无法连接数据库
