### ISSUE TITLE
[issue] 1.12catServer加载Trchats2.1.0失败

### ISSUE THREAD

**Issue by YQingYuQWQ** [FlickerProjects/TrChat#456]
### Whether the latest version has been tried

- [X] I have updated TrChat to the latest version, and the issue is also reproduced.

### Have you checked the Wiki

- [X] I have checked the Wiki for this problem and determined that the problem exists.

### Detailed description

我从2.0.4更新到2.1.0后问题出现，并且已经删除了trchat2.0.4源文件与文件夹

### configuration file

```YAML
[10:00:32] [Server thread/ERROR]: Could not load 'plugins/TrChat-2.1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[JavaPluginLoader.class:git-CatServer-1.12.2-dae70adc]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[SimplePluginManager.class:git-CatServer-1.12.2-dae70adc]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [SimplePluginManager.class:git-CatServer-1.12.2-dae70adc]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:359) [CraftServer.class:git-CatServer-1.12.2-dae70adc]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:340) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
Caused by: java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_342]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_342]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-dae70adc]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-dae70adc]
        ... 7 more
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.AnnotationTypeMismatchExceptionProxy
        at sun.reflect.annotation.AnnotationParser.parseEnumArray(AnnotationParser.java:744) ~[?:1.8.0_342]
        at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:533) ~[?:1.8.0_342]
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355) ~[?:1.8.0_342]
        at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286) ~[?:1.8.0_342]
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120) ~[?:1.8.0_342]
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72) ~[?:1.8.0_342]
        at java.lang.Class.createAnnotationData(Class.java:3521) ~[?:1.8.0_342]
        at java.lang.Class.annotationData(Class.java:3510) ~[?:1.8.0_342]
        at java.lang.Class.getAnnotation(Class.java:3415) ~[?:1.8.0_342]
        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.checkPlatform(VisitorHandler.java:193) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.getClasses(VisitorHandler.java:179) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:74) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.inject.VisitorHandler.lambda$init$0(VisitorHandler.java:42) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLib$1.run(TabooLib.java:79) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_342]
        at me.arasple.mc.trchat.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_342]
        at me.arasple.mc.trchat.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:53) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_342]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_342]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-dae70adc]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-dae70adc]
        ... 7 more
```

### Server environment

Server version:
CatServer 1.21
Plugin list:
 Plugins (70): ChatReplace, AntiExplosion, OreTeleport, PlaceholderAPI, PlugMan, XinxinRandomConmmand, MinePay, EndBattle, AkitaRace, DragonArmourers, HealLinCatServer, DeluxeTags, NoSellLoreItemToGlobalShop, GuoItemLoreCommand, BanItem, SuperOptimization, InfiniteScoreboard, LegendaryProtect, FixRaidError, AntiCraft, PokemonEventLog, CoreProtect, LuckPerms, GSQBanItem, PokeMenu, WorldEdit, TDittoLimit, AkitaPokeSteal, PokePlaceholderAPI, Log4jJndiFixer, TitleBroadCast, PokeStar, spark, Tpr, WorldBorder, MinePaySign, LimitLegendarySpawn, Notbuild, LiteSignIn, PokeClear, BiliBiliVideo, PokemonPapiPro, PokeBeatBattleCommand, MTCard, PixelmonDialog, AkitaFlute, DragonCore, Vault, PokeRB, Lores, DragonInventory, PlotSquared, Marriage, PlayerPoints, ServerSafetyManagement, CMIEInjector, Gifts, TrMenu, Multiverse-Core, ZMusic, AkitaBottleCap, CMI, PokemonAPI, KeyExecute, NyEconomy, PokemonInfo, OnlineReward, PokePlate, ServerMarket, AyCore

**Comment by YQingYuQWQ** [comment]
server纠正：catserver 1.12

**Comment by ItsFlicker** [comment]
尝试最新release
