### ISSUE TITLE
[问题 跨服展示物品时候报错，好像是json转换异常

### ISSUE THREAD

**Issue by guyue36** [FlickerProjects/TrChat#457]
### 是否已尝试最新的版本

- [X] 我已更新 TrChat 至最新的版本, 并且同样复现该问题.

### 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 如果使用跨服功能, 是否在代理端上安装了TrChat或使用redis转发?

- [X] 我已在代理端上安装了TrChat或使用redis转发

### 详细描述

全服聊天时候 ，发送物品展示就会出现 

### 配置文件

```YAML
Options:
  Target: ALL
  Always-Listen: true

Formats:
  - condition: ~
    priority: 100
    msg:
      default-color: '&7'
      hover: '&7Date: %server_time_HH:mm:ss%'
    prefix:
      world:
        text: '&a[%multiverse_world_alias%&a]'
        hover: |-
          &r
          &8▪ &7位置: &3%multiverse_world_alias%&7, x:&2%player_x%/&7y:&2%player_y%/&7z:&2%player_z%
          &r
          &6▶ &e点击我想这位玩家发送传送请求
          &r
        command: '/tpa %player_name%'
        # (Optional) Requirement to display this JSON part for the player
        requirement: null
      称号:
        text: '&3%deluxetags_tag%'
        hover: |-
          &r
          &8▪ &a玩家称号： %deluxetags_tag%
          &8▪ &a称号描述；%deluxetags_description%
          &r▪ &a称号个数: &e%deluxetags_amount% &a个
          &6▶ &e点击我查看你的称号
          &r
        command: '/tags open'
      玩家名字:
        text: '&b%player_name%'
        hover: |-
          &8▪ &7Ping: &3%player_ping% Ms
          &r▪ &a金币: &6%vault_eco_balance% $
          &8▪ &a累计签到: &c%xiaosign_ex% &a天
          &6▶ &e点击玩家名字进行私聊
          &r
        suggest: '/msg %player_name% '
      玩家等级:
        text: '&a[%sl_title%&f-&6&l%sl_level%级&a]'
        hover: |-
          &8▪ &7生命值: &c%player_health_rounded% ❤
          &8▪ &b距离下一级：&a%sl_exp%&f/&6%sl_maxExp%
          &8▪ &6最大等级：%sl_maxlevel%
          &8▪ &b战斗力: &e%sx_value%
          &a左键打开 &7| &6该玩家的属性面板
        command: '/gyte openOtherView %player_name%'
      part-before-msg:
        text: '&4-> '
    msg:
      default-color: 'f'
      hover: '&7时间: %server_time_HH:mm:ss%'
    suffix:
      example:
        text: ''
```

### 日志

[14:11:52 WARN]: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@2e4fae66, receiver=xingyun), cancelled=false, tag=trchat:main) to listener me.arasple.mc.trchat.taboolib.platform.BungeeListener$BungeeListener@1b5cf611
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: [{"text":"{id:\"minecraft:stone\",Count:1b,tag:{}}"}]
        at com.google.gson.Gson.fromJson(Gson.java:899) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:78) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:23) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:15) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:97) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:22) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:57) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:23) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:15) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:97) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:22) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:57) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:23) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:15) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:97) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:22) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.Gson.fromJson(Gson.java:925) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:52) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at me.arasple.mc.trchat.taboolib.module.chat.Components.parseRaw(Components.kt:46) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerBungeeTransfer.execute(ListenerBungeeTransfer.kt:60) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerBungeeTransfer.onTransfer(ListenerBungeeTransfer.kt:40) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:1.8.0_401]
        at me.arasple.mc.trchat.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBungee$2.invoke(EventBus.kt:89) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$registerBungee$2.invoke(EventBus.kt:89) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBungeeListener$1.invoke(Listener.kt:58) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBungeeListener$1.invoke(Listener.kt:58) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BungeeListener$registerListener$listener$1.invoke(BungeeListener.kt:44) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BungeeListener$registerListener$listener$1.invoke(BungeeListener.kt:44) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BungeeListener$BungeeListener.handle(BungeeListener.kt:64) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_401]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_401]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:271) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:102) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_401]
Caused by: java.lang.IllegalStateException: Not a JSON Object: [{"text":"{id:\"minecraft:stone\",Count:1b,tag:{}}"}]
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.api.chat.HoverEvent$ContentItem$Serializer.deserialize(HoverEvent.java:298) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at net.md_5.bungee.api.chat.HoverEvent$ContentItem$Serializer.deserialize(HoverEvent.java:292) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Waterfall-1.12.2.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
        ... 105 more

### 服务器环境

服务器版本:
catserver 1.12.2  Waterfall-1.12.2
插件列表:
TrChat-2.1.0 TrChat-2.1.3 j均有问题
![QQ20241221-142515](https://github.com/user-attachments/assets/d65bb76a-2e54-4bed-9528-16577f3bb7aa)
![QQ20241221-142528](https://github.com/user-attachments/assets/b869472b-d150-41c5-8c61-7c7c0c92da9e)

**Comment by ItsFlicker** [comment]
https://github.com/TrPlugins/TrChat/actions/runs/13114193271
