### ISSUE TITLE
paper 1.18.1 [i] 报错

### ISSUE THREAD

**Issue by handy-git** [FlickerProjects/TrChat#46]
[19:56:20 ERROR]: Could not pass event TrChatEvent to TrChat v1.90-R4
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor31.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:37) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:37) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[TrChat-1.90-R4.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-76]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:39) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.internal.listener.ListenerChatEvent.onChat(ListenerChatEvent.kt:65) ~[TrChat-1.90-R4.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:37) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:37) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[TrChat-1.90-R4.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-76]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230) ~[paper-1.18.1.jar:git-Paper-76]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115) ~[paper-1.18.1.jar:git-Paper-76]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2185) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2096) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2062) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.server.v1_18_R1.ItemStack org.bukkit.craftbukkit.v1_18_R1.inventory.CraftItemStack.asNMSCopy(org.bukkit.inventory.ItemStack)'
        at me.arasple.mc.trchat.taboolib.module.nms.NMSGenericImpl.getName(NMSGenericImpl.java:116) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.NMSKt.getInternalName(NMS.kt:83) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.taboolib.module.nms.i18n.I18nOrigin.getName(I18nOrigin.java:85) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.taboolib.module.nms.NMSKt.getI18nName(NMS.kt:87) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.common.chat.format.objects.MsgComponent.getName(MsgComponent.kt:131) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.common.chat.format.objects.MsgComponent.toMsgTellraw$lambda-5(MsgComponent.kt:82) ~[TrChat-1.90-R4.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at me.arasple.mc.trchat.common.chat.format.objects.MsgComponent.toMsgTellraw(MsgComponent.kt:80) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.common.chat.format.Format.apply(Format.kt:33) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.common.chat.format.Format.apply$default(Format.kt:30) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.common.channel.impl.ChannelNormal.execute$TrChat(ChannelNormal.kt:31) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.common.channel.ChatChannels$ChannelListener$callChannel$1.invoke(ChatChannels.kt:49) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.common.channel.ChatChannels$ChannelListener$callChannel$1.invoke(ChatChannels.kt:48) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.taboolib.common5.MirrorKt.mirrorNow(Mirror.kt:17) ~[TrChat-1.90-R4.jar:?]
        at me.arasple.mc.trchat.common.channel.ChatChannels$ChannelListener.callChannel(ChatChannels.kt:48) ~[TrChat-1.90-R4.jar:?]
        ... 36 more

**Comment by Yurinann** [comment]
建议首先尝试使用最新版（1.90-R5）后再次查看该问题是否出现

**Comment by ItsFlicker** [comment]
使用1.90-R5即可
