### ISSUE TITLE
java.lang.NoSuchFieldException: playerConnection at class net.minecraft.server.level.EntityPlayer

### ISSUE THREAD

**Issue by ClayCoffee** [FlickerProjects/TrChat#54]
[20:02:40 WARN]: java.lang.NoSuchFieldException: playerConnection at class net.minecraft.server.level.EntityPlayer
[20:02:40 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.get(Reflex.kt:60)
[20:02:40 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.read(Reflex.kt:25)
[20:02:40 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:128)
[20:02:40 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:124)
[20:02:40 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:29)
[20:02:40 WARN]:        at TrChat-1.90-R4.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.removePlayerChannel$lambda-1(ChannelExecutor.kt:46)
[20:02:40 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[20:02:40 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[20:02:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:02:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:02:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

This server is running Paper version git-Paper-150 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0c64d40)
Plugins (34): BottledExp, ChestCommands, ClayAdvancedTowny, ClayAPI, ClayTownyFlight, ClayTownyWar, CMI, CMILib, CoreProtect, dynmap, Dynmap-Towny*, LoneLibs, LuckPerms, mcMMO, Multiverse-Core, PlaceholderAPI, PlugMan, ProtocolLib, ProtocolSupport, QuickShop, ServerBooster, Shopkeepers, Slimefun, TheNewEconomy, TitleManager, Towny, TownyChat, TrChat, UserPrefix*, Vault, ViaVersion, WorldBorder, WorldEdit, WorldGuard

**Comment by ItsFlicker** [comment]
使用1.90-R5即可

**Comment by ItsFlicker** [comment]
https://github.com/FlickerProjects/TrChat/releases/tag/1.90
