### ISSUE TITLE
Trchat在启动阶段的报错

### ISSUE THREAD

**Issue by ZoruaFox** [FlickerProjects/TrChat#67]
```
[02:56:35] [Server thread/ERROR] [org.bukkit.craftbukkit.v1_16_R3.CraftServer/]: null initializing TrChat v1.90-R5 (Is it up to date?)
java.lang.NullPointerException: null
	at me.arasple.mc.trchat.common.function.imp.Function.<init>(Function.kt:18) ~[?:?]
	at me.arasple.mc.trchat.common.function.ChatFunctions.loadFunctions(ChatFunctions.kt:24) ~[?:?]
	at me.arasple.mc.trchat.TrChat.onLoad(TrChat.kt:59) ~[?:?]
	at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onLoad(BukkitPlugin.java:52) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:303) ~[forge:1.16.5-cf698da]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:208) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:730) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
附加信息：
Using: TrChat-1.90-R5.jar
Version
**This server is running LoliServer version 1.16.5-cf698da (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.22)**

**Comment by ItsFlicker** [comment]
重新生成functions.yml是否还会报错
