### ISSUE TITLE
插件启动、玩家进出服务器报错

### ISSUE THREAD

**Issue by yuyuko233** [FlickerProjects/TrChat#69]
如题，插件启动、玩家进出服务器报错

Java版本:  OpenJDK 11.0.13.8-hotspot

核心版本: [LoliServer-ccb19cf](https://github.com/Loli-Server/LoliServer/actions/runs/1657542983)

插件版本:  [[1.90-R6] Fix #68](https://github.com/FlickerProjects/TrChat/actions/runs/1787901588)

玩家进出服务器的报错:
[https://pastebin.com/yMMUdDPs](https://pastebin.com/yMMUdDPs)

插件启动时的报错: 
```
[15:35:28][Server thread][INFO]: [TrChat] Enabling TrChat v1.90-R6
[15:35:28][Server thread][INFO]: [PlaceholderAPI] Successfully registered expansion: trchat [1.90-R6]
[15:35:28][Server thread][ERROR]: Error occurred while enabling TrChat v1.90-R6 (Is it up to date?)
java.lang.NoClassDefFoundError: org/slf4j/spi/SLF4JServiceProvider
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800) ~[?:?]
        at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698) ~[?:?]
        at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621) ~[?:?]
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:576) ~[?:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1210) ~[?:?]
        at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221) ~[?:?]
        at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265) ~[?:?]
        at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300) ~[?:?]
        at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385) ~[?:?]
        at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:104) ~[?:?]
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:147) ~[?:?]
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:139) ~[?:?]
        at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:421) ~[?:?]
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:407) ~[?:?]
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:356) ~[?:?]
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:382) ~[?:?]
        at com.zaxxer.hikari_4_0_3.HikariConfig.<clinit>(HikariConfig.java:51) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.database.Database.createDataSource(Database.kt:18) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.database.Database.createDataSource$default(Database.kt:17) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.database.Host.createDataSource(Host.kt:22) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.database.Host.createDataSource$default(Host.kt:21) ~[?:?]
        at me.arasple.mc.trchat.taboolib.expansion.Database.<init>(Database.kt:5) ~[?:?]
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.setupPlayerDatabase(DatabaseHandler.kt:31) ~[?:?]
        at me.arasple.mc.trchat.internal.data.Database.init(Database.kt:31) ~[?:?]
        at me.arasple.mc.trchat.TrChat.onEnable(TrChat.kt:67) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:61) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:412) ~[forge:1.16.5-ccb19cf]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:323) ~[forge:1.16.5-ccb19cf]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:426) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:344) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:724) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:264) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException: org.slf4j.spi.SLF4JServiceProvider
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 46 more
[15:35:28][Server thread][INFO]: [AuthMe] Enabling AuthMe v5.6.0-SNAPSHOT-b2482
```

**Comment by yuyuko233** [comment]
玩家发送消息也报错
```
> 0
[15:52:53][Server thread][INFO]: Unknown command. Type "/help" for help.
[15:52:56][Async Chat Thread - #0][ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v1.90-R6
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:571) ~[forge:?]
        at net.minecraft.network.play.ServerPlayNetHandler.chat(ServerPlayNetHandler.java:1721) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_244548_c(ServerPlayNetHandler.java:1672) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1611) ~[?:?]
        at net.minecraft.network.play.client.CChatMessagePacket.lambda$handle$0(CChatMessagePacket.java:34) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalStateException: unavailable
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.getDataContainer(DatabaseHandler.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.getDataContainer(DatabaseHandlerForBukkit.kt:7) ~[?:?]
        at me.arasple.mc.trchat.internal.data.Users.isMuted(Users.kt:73) ~[?:?]
        at me.arasple.mc.trchat.util.UtilKt.checkMute(Util.kt:26) ~[?:?]
        at me.arasple.mc.trchat.internal.listener.ListenerChatEvent.onChat(ListenerChatEvent.kt:36) ~[?:?]
        ... 23 more
[15:52:56][Async Chat Thread - #0][INFO]: <xxx> 1
[15:52:56][Netty Server IO #3][ERROR]: Could not pass event PacketSendEvent to TrChat v1.90-R6
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor66.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:571) ~[forge:?]
        at me.arasple.mc.trchat.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:39) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:18) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at net.minecraft.network.NetworkManager.lambda$sendPacket$5(NetworkManager.java:208) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [server-1.16.5-20210115.111550-extra.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [server-1.16.5-20210115.111550-extra.jar:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalStateException: unavailable
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerKt.getDataContainer(DatabaseHandler.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.expansion.DatabaseHandlerForBukkitKt.getDataContainer(DatabaseHandlerForBukkit.kt:7) ~[?:?]
        at me.arasple.mc.trchat.internal.data.Users.isFilterEnabled(Users.kt:45) ~[?:?]
        at me.arasple.mc.trchat.internal.listener.ListenerPackets.e(ListenerPackets.kt:27) ~[?:?]
        ... 28 more
```

**Comment by ItsFlicker** [comment]
请尝试更换java

**Comment by yuyuko233** [comment]
> 请尝试更换java

更换为Java8么？

**Comment by ItsFlicker** [comment]
> 更换为Java8么？

换成不是OpenJDK的

**Comment by yuyuko233** [comment]
> > 更换为Java8么？
> 
> 换成不是OpenJDK的

换成`jdk-11.0.14`还是不行

**Comment by ItsFlicker** [comment]
就是核心的问题了

**Comment by yuyuko233** [comment]
最新构建已修复
[LoliServer-1.16.5-b90f47b](https://github.com/Loli-Server/LoliServer/actions/runs/1795148053)
