### ISSUE TITLE
Waterfall Bugs

### ISSUE THREAD

**Issue by srlss123** [FlickerProjects/TrChat#70]
Error loading plugin TrChat
java.lang.RuntimeException: Runtime environment setup failed, please feedback!
    at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:140)
    at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:86)
    at me.arasple.mc.trchat.taboolib.platform.BungeePlugin.onLoad(BungeePlugin.java:45)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:344)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

In BungeeCord or waterfall-1.18-477 cloud not start trchat
I try java8 java11 java16 and java17

**Comment by srlss123** [comment]
[08:49:35 WARN]: Error loading plugin TrChat
java.lang.RuntimeException: Runtime environment setup failed, please feedback!
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:140) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:86) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BungeePlugin.onLoad(BungeePlugin.java:45) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:398) ~[waterfall-1.18-478.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:83ff18f:478]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[waterfall-1.18-478.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:83ff18f:478]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[waterfall-1.18-478.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:83ff18f:478]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.18-478.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:83ff18f:478]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.18-478.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:83ff18f:478

In Waterfall

**Comment by srlss123** [comment]
[08:49:35 WARN]: Error loading plugin TrChat
java.lang.RuntimeException: Runtime environment setup failed, please feedback!
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:140) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:86) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BungeePlugin.onLoad(BungeePlugin.java:45) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:398) ~[waterfall-1.18-478.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:83ff18f:478]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[waterfall-1.18-478.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:83ff18f:478]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[waterfall-1.18-478.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:83ff18f:478]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.18-478.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:83ff18f:478]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.18-478.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:83ff18f:478

In Waterfall

**Comment by ItsFlicker** [comment]
尝试把服务端文件夹下的libs删了重新启动

**Comment by srlss123** [comment]
不行

**Comment by ItsFlicker** [comment]
发一下插件列表

**Comment by srlss123** [comment]
插件列表 (16 + 6): BungeeJoinMessages, BungeePackFix, BungeePluginManagerPlus, BungeeTabListPlus, floodgate, Geyser-BungeeCord, LiteAnnouncer, LiteBans, LuckPerms, MiaoChat, MiniMOTD, MultiLogin, Plan, Reconnect, TrChat, yuanluServerDo, cmd_alert, cmd_find, cmd_list, cmd_send, cmd_server, reconnect_yaml.

**Comment by 157946a** [comment]
上传所有插件及核心，以便于测试

**Comment by srlss123** [comment]
https://cowtransfer.com/s/466c9d04bb2140

**Comment by srlss123** [comment]
插件只有Trchat都不行
你直接搞一个最新版本trchat塞进去100%启动不了

**Comment by ItsFlicker** [comment]
![image](https://user-images.githubusercontent.com/34670283/153333672-f626041c-2522-4c17-8330-716d2143cbc8.png)
你这个端只装trchat我可以启动

**Comment by srlss123** [comment]
你是windows server 系统吗

**Comment by srlss123** [comment]
java版本是多少呢

**Comment by ItsFlicker** [comment]
![image](https://user-images.githubusercontent.com/34670283/153333996-05f7545e-31ad-4985-be80-ee49e0098dcd.png)
windows server我去测一下

**Comment by srlss123** [comment]
环境是 windows server 我的java和你一样

**Comment by 157946a** [comment]
我的结果和他一样,也是jdk17,在vps上跑的

**Comment by srlss123** [comment]
奇怪了就我不可以吗 请你们把这个带trchat的打包直接发给我

**Comment by 157946a** [comment]
https://cowtransfer.com/s/aa534194610044

**Comment by srlss123** [comment]
已经确认该BUG属于windows server 2022专属bug
(
用了你发的立刻正常了
垃圾2022

**Comment by 157946a** [comment]
hhhhhhh

**Comment by srlss123** [comment]
![QQ图片20220210125501](https://user-images.githubusercontent.com/78008410/153339829-ed8d5bc3-4e7c-4bc0-8dfe-3dfac30703b5.png)
windows server 2022 
真的全是bug(
