### ISSUE TITLE
TrChat崩服问题与无法加载问题

### ISSUE THREAD

**Issue by MrLaoGe** [FlickerProjects/TrChat#75]
无法加载的问题：
[03:36:48 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] Runtime environment setup failed, please feedback! initializing TrChat v1.90-R6 (Is it up to date?)
java.lang.RuntimeException: Runtime environment setup failed, please feedback!
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:140) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:86) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onLoad(BukkitPlugin.java:47) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:274) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]

崩服问题：
和之前的潜影盒一样,当物品nbt超过最大上限就会崩服, 建议新增一个只读取装备Name和Lore的nbt限制, 避免数据移除

**Comment by MrLaoGe** [comment]
无法加载问题已解决, 是前置环境无法正常下载导致的

**Comment by ItsFlicker** [comment]
崩服问题将在2.0修复

**Comment by ItsFlicker** [comment]
尝试https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1 是否还有此问题

**Comment by MrLaoGe** [comment]
> 尝试 [https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1 ](https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1)是否还有此问题

还未测试,后续我会反馈测试结果, 在目前已知问题中, 这个是由NBT造成的数据内存溢出问题, 和基岩版的崩服字符串同理。最优先解应该是限制展示物品的NBT数量上限或直接新增移除展示读取物品Name, Lore, custom_model_data 这三个以外的其他NBT内容

**Comment by rewsdjad1** [comment]
我也遇到了，并且是TrChat的最新版
```
[org.bukkit.craftbukkit.v1_17_R1.CraftServer] Runtime environment setup failed, please feedback! initializing TrChat v2.0.0-PRE-4 (Is it up to date?)
java.lang.RuntimeException: Runtime environment setup failed, please feedback!
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:140) ~[TrChat-2.0.0-PRE-4.jar:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:86) ~[TrChat-2.0.0-PRE-4.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onLoad(BukkitPlugin.java:47) ~[TrChat-2.0.0-PRE-4.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:425) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by 157946a** [comment]
尝试最新版本是否还会出现

**Comment by rewsdjad1** [comment]
> 尝试最新版本是否还会出现

```
[19:50:21 INFO]: [TrChat] Loading TrChat v2.0.0-PRE-6
[19:50:21 ERROR]: [org.bukkit.craftbukkit.v1_17_R1.CraftServer] Runtime environment setup failed, please feedback! initializing TrChat v2.0.0-PRE-6 (Is it up to date?)
java.lang.RuntimeException: Runtime environment setup failed, please feedback!
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:140) ~[TrChat-2.0.0-PRE-6.jar:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:86) ~[TrChat-2.0.0-PRE-6.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onLoad(BukkitPlugin.java:47) ~[TrChat-2.0.0-PRE-6.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:425) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-409]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

还是这样，看到他的回复了，但还是不知道怎么修复

**Comment by 157946a** [comment]
> > 尝试最新版本是否还会出现
> 
> ```
> [19:50:21 INFO]: [TrChat] Loading TrChat v2.0.0-PRE-6
> [19:50:21 ERROR]: [org.bukkit.craftbukkit.v1_17_R1.CraftServer] Runtime environment setup failed, please feedback! initializing TrChat v2.0.0-PRE-6 (Is it up to date?)
> java.lang.RuntimeException: Runtime environment setup failed, please feedback!
>         at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:140) ~[TrChat-2.0.0-PRE-6.jar:?]
>         at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:86) ~[TrChat-2.0.0-PRE-6.jar:?]
>         at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onLoad(BukkitPlugin.java:47) ~[TrChat-2.0.0-PRE-6.jar:?]
>         at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:425) ~[patched_1.17.1.jar:git-Paper-409]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-409]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-409]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
>         at java.lang.Thread.run(Thread.java:833) ~[?:?]
> ```
> 
> 还是这样

你这是环境问题,尝试删除服务器根目录libs然后重新下载,也有可能是有插件冲突

**Comment by rewsdjad1** [comment]
> 



> > > 尝试最新版本是否还会出现
> > 
> > 
> > ```
> > [19:50:21 INFO]: [TrChat] Loading TrChat v2.0.0-PRE-6
> > [19:50:21 ERROR]: [org.bukkit.craftbukkit.v1_17_R1.CraftServer] Runtime environment setup failed, please feedback! initializing TrChat v2.0.0-PRE-6 (Is it up to date?)
> > java.lang.RuntimeException: Runtime environment setup failed, please feedback!
> >         at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:140) ~[TrChat-2.0.0-PRE-6.jar:?]
> >         at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:86) ~[TrChat-2.0.0-PRE-6.jar:?]
> >         at me.arasple.mc.trchat.taboolib.platform.BukkitPlugin.onLoad(BukkitPlugin.java:47) ~[TrChat-2.0.0-PRE-6.jar:?]
> >         at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:425) ~[patched_1.17.1.jar:git-Paper-409]
> >         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-409]
> >         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-409]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
> >         at java.lang.Thread.run(Thread.java:833) ~[?:?]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 还是这样
> 
> 你这是环境问题,尝试删除服务器根目录libs然后重新下载,也有可能是有插件冲突

谢谢，修好了
