### ISSUE TITLE
waterfallBC核心报错

### ISSUE THREAD

**Issue by lovemercer** [FlickerProjects/TrChat#76]
核心版本：waterfall-1.18-478.jar
Java版本:16
报错如下:

[08:26:37 ERROR]: java.net.UnknownHostException: maven.aliyun.com
[08:26:37 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
[08:26:37 ERROR]:       at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[08:26:37 ERROR]:       at java.base/java.net.Socket.connect(Socket.java:645)
[08:26:37 ERROR]:       at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:300)
[08:26:37 ERROR]:       at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[08:26:37 ERROR]:       at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[08:26:37 ERROR]:       at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:497)
[08:26:37 ERROR]:       at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:600)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:379)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1653)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[08:26:37 ERROR]:       at java.base/java.net.URL.openStream(URL.java:1192)
[08:26:37 ERROR]:       at me.arasple.mc.trchat.taboolib.common.env.RuntimeEnv.loadDependency(RuntimeEnv.java:157)
[08:26:37 ERROR]:       at me.arasple.mc.trchat.taboolib.common.env.RuntimeEnv.setup(RuntimeEnv.java:35)
[08:26:37 ERROR]:       at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:117)
[08:26:37 ERROR]:       at me.arasple.mc.trchat.taboolib.platform.BungeePlugin.<clinit>(BungeePlugin.java:32)
[08:26:37 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:26:37 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[08:26:37 ERROR]:       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:26:37 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[08:26:37 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[08:26:37 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:395)
[08:26:37 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300)
[08:26:37 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278)
[08:26:37 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[08:26:37 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[08:26:37 ERROR]: java.net.UnknownHostException: maven.aliyun.com
[08:26:37 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
[08:26:37 ERROR]:       at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[08:26:37 ERROR]:       at java.base/java.net.Socket.connect(Socket.java:645)
[08:26:37 ERROR]:       at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:300)
[08:26:37 ERROR]:       at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[08:26:37 ERROR]:       at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[08:26:37 ERROR]:       at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:497)
[08:26:37 ERROR]:       at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:600)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:379)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1653)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[08:26:37 ERROR]:       at java.base/java.net.URL.openStream(URL.java:1192)
[08:26:37 ERROR]:       at me.arasple.mc.trchat.taboolib.common.env.RuntimeEnv.loadDependency(RuntimeEnv.java:157)
[08:26:37 ERROR]:       at me.arasple.mc.trchat.taboolib.common.env.RuntimeEnv.setup(RuntimeEnv.java:35)
[08:26:37 ERROR]:       at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:117)
[08:26:37 ERROR]:       at me.arasple.mc.trchat.taboolib.platform.BungeePlugin.<clinit>(BungeePlugin.java:32)
[08:26:37 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:26:37 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[08:26:37 ERROR]:       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:26:37 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[08:26:37 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[08:26:37 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:395)
[08:26:37 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300)
[08:26:37 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278)
[08:26:37 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[08:26:37 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[08:26:37 ERROR]: java.net.UnknownHostException: maven.aliyun.com
[08:26:37 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
[08:26:37 ERROR]:       at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[08:26:37 ERROR]:       at java.base/java.net.Socket.connect(Socket.java:645)
[08:26:37 ERROR]:       at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:300)
[08:26:37 ERROR]:       at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[08:26:37 ERROR]:       at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[08:26:37 ERROR]:       at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:497)
[08:26:37 ERROR]:       at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:600)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:379)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1653)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
[08:26:37 ERROR]:       at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[08:26:37 ERROR]:       at java.base/java.net.URL.openStream(URL.java:1192)
[08:26:37 ERROR]:       at me.arasple.mc.trchat.taboolib.common.env.RuntimeEnv.loadDependency(RuntimeEnv.java:157)
[08:26:37 ERROR]:       at me.arasple.mc.trchat.taboolib.common.env.RuntimeEnv.setup(RuntimeEnv.java:35)
[08:26:37 ERROR]:       at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:117)
[08:26:37 ERROR]:       at me.arasple.mc.trchat.taboolib.platform.BungeePlugin.<clinit>(BungeePlugin.java:32)
[08:26:37 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:26:37 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[08:26:37 ERROR]:       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:26:37 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[08:26:37 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[08:26:37 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:395)
[08:26:37 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300)
[08:26:37 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278)
[08:26:37 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[08:26:37 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[08:26:37 WARN]: Error loading plugin TrChat
java.lang.RuntimeException: Runtime environment setup failed, please feedback!
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:140) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:86) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BungeePlugin.onLoad(BungeePlugin.java:45) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:398) ~[waterfall-1.18-478.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:83ff18f:478]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[waterfall-1.18-478.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:83ff18f:478]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[waterfall-1.18-478.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:83ff18f:478]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.18-478.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:83ff18f:478]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.18-478.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:83ff18f:478]

**Comment by ItsFlicker** [comment]
网络问题 
尝试在本地启动后将libs和assests文件夹复制到服务器上
