### ISSUE TITLE
在1.18.2上颜色无法生效

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [FlickerProjects/TrChat#83]
如题，并且玩家进入服务器时Console有以下报错
```
[16:31:36 INFO]: UUID of player SakuranomiyaAira is 32d4a2a6-3e89-42cc-bee6-778c4c74feee
[16:31:37 WARN]: java.lang.NoSuchFieldException: playerConnection at class net.minecraft.server.level.EntityPlayer
[16:31:37 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.get(Reflex.kt:60)
[16:31:37 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.read(Reflex.kt:25)
[16:31:37 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:128)
[16:31:37 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:124)
[16:31:37 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:29)
[16:31:37 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.addPlayerChannel$lambda-0(ChannelExecutor.kt:36)
[16:31:37 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[16:31:37 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[16:31:37 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:31:37 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:31:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

玩家离开时有以下报错
```
[16:37:33 WARN]: java.lang.NoSuchFieldException: playerConnection at class net.minecraft.server.level.EntityPlayer
[16:37:33 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.get(Reflex.kt:60)
[16:37:33 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.read(Reflex.kt:25)
[16:37:33 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:128)
[16:37:33 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:124)
[16:37:33 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:29)
[16:37:33 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.removePlayerChannel$lambda-1(ChannelExecutor.kt:46)
[16:37:33 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[16:37:33 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[16:37:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:37:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:37:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ItsFlicker** [comment]
1.18.2未支持

**Comment by ItsFlicker** [comment]
已支持
