### ISSUE TITLE
1.18.2  玩家加入或者退出游戏 TrChat-1.90-R7报错

### ISSUE THREAD

**Issue by handy-git** [FlickerProjects/TrChat#84]
[22:53:16 WARN]: java.lang.NoSuchFieldException: playerConnection at class net.minecraft.server.level.EntityPlayer
[22:53:16 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.get(Reflex.kt:60)
[22:53:16 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.read(Reflex.kt:25)
[22:53:16 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:128)
[22:53:16 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:124)
[22:53:16 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:29)
[22:53:16 WARN]:        at TrChat-1.90-R7.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.removePlayerChannel$lambda-1(ChannelExecutor.kt:46)
[22:53:16 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[22:53:16 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[22:53:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:53:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:53:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ItsFlicker** [comment]
1.18.2 已支持
