### ISSUE TITLE
1.18.2 TrChat v1.90-R7 [i]报错

### ISSUE THREAD

**Issue by handy-git** [FlickerProjects/TrChat#85]
[22:54:11 ERROR]: Could not pass event TrChatEvent to TrChat v1.90-R7
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor389.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[TrChat-1.90-R7.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1574]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:39) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.internal.listener.ListenerChatEvent.onChat(ListenerChatEvent.kt:67) ~[TrChat-1.90-R7.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor388.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[TrChat-1.90-R7.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1574]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:194) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:66) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2208) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2174) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R2.NBTTagCompound
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.MinecraftServerUtilKt.nmsClass(MinecraftServerUtil.kt:19) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.common.chat.format.objects.JsonComponent$Companion$classNBTTagCompound$2.invoke(JsonComponent.kt:83) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.common.chat.format.objects.JsonComponent$Companion$classNBTTagCompound$2.invoke(JsonComponent.kt:82) ~[TrChat-1.90-R7.jar:?]
        at kotlin1531.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.common.chat.format.objects.JsonComponent$Companion.getClassNBTTagCompound(JsonComponent.kt:82) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.common.chat.format.objects.JsonComponent$Companion.hoverItemFixed(JsonComponent.kt:101) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.common.chat.format.objects.MsgComponent.toMsgTellraw$lambda-5(MsgComponent.kt:83) ~[TrChat-1.90-R7.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at me.arasple.mc.trchat.common.chat.format.objects.MsgComponent.toMsgTellraw(MsgComponent.kt:80) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.common.chat.format.Format.apply(Format.kt:33) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.common.chat.format.Format.apply$default(Format.kt:30) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.common.channel.impl.ChannelNormal.execute$TrChat(ChannelNormal.kt:31) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.common.channel.ChatChannels$ChannelListener$callChannel$1.invoke(ChatChannels.kt:49) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.common.channel.ChatChannels$ChannelListener$callChannel$1.invoke(ChatChannels.kt:48) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.taboolib.common5.MirrorKt.mirrorNow(Mirror.kt:17) ~[TrChat-1.90-R7.jar:?]
        at me.arasple.mc.trchat.common.channel.ChatChannels$ChannelListener.callChannel(ChatChannels.kt:48) ~[TrChat-1.90-R7.jar:?]
        ... 37 more

**Comment by ItsFlicker** [comment]
1.18.2 已支持
