### ISSUE TITLE
TrChat v1.90-R6 在1.18.2运行的报错

### ISSUE THREAD

**Issue by OshinoLin** [FlickerProjects/TrChat#88]
`[16:50:15 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R2.ItemStack
[16:50:15 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153)
[16:50:15 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105)
[16:50:15 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:50:15 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[16:50:15 WARN]:        at java.base/java.lang.Class.forName(Class.java:467)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.module.nms.AsmClassLoader.findClass(AsmClassLoader.kt:9)
[16:50:15 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[16:50:15 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:50:15 WARN]:        at me.arasple.mc.trchat.api.nms.NMSImpl.optimizeNBT(NMSImpl.kt:58)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.api.nms.NMS.optimizeNBT$default(NMS.kt:25)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.common.chat.format.objects.JsonComponent$Companion.hoverItemFixed(JsonComponent.kt:99)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.common.chat.format.objects.MsgComponent.toMsgTellraw$lambda-5(MsgComponent.kt:83)
[16:50:15 WARN]:        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.common.chat.format.objects.MsgComponent.toMsgTellraw(MsgComponent.kt:80)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.common.chat.format.Format.apply(Format.kt:33)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.common.chat.format.Format.apply$default(Format.kt:30)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.common.channel.impl.ChannelGlobal.execute$TrChat(ChannelGlobal.kt:32)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.common.channel.ChatChannels$ChannelListener$callChannel$1.invoke(ChatChannels.kt:49)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.common.channel.ChatChannels$ChannelListener$callChannel$1.invoke(ChatChannels.kt:48)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.common5.MirrorKt.mirrorNow(Mirror.kt:17)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.common.channel.ChatChannels$ChannelListener.callChannel(ChatChannels.kt:48)
[16:50:15 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:50:15 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:50:15 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:50:15 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72)
[16:50:15 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[16:50:15 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:50:15 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:39)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.internal.listener.ListenerChatEvent.onChat(ListenerChatEvent.kt:59)
[16:50:15 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:50:15 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:50:15 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:50:15 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35)
[16:50:15 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72)
[16:50:15 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[16:50:15 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:50:15 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631)
[16:50:15 WARN]:        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:194)
[16:50:15 WARN]:        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:66)
[16:50:15 WARN]:        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2297)
[16:50:15 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2208)
[16:50:15 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2174)
[16:50:15 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat$1.run(PacketPlayInChat.java:40)
[16:50:15 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:50:15 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:50:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by OshinoLin** [comment]
`[16:29:03 WARN]: java.lang.NoSuchFieldException: playerConnection at class net.minecraft.server.level.EntityPlayer
[16:29:03 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.get(Reflex.kt:60)
[16:29:03 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex.read(Reflex.kt:25)
[16:29:03 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:128)
[16:29:03 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:124)
[16:29:03 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:29)
[16:29:03 WARN]:        at TrChat-1.90-R6.jar//me.arasple.mc.trchat.taboolib.module.nms.ChannelExecutor.addPlayerChannel$lambda-0(ChannelExecutor.kt:36)
[16:29:03 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[16:29:03 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[16:29:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:29:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:29:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by OshinoLin** [comment]
`[16:50:15 ERROR]: Could not pass event TrChatEvent to TrChat v1.90-R6
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[TrChat-1.90-R6.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1584]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:39) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.internal.listener.ListenerChatEvent.onChat(ListenerChatEvent.kt:59) ~[TrChat-1.90-R6.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[TrChat-1.90-R6.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1584]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:194) ~[purpur-1.18.2.jar:git-Purpur-1584]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:66) ~[purpur-1.18.2.jar:git-Purpur-1584]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2208) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2174) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R2.NBTTagCompound
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at me.arasple.mc.trchat.taboolib.module.nms.MinecraftServerUtilKt.nmsClass(MinecraftServerUtil.kt:19) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.common.chat.format.objects.JsonComponent$Companion$classNBTTagCompound$2.invoke(JsonComponent.kt:83) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.common.chat.format.objects.JsonComponent$Companion$classNBTTagCompound$2.invoke(JsonComponent.kt:82) ~[TrChat-1.90-R6.jar:?]
        at kotlin1531.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.common.chat.format.objects.JsonComponent$Companion.getClassNBTTagCompound(JsonComponent.kt:82) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.common.chat.format.objects.JsonComponent$Companion.hoverItemFixed(JsonComponent.kt:101) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.common.chat.format.objects.MsgComponent.toMsgTellraw$lambda-5(MsgComponent.kt:83) ~[TrChat-1.90-R6.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at me.arasple.mc.trchat.common.chat.format.objects.MsgComponent.toMsgTellraw(MsgComponent.kt:80) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.common.chat.format.Format.apply(Format.kt:33) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.common.chat.format.Format.apply$default(Format.kt:30) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.common.channel.impl.ChannelGlobal.execute$TrChat(ChannelGlobal.kt:32) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.common.channel.ChatChannels$ChannelListener$callChannel$1.invoke(ChatChannels.kt:49) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.common.channel.ChatChannels$ChannelListener$callChannel$1.invoke(ChatChannels.kt:48) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.taboolib.common5.MirrorKt.mirrorNow(Mirror.kt:17) ~[TrChat-1.90-R6.jar:?]
        at me.arasple.mc.trchat.common.channel.ChatChannels$ChannelListener.callChannel(ChatChannels.kt:48) ~[TrChat-1.90-R6.jar:?]
        ... 39 more
>`

**Comment by ItsFlicker** [comment]
用R8
