### ISSUE TITLE
trchat插件跟PlayMoreSounds聊天声音冲突了

### ISSUE THREAD

**Issue by yuankun1** [FlickerProjects/TrChat#91]
PlayMoreSounds聊天会发出音效
但是加上trchat他就阻挡了PlayMoreSounds插件的聊天音效

**Comment by ItsFlicker** [comment]
尝试https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1 是否还有此问题

**Comment by yuankun1** [comment]
> 尝试https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1 是否还有此问题
虽然不在跟声音冲突了 但是会吧的世界变量刷报错
[02:02:15 ERROR]: Could not pass event AsyncPlayerChatEvent to TrChat v2.0.0-PRE-1
 java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_291]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_291]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_291]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[?:?]
        at me.arasple.mc.trchat.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
        at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1508) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1443) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.lambda$processPacket$0(CPacketChatMessage.java:42) ~[la.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_291]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_291]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_291]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_291]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
Caused by: java.lang.NullPointerException
        at com.extendedclip.papi.expansion.multiverse.MultiverseExpansion.onPlaceholderRequest(MultiverseExpansion.java:51) ~[?:?]
        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:161) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98) ~[?:?]
        at me.arasple.mc.trchat.taboolib.platform.compat.PlaceholderExpansionKt.replacePlaceholder(PlaceholderExpansion.kt:15) ~[?:?]
        at me.arasple.mc.trchat.module.display.format.part.json.Text.process(Text.kt:22) ~[?:?]
        at me.arasple.mc.trchat.module.display.format.part.json.Text.process$default(Text.kt:20) ~[?:?]
        at me.arasple.mc.trchat.module.display.format.JsonComponent.toTextComponent(JsonComponent.kt:24) ~[?:?]
        at me.arasple.mc.trchat.module.display.channel.Channel.execute(Channel.kt:77) ~[?:?]
        at me.arasple.mc.trchat.module.internal.listener.ListenerChatEvent.onChat(ListenerChatEvent.kt:68) ~[?:?]
        ... 21 more
[01:55:33 WARN]: 获取变量值时,对应插件处理出现异常->%multiverse_world_alias%
 java.lang.NullPointerException: null
        at com.extendedclip.papi.expansion.multiverse.MultiverseExpansion.onPlaceholderRequest(MultiverseExpansion.java:51) ~[?:?]
        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:161) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98) ~[?:?]
        at eos.moe.dragoncore.listener.PlaceholderListener.onPlaceholder(PlaceholderListener.java:25) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor524.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:73) ~[TimedEventExecutor.class:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
        at eos.moe.dragoncore.api.event.SyncPlaceholderEvent.callEvent(SyncPlaceholderEvent.java:48) ~[?:?]
        at eos.moe.dragoncore.network.receiver.MessagePlaceholder.onMessage(MessagePlaceholder.java:27) ~[?:?]
        at eos.moe.dragoncore.network.PluginMessageReceiver.lambda$onPluginMessageReceived$0(PluginMessageReceiver.java:54) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) [CraftTask.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:50) [CraftAsyncTask.class:?]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [ServerSchedulerReportingWrapper.class:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_291]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_291]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]

**Comment by yuankun1** [comment]
> 尝试https://github.com/FlickerProjects/TrChat/releases/tag/v2.0.0-PRE-1 是否还有此问题

不过更新一下papi 世界变量就不会报错了

**Comment by yuankun1** [comment]
[02:11:05 INFO]: [TrChat] Error occurred while catching cloud thesaurus.
[02:11:05 INFO]:          Read timed out
[02:11:05 INFO]:          java.net.SocketInputStream.socketRead0(Native Method)
[02:11:05 INFO]:          java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[02:11:05 INFO]:          java.net.SocketInputStream.read(SocketInputStream.java:171)
[02:11:05 INFO]:          java.net.SocketInputStream.read(SocketInputStream.java:141)
[02:11:05 INFO]:          sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:475)
[02:11:05 INFO]:          sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:469)
[02:11:05 INFO]:          sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:69)
[02:11:05 INFO]:          sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1239)
[02:11:05 INFO]:          sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:75)
[02:11:05 INFO]:          sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:926)
[02:11:05 INFO]:          java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
[02:11:05 INFO]:          java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
[02:11:05 INFO]:          java.io.BufferedInputStream.read(BufferedInputStream.java:345)
[02:11:05 INFO]:          sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
[02:11:05 INFO]:          sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
[02:11:05 INFO]:          sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
[02:11:05 INFO]:          sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[02:11:05 INFO]:          sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[02:11:05 INFO]:          java.net.URL.openStream(URL.java:1092)
[02:11:05 INFO]:          me.arasple.mc.trchat.module.display.filter.ChatFilter.catchCloudThesaurus(ChatFilter.kt:101)
[02:11:05 INFO]:          me.arasple.mc.trchat.module.display.filter.ChatFilter.loadCloudFilter(ChatFilter.kt:80)
[02:11:05 INFO]:          me.arasple.mc.trchat.module.display.filter.ChatFilter.access$loadCloudFilter(ChatFilter.kt:28)
[02:11:05 INFO]:          me.arasple.mc.trchat.module.display.filter.ChatFilter$loadFilter$2.invoke(ChatFilter.kt:63)
[02:11:05 INFO]:          me.arasple.mc.trchat.module.display.filter.ChatFilter$loadFilter$2.invoke(ChatFilter.kt:62)
[02:11:05 INFO]:          me.arasple.mc.trchat.taboolib.platform.BukkitExecutor$submit$6.run(BukkitExecutor.kt:89)
[02:11:05 INFO]:          org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[02:11:05 INFO]:          org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:50)
[02:11:05 INFO]:          com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[02:11:05 INFO]:          java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[02:11:05 INFO]:          java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[02:11:05 INFO]:          java.lang.Thread.run(Thread.java:748)
[02:11:05 INFO]: [TrChat] 无法从云端更新敏感词库......
还有这个报错....

**Comment by ItsFlicker** [comment]
> [02:11:05 INFO]: [TrChat] Error occurred while catching cloud thesaurus. [02:11:05 INFO]: Read timed out [02:11:05 INFO]: java.net.SocketInputStream.socketRead0(Native Method) [02:11:05 INFO]: java.net.SocketInputStream.socketRead(SocketInputStream.java:116) [02:11:05 INFO]: java.net.SocketInputStream.read(SocketInputStream.java:171) [02:11:05 INFO]: java.net.SocketInputStream.read(SocketInputStream.java:141) [02:11:05 INFO]: sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:475) [02:11:05 INFO]: sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:469) [02:11:05 INFO]: sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:69) [02:11:05 INFO]: sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1239) [02:11:05 INFO]: sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:75) [02:11:05 INFO]: sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:926) [02:11:05 INFO]: java.io.BufferedInputStream.fill(BufferedInputStream.java:246) [02:11:05 INFO]: java.io.BufferedInputStream.read1(BufferedInputStream.java:286) [02:11:05 INFO]: java.io.BufferedInputStream.read(BufferedInputStream.java:345) [02:11:05 INFO]: sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735) [02:11:05 INFO]: sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) [02:11:05 INFO]: sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593) [02:11:05 INFO]: sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) [02:11:05 INFO]: sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) [02:11:05 INFO]: java.net.URL.openStream(URL.java:1092) [02:11:05 INFO]: me.arasple.mc.trchat.module.display.filter.ChatFilter.catchCloudThesaurus(ChatFilter.kt:101) [02:11:05 INFO]: me.arasple.mc.trchat.module.display.filter.ChatFilter.loadCloudFilter(ChatFilter.kt:80) [02:11:05 INFO]: me.arasple.mc.trchat.module.display.filter.ChatFilter.access$loadCloudFilter(ChatFilter.kt:28) [02:11:05 INFO]: me.arasple.mc.trchat.module.display.filter.ChatFilter$loadFilter$2.invoke(ChatFilter.kt:63) [02:11:05 INFO]: me.arasple.mc.trchat.module.display.filter.ChatFilter$loadFilter$2.invoke(ChatFilter.kt:62) [02:11:05 INFO]: me.arasple.mc.trchat.taboolib.platform.BukkitExecutor$submit$6.run(BukkitExecutor.kt:89) [02:11:05 INFO]: org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) [02:11:05 INFO]: org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:50) [02:11:05 INFO]: com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [02:11:05 INFO]: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [02:11:05 INFO]: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [02:11:05 INFO]: java.lang.Thread.run(Thread.java:748) [02:11:05 INFO]: [TrChat] 无法从云端更新敏感词库...... 还有这个报错....

网络问题
